/* ============================================================
   Routime — Service Worker
   Cache-first strategy for the app shell (works offline).
   When adding new files: add them to ARCHIVOS and bump VERSION.
   ============================================================ */
var VERSION = 'routime-v6';

var ARCHIVOS = [
  './index.html',
  './manifest.json',
  './site/index.html',
  './site/styles.css',
  './site/strings.es.js',
  './site/strings.en.js',
  './team/index.html',
  './team/styles.css',
  './team/strings.es.js',
  './team/strings.en.js',
  './settings/index.html',
  './settings/app.js',
  './settings/styles.css',
  './settings/strings.es.js',
  './settings/strings.en.js',
  './about/index.html',
  './about/styles.css',
  './about/strings.es.js',
  './about/strings.en.js',
  './legal/index.html',
  './legal/styles.css',
  './legal/strings.es.js',
  './legal/strings.en.js',
  './assets/css/tokens.css',
  './assets/css/base.css',
  './assets/css/components.css',
  './assets/fonts/atkinson-hyperlegible-400.woff2',
  './assets/fonts/atkinson-hyperlegible-700.woff2',
  './assets/fonts/nunito-variable.woff2',
  './assets/js/utils.js',
  './assets/js/i18n.js',
  './assets/js/tts.js',
  './assets/js/storage.js',
  './assets/js/feedback.js',
  './assets/js/dinero.js',
  './assets/img/icono.svg',
  './assets/img/icono-192.png',
  './assets/img/icono-512.png',
  './assets/img/pile-dust.svg',
  './tools/chess/index.html',
  './tools/chess/app.js',
  './tools/chess/data.js',
  './tools/chess/strings.es.js',
  './tools/chess/strings.en.js',
  './tools/chess/styles.css',
  './tools/catch/index.html',
  './tools/catch/app.js',
  './tools/catch/data.js',
  './tools/catch/strings.es.js',
  './tools/catch/strings.en.js',
  './tools/catch/styles.css',
  './tools/connect-dots/index.html',
  './tools/connect-dots/app.js',
  './tools/connect-dots/data.js',
  './tools/connect-dots/strings.es.js',
  './tools/connect-dots/strings.en.js',
  './tools/connect-dots/styles.css',
  './tools/calm/index.html',
  './tools/calm/app.js',
  './tools/calm/data.js',
  './tools/calm/strings.es.js',
  './tools/calm/strings.en.js',
  './tools/calm/styles.css',
  './tools/categories/index.html',
  './tools/categories/app.js',
  './tools/categories/data.js',
  './tools/categories/strings.es.js',
  './tools/categories/strings.en.js',
  './tools/categories/styles.css',
  './tools/bullying-chat/index.html',
  './tools/bullying-chat/app.js',
  './tools/bullying-chat/data.js',
  './tools/bullying-chat/strings.es.js',
  './tools/bullying-chat/strings.en.js',
  './tools/bullying-chat/styles.css',
  './tools/safe-chat/index.html',
  './tools/safe-chat/app.js',
  './tools/safe-chat/data.js',
  './tools/safe-chat/strings.es.js',
  './tools/safe-chat/strings.en.js',
  './tools/safe-chat/styles.css',
  './tools/coloring/index.html',
  './tools/coloring/app.js',
  './tools/coloring/data.js',
  './tools/coloring/strings.es.js',
  './tools/coloring/strings.en.js',
  './tools/coloring/styles.css',
  './tools/comedy-club/index.html',
  './tools/comedy-club/app.js',
  './tools/comedy-club/data.js',
  './tools/comedy-club/strings.es.js',
  './tools/comedy-club/strings.en.js',
  './tools/comedy-club/styles.css',
  './tools/builders/index.html',
  './tools/builders/app.js',
  './tools/builders/data.js',
  './tools/builders/strings.es.js',
  './tools/builders/strings.en.js',
  './tools/builders/styles.css',
  './tools/connect-four/index.html',
  './tools/connect-four/app.js',
  './tools/connect-four/data.js',
  './tools/connect-four/strings.es.js',
  './tools/connect-four/strings.en.js',
  './tools/connect-four/styles.css',
  './tools/checkers/index.html',
  './tools/checkers/app.js',
  './tools/checkers/data.js',
  './tools/checkers/strings.es.js',
  './tools/checkers/strings.en.js',
  './tools/checkers/styles.css',
  './tools/idioms/index.html',
  './tools/idioms/app.js',
  './tools/idioms/data.js',
  './tools/idioms/strings.es.js',
  './tools/idioms/strings.en.js',
  './tools/idioms/styles.css',
  './tools/double-meaning/index.html',
  './tools/double-meaning/app.js',
  './tools/double-meaning/data.js',
  './tools/double-meaning/strings.es.js',
  './tools/double-meaning/strings.en.js',
  './tools/double-meaning/styles.css',
  './tools/differences/index.html',
  './tools/differences/app.js',
  './tools/differences/data.js',
  './tools/differences/strings.es.js',
  './tools/differences/strings.en.js',
  './tools/differences/styles.css',
  './tools/domino/index.html',
  './tools/domino/app.js',
  './tools/domino/data.js',
  './tools/domino/strings.es.js',
  './tools/domino/strings.en.js',
  './tools/domino/styles.css',
  './tools/where-is/index.html',
  './tools/where-is/app.js',
  './tools/where-is/data.js',
  './tools/where-is/strings.es.js',
  './tools/where-is/strings.en.js',
  './tools/where-is/styles.css',
  './tools/where-to-store/index.html',
  './tools/where-to-store/app.js',
  './tools/where-to-store/data.js',
  './tools/where-to-store/strings.es.js',
  './tools/where-to-store/strings.en.js',
  './tools/where-to-store/styles.css',
  './tools/ecos/index.html',
  './tools/ecos/app.js',
  './tools/ecos/data.js',
  './tools/ecos/strings.es.js',
  './tools/ecos/strings.en.js',
  './tools/ecos/styles.css',
  './tools/path/index.html',
  './tools/path/app.js',
  './tools/path/data.js',
  './tools/path/strings.es.js',
  './tools/path/strings.en.js',
  './tools/path/styles.css',
  './tools/theatre/index.html',
  './tools/theatre/app.js',
  './tools/theatre/data.js',
  './tools/theatre/strings.es.js',
  './tools/theatre/strings.en.js',
  './tools/theatre/styles.css',
  './tools/emotions/index.html',
  './tools/emotions/app.js',
  './tools/emotions/data.js',
  './tools/emotions/strings.es.js',
  './tools/emotions/strings.en.js',
  './tools/emotions/styles.css',
  './tools/emergencies/index.html',
  './tools/emergencies/app.js',
  './tools/emergencies/data.js',
  './tools/emergencies/strings.es.js',
  './tools/emergencies/strings.en.js',
  './tools/emergencies/styles.css',
  './tools/phone-numbers/index.html',
  './tools/phone-numbers/app.js',
  './tools/phone-numbers/data.js',
  './tools/phone-numbers/strings.es.js',
  './tools/phone-numbers/strings.en.js',
  './tools/phone-numbers/styles.css',
  './tools/doctor-visit/index.html',
  './tools/doctor-visit/app.js',
  './tools/doctor-visit/data.js',
  './tools/doctor-visit/strings.es.js',
  './tools/doctor-visit/strings.en.js',
  './tools/doctor-visit/styles.css',
  './tools/first-aid-kit/index.html',
  './tools/first-aid-kit/app.js',
  './tools/first-aid-kit/data.js',
  './tools/first-aid-kit/strings.es.js',
  './tools/first-aid-kit/strings.en.js',
  './tools/first-aid-kit/styles.css',
  './tools/my-details/index.html',
  './tools/my-details/app.js',
  './tools/my-details/data.js',
  './tools/my-details/strings.es.js',
  './tools/my-details/strings.en.js',
  './tools/my-details/styles.css',
  './tools/fit/index.html',
  './tools/fit/app.js',
  './tools/fit/data.js',
  './tools/fit/strings.es.js',
  './tools/fit/strings.en.js',
  './tools/fit/styles.css',
  './tools/friends/index.html',
  './tools/friends/app.js',
  './tools/friends/data.js',
  './tools/friends/strings.es.js',
  './tools/friends/strings.en.js',
  './tools/friends/styles.css',
  './tools/self-esteem/index.html',
  './tools/self-esteem/app.js',
  './tools/self-esteem/data.js',
  './tools/self-esteem/strings.es.js',
  './tools/self-esteem/strings.en.js',
  './tools/self-esteem/styles.css',
  './tools/resilience/index.html',
  './tools/resilience/app.js',
  './tools/resilience/data.js',
  './tools/resilience/strings.es.js',
  './tools/resilience/strings.en.js',
  './tools/resilience/styles.css',
  './tools/trust-circle/index.html',
  './tools/trust-circle/app.js',
  './tools/trust-circle/data.js',
  './tools/trust-circle/strings.es.js',
  './tools/trust-circle/strings.en.js',
  './tools/trust-circle/styles.css',
  './tools/turns-mirrors/index.html',
  './tools/turns-mirrors/app.js',
  './tools/turns-mirrors/data.js',
  './tools/turns-mirrors/strings.es.js',
  './tools/turns-mirrors/strings.en.js',
  './tools/turns-mirrors/styles.css',
  './tools/street/index.html',
  './tools/street/app.js',
  './tools/street/data.js',
  './tools/street/strings.es.js',
  './tools/street/strings.en.js',
  './tools/street/styles.css',
  './tools/house/index.html',
  './tools/house/app.js',
  './tools/house/data.js',
  './tools/house/strings.es.js',
  './tools/house/strings.en.js',
  './tools/house/styles.css',
  './tools/shopping/index.html',
  './tools/shopping/app.js',
  './tools/shopping/data.js',
  './tools/shopping/strings.es.js',
  './tools/shopping/strings.en.js',
  './tools/shopping/styles.css',
  './tools/healthy-food/index.html',
  './tools/healthy-food/app.js',
  './tools/healthy-food/data.js',
  './tools/healthy-food/strings.es.js',
  './tools/healthy-food/strings.en.js',
  './tools/healthy-food/styles.css',
  './tools/sentence/index.html',
  './tools/sentence/app.js',
  './tools/sentence/data.js',
  './tools/sentence/strings.es.js',
  './tools/sentence/strings.en.js',
  './tools/sentence/styles.css',
  './tools/shop/index.html',
  './tools/shop/app.js',
  './tools/shop/data.js',
  './tools/shop/strings.es.js',
  './tools/shop/strings.en.js',
  './tools/shop/styles.css',
  './tools/task-list/index.html',
  './tools/task-list/app.js',
  './tools/task-list/data.js',
  './tools/task-list/strings.es.js',
  './tools/task-list/strings.en.js',
  './tools/task-list/styles.css',
  './tools/my-agenda/index.html',
  './tools/my-agenda/app.js',
  './tools/my-agenda/data.js',
  './tools/my-agenda/strings.es.js',
  './tools/my-agenda/strings.en.js',
  './tools/my-agenda/styles.css',
  './tools/post-or-not/index.html',
  './tools/post-or-not/app.js',
  './tools/post-or-not/data.js',
  './tools/post-or-not/strings.es.js',
  './tools/post-or-not/strings.en.js',
  './tools/post-or-not/styles.css',
  './tools/social-safety/index.html',
  './tools/social-safety/app.js',
  './tools/social-safety/data.js',
  './tools/social-safety/strings.es.js',
  './tools/social-safety/strings.en.js',
  './tools/social-safety/styles.css',
  './tools/sexual-health/index.html',
  './tools/sexual-health/app.js',
  './tools/sexual-health/data.js',
  './tools/sexual-health/strings.es.js',
  './tools/sexual-health/strings.en.js',
  './tools/sexual-health/styles.css',
  './tools/blocks/index.html',
  './tools/blocks/app.js',
  './tools/blocks/data.js',
  './tools/blocks/strings.es.js',
  './tools/blocks/strings.en.js',
  './tools/blocks/styles.css',
  './tools/my-body/index.html',
  './tools/my-body/app.js',
  './tools/my-body/data.js',
  './tools/my-body/strings.es.js',
  './tools/my-body/strings.en.js',
  './tools/my-body/styles.css',
  './tools/good-manners/index.html',
  './tools/good-manners/app.js',
  './tools/good-manners/data.js',
  './tools/good-manners/strings.es.js',
  './tools/good-manners/strings.en.js',
  './tools/good-manners/styles.css',
  './tools/dictionary/index.html',
  './tools/dictionary/app.js',
  './tools/dictionary/data.js',
  './tools/dictionary/strings.es.js',
  './tools/dictionary/strings.en.js',
  './tools/dictionary/styles.css',
  './tools/spelling/index.html',
  './tools/spelling/app.js',
  './tools/spelling/data.js',
  './tools/spelling/strings.es.js',
  './tools/spelling/strings.en.js',
  './tools/spelling/styles.css',
  './tools/colored-spelling/index.html',
  './tools/colored-spelling/app.js',
  './tools/colored-spelling/data.js',
  './tools/colored-spelling/strings.es.js',
  './tools/colored-spelling/strings.en.js',
  './tools/colored-spelling/styles.css',
  './tools/word-search/index.html',
  './tools/word-search/app.js',
  './tools/word-search/data.js',
  './tools/word-search/strings.es.js',
  './tools/word-search/strings.en.js',
  './tools/word-search/styles.css',
  './tools/vocabulary/index.html',
  './tools/vocabulary/app.js',
  './tools/vocabulary/data.js',
  './tools/vocabulary/strings.es.js',
  './tools/vocabulary/strings.en.js',
  './tools/vocabulary/styles.css',
  './tools/pairs/index.html',
  './tools/pairs/app.js',
  './tools/pairs/data.js',
  './tools/pairs/strings.es.js',
  './tools/pairs/strings.en.js',
  './tools/pairs/styles.css',
  './tools/times-of-day/index.html',
  './tools/times-of-day/app.js',
  './tools/times-of-day/data.js',
  './tools/times-of-day/strings.es.js',
  './tools/times-of-day/strings.en.js',
  './tools/times-of-day/styles.css',
  './tools/clock/index.html',
  './tools/clock/app.js',
  './tools/clock/data.js',
  './tools/clock/strings.es.js',
  './tools/clock/strings.en.js',
  './tools/clock/styles.css',
  './tools/piano-keys/index.html',
  './tools/piano-keys/app.js',
  './tools/piano-keys/data.js',
  './tools/piano-keys/strings.es.js',
  './tools/piano-keys/strings.en.js',
  './tools/piano-keys/styles.css',
  './tools/whats-missing/index.html',
  './tools/whats-missing/app.js',
  './tools/whats-missing/data.js',
  './tools/whats-missing/strings.es.js',
  './tools/whats-missing/strings.en.js',
  './tools/whats-missing/styles.css',
  './tools/be-prepared/index.html',
  './tools/be-prepared/app.js',
  './tools/be-prepared/data.js',
  './tools/be-prepared/strings.es.js',
  './tools/be-prepared/strings.en.js',
  './tools/be-prepared/styles.css',
  './tools/while-help-arrives/index.html',
  './tools/while-help-arrives/app.js',
  './tools/while-help-arrives/data.js',
  './tools/while-help-arrives/strings.es.js',
  './tools/while-help-arrives/strings.en.js',
  './tools/while-help-arrives/styles.css',
  './tools/what-to-wear/index.html',
  './tools/what-to-wear/app.js',
  './tools/what-to-wear/data.js',
  './tools/what-to-wear/strings.es.js',
  './tools/what-to-wear/strings.en.js',
  './tools/what-to-wear/styles.css',
  './tools/what-do-i-need/index.html',
  './tools/what-do-i-need/app.js',
  './tools/what-do-i-need/data.js',
  './tools/what-do-i-need/strings.es.js',
  './tools/what-do-i-need/strings.en.js',
  './tools/what-do-i-need/styles.css',
  './tools/what-first/index.html',
  './tools/what-first/app.js',
  './tools/what-first/data.js',
  './tools/what-first/strings.es.js',
  './tools/what-first/strings.en.js',
  './tools/what-first/styles.css',
  './tools/routines/index.html',
  './tools/routines/app.js',
  './tools/routines/data.js',
  './tools/routines/strings.es.js',
  './tools/routines/strings.en.js',
  './tools/routines/styles.css',
  './tools/school-rules/index.html',
  './tools/school-rules/app.js',
  './tools/school-rules/data.js',
  './tools/school-rules/strings.es.js',
  './tools/school-rules/strings.en.js',
  './tools/school-rules/styles.css',
  './tools/signs/index.html',
  './tools/signs/app.js',
  './tools/signs/data.js',
  './tools/signs/strings.es.js',
  './tools/signs/strings.en.js',
  './tools/signs/styles.css',
  './tools/situations/index.html',
  './tools/situations/app.js',
  './tools/situations/data.js',
  './tools/situations/strings.es.js',
  './tools/situations/strings.en.js',
  './tools/situations/styles.css',
  './tools/visual-sudoku/index.html',
  './tools/visual-sudoku/app.js',
  './tools/visual-sudoku/data.js',
  './tools/visual-sudoku/strings.es.js',
  './tools/visual-sudoku/strings.en.js',
  './tools/visual-sudoku/styles.css',
  './tools/tracing/index.html',
  './tools/tracing/app.js',
  './tools/tracing/data.js',
  './tools/tracing/strings.es.js',
  './tools/tracing/strings.en.js',
  './tools/tracing/styles.css',
  './tools/tic-tac-toe/index.html',
  './tools/tic-tac-toe/app.js',
  './tools/tic-tac-toe/data.js',
  './tools/tic-tac-toe/strings.es.js',
  './tools/tic-tac-toe/strings.en.js',
  './tools/tic-tac-toe/styles.css'
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(VERSION).then(function (cache) {
      /* cache: 'reload' avoids storing stale copies from the browser's HTTP cache */
      var peticiones = ARCHIVOS.map(function (a) {
        return new Request(a, { cache: 'reload' });
      });
      return cache.addAll(peticiones);
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (claves) {
      return Promise.all(
        claves.filter(function (c) { return c !== VERSION; })
          .map(function (c) { return caches.delete(c); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then(function (respuesta) {
      if (respuesta) return respuesta;
      return fetch(event.request).then(function (r) {
        /* Also cache new same-origin resources and fonts — but never cache
           a redirect. Safari (and the Fetch spec) rejects a top-level
           navigation served by the SW that carries a Location header
           ("Response served by service worker has redirections"), so we
           follow the redirect and cache only the final 200. */
        if (r.status === 200) {
          var copia = r.clone();
          caches.open(VERSION).then(function (cache) {
            cache.put(event.request, copia);
          });
        }
        return r;
      }).catch(function () {
        /* Offline / network failure. Don't serve site/index.html here:
           its relative paths only resolve correctly under /site/, so
           Safari would either break the layout or refuse the response
           as a phantom redirect. Reply with a tiny inline HTML that
           stays at the current URL and offers a link to the landing. */
        return new Response(
          '<!doctype html><html lang="es"><head><meta charset="utf-8">' +
          '<meta name="viewport" content="width=device-width,initial-scale=1">' +
          '<title>Sin conexión</title><style>body{font-family:system-ui,sans-serif;' +
          'margin:2rem auto;max-width:32rem;padding:0 1rem;line-height:1.5}' +
          'a{color:#1d4ed8}</style></head><body>' +
          '<h1>Sin conexión</h1>' +
          '<p>No hemos podido cargar esta página. Comprueba tu conexión a ' +
          'Internet y vuelve a intentarlo.</p>' +
          '<p><a href="./site/index.html">Volver a la portada</a></p>' +
          '</body></html>',
          { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
        );
      });
    })
  );
});
