/* ============================================================
   Routime — Textos de la-tienda (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "🏪 La Tienda",
    "instruccion": "Aquí usas el dinero como en la vida real: haces una compra entera, controlas lo que te queda y piensas si un precio está bien.",
    "volverMenu": "← Menú",
    "elegirNivel": "Elige el nivel",
    "vecesTexto": "{n} veces",
    "btnOtroNivel": "Elegir otro nivel",
    "si": "Sí",
    "no": "No",
    "ariaMesa": "Dinero sobre la mesa",
    "menuTienda": "Una compra",
    "menuTiendaDetalle": "De principio a fin: mira, paga y revisa.",
    "menuQuedame": "¿Qué me queda?",
    "menuQuedameDetalle": "Vas comprando. Calcula lo que te queda.",
    "menuMucho": "¿Mucho o poco?",
    "menuMuchoDetalle": "¿Ese precio está bien o es demasiado?",
    "menuFiar": "¿Es de fiar?",
    "menuFiarDetalle": "Un precio muy bajo puede ser una trampa.",
    "instruccionTienda": "Vas a hacer una compra entera: mira si te llega, paga y revisa el cambio.",
    "instruccionQuedame": "Empiezas con un dinero. Vas comprando cosas. Calcula cuánto te queda.",
    "instruccionMucho": "Mira el producto y su precio. Piensa si está bien o es demasiado dinero.",
    "instruccionFiar": "Mira el precio de una ganga. Piensa si te puedes fiar o es sospechoso: puede ser una estafa.",
    "compraDe": "Compra {n} de {t}",
    "paso1Enunciado": "{nombre} cuesta {precio}. Este es tu dinero. ¿Te llega?",
    "pistaPaso1": "Cuenta tu dinero, despacio. Después mira el precio.",
    "explicaLlega": "Tienes {total}. El precio es {precio}. Sí te llega.",
    "explicaNoLlega": "Tienes {total}. El precio es {precio}. No te llega.",
    "resolucionNoLlega": "Eliges algo más barato: {nombre}, por {precio}.",
    "paso2Enunciado": "Paga. El precio es {precio}. Toca tu dinero para ponerlo en el mostrador.",
    "hasPuesto": "En el mostrador: {total}",
    "btnPagar": "Pagar",
    "pagoJusto": "¡Pagas justo! No hay cambio. Compra terminada.",
    "faltaDinero1": "Falta dinero. Mira el precio y mira el mostrador.",
    "faltaDinero2": "Faltan {dif}. Pon más dinero en el mostrador.",
    "ariaQuitarDelMostrador": "Quitar {d} del mostrador",
    "paso3Enunciado": "Pagaste {pagado}. El precio es {precio}. Te devuelven esto. ¿Está bien el cambio?",
    "pistaPaso3": "Cuenta el dinero que te han devuelto. Piensa cuánto tenían que devolverte.",
    "explicaCambioBien": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está bien.",
    "explicaCambioMal": "El cambio bueno es {bueno}. Te han devuelto {mostrado}. Está mal.",
    "dia1": "lunes",
    "dia2": "martes",
    "dia3": "miércoles",
    "dia4": "jueves",
    "dia5": "viernes",
    "dia6": "sábado",
    "pistaPaga": "🤔 Mira lo que quieres y mira cuánto te queda. ¿Te llega?",
    "explicacionPagaSabado": "✅ Hoy es sábado: te toca el capricho de la semana. Te quedan {queda}.",
    "resolucionCambioBien": "El cambio está bien. ¡Compra terminada!",
    "resolucionCambioMal": "Bien visto: el cambio estaba mal. Se lo dices al dependiente y te da el cambio bueno.",
    "btnContinuar": "Continuar →",
    "resumenTienda": "Compras redondas: {n} de {t}.",
    "enunciadoQuedame": "Tienes {saldo}. Compras {nombre}. Cuesta {gasto}. ¿Cuánto te queda?",
    "pistaQuedame": "Mira el dinero de la mesa. Quita lo que cuesta y cuenta lo que queda.",
    "explicacionQuedameBien": "¡Eso es! Tenías {saldo}. {nombre} cuesta {gasto}. Te quedan {queda}.",
    "explicacionQuedameCasi": "Mira: tenías {saldo}. {nombre} cuesta {gasto}. Te quedan {queda}.",
    "resumenQuedame": "Has calculado bien {n} de {t}.",
    "enunciadoMucho": "{nombre} cuesta {mostrado}. ¿Está bien de precio o es demasiado?",
    "estaBien": "Está bien",
    "esDemasiado": "Es demasiado",
    "pistaMucho": "Piensa: ¿cuánto cuesta {nombre} normalmente? ¿Mucho más o mucho menos?",
    "explicacionMuchoBien": "Normalmente, {nombre} cuesta unos {ref}. {mostrado} es un precio normal.",
    "explicacionMuchoMal": "Normalmente, {nombre} cuesta unos {ref}. {mostrado} es demasiado dinero.",
    "resumenMucho": "Has pensado bien {n} de {t} precios.",
    "enunciadoFiar": "{contexto} venden {nombre} por {precio}. ¿Te parece de fiar o es sospechoso?",
    "contextoFiar1": "En una tienda",
    "contextoFiar2": "En un mercadillo",
    "contextoFiar3": "Por internet",
    "pareceFiar": "Parece de fiar",
    "sospechoso": "Es sospechoso",
    "pistaFiar": "Piensa: ¿cuánto cuesta {nombre} normalmente? Si el precio es muchísimo más bajo, hay truco.",
    "explicacionFiarBien": "{nombre} cuesta normalmente unos {ref}. Por {mostrado} es un precio normal: parece de fiar.",
    "explicacionFiarMal": "{nombre} cuesta normalmente unos {ref}. Por {mostrado} es demasiado barato: es sospechoso, puede ser una estafa.",
    "resumenFiar": "Has detectado bien {n} de {t} gangas.",
  "contexto": "Estás en una tienda con dinero en la mano. Vas a decidir si algo te llega, a pagar y a comprobar el cambio.",
  "pista": "🤔 Cuenta el dinero despacio. ¿Te llega o no te llega?",
  "explicacion": "✅ Así se usa el dinero de verdad. La próxima vez que pagues, hazlo con calma y comprueba el cambio.",
  "transferencia": "Esto te servirá para hacer compras reales: saber si te llega, pagar justo y comprobar que el cambio está bien.",
  }, 'es');
})();
