/* ============================================================
   Routime â€” Textos de lista-tareas (ES)
   Archivo especÃ­fico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html segÃºn App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "ðŸ—’ï¸ Lista de Tareas",
    "instruccion": "Toca las tareas en el orden correcto, de primero a Ãºltimo.",
    "instruccionNivel": " Primero elige el nivel.",
    "elegirNivel": "Elige el nivel",
    "etiquetaOrden": "Tu orden",
    "etiquetaTareas": "Tareas",
    "ariaTarea": "Tarea",
    "veces": "veces",
    "btnJugar": "Â¡Jugar!",
    "resumenFinal": "Has ganado {n} estrellas. Ahora tienes {total} estrellas.",
    "btnOtroNivel": "Elegir otro nivel",
    "btnMenu": "Volver al inicio",
    "contexto": "Tienes varias tareas que hacer a lo largo del dÃ­a. Tienes que ordenarlas para hacerlas en un buen orden.",
    "pista": "ðŸ¤” Piensa: Â¿quÃ© es lo primero que tienes que hacer hoy?",
    "explicacion": "âœ… AsÃ­ se organiza un dÃ­a. Empezar por lo importante hace que todo vaya mÃ¡s fÃ¡cil.",
    "transferencia": "Esto te servirÃ¡ para organizar tu dÃ­a real: en casa, en el cole o cuando hay muchas cosas a la vez.",
    "nivelListasTitulo": "Nivel 3",
    "nivelListasDescripcion": "Crea tu lista",
    "nivelListasEstrellas": 1,
    "nivelListasBoton": "Empezar",
    "crearTitulo": "ðŸ“ Crea tu lista",
    "crearInstruccion": "Practica creando una lista: aÃ±ade cosas, cÃ¡mbialas de orden, mÃ¡rcalas como hechas y bÃ³rralas.",
    "transferenciaCrear": "Esta lista es de prÃ¡ctica. Se queda en este dispositivo y te ayuda a entrenar cÃ³mo se hace una lista de verdad.",
    "consejoListaTitulo": "ðŸ’¡ CÃ³mo hacer una buena lista",
    "consejoListaPaso1": "Piensa quÃ© tienes que hacer.",
    "consejoListaPaso2": "Apunta cada cosa en la lista.",
    "consejoListaPaso3": "Ponlas en el orden en que las vas a hacer.",
    "consejoListaPaso4": "MÃ¡rcalas como hechas cuando termines.",
    "btnMisListas": "ðŸ“‹ Mis listas",
    "ariaMisListas": "Volver a tus listas para crear otra, abrirla o borrarla",
    "labelNombreLista": "Nombre de la lista",
    "ariaNombreLista": "Nombre de la lista",
    "btnEmpezarCrear": "Empezar",
    "placeholderInputItem": "Escribe una cosa...",
    "ariaInputItem": "Escribe un elemento de tu lista",
    "btnAnadirItem": "âž• AÃ±adir",
    "btnHechoItem": "âœ” Hecho",
    "btnPendienteItem": "Marcar como hecho",
    "ariaBtnAnadirItem": "AÃ±adir a la lista",
    "ariaSubirItem": "Subir el elemento seleccionado",
    "ariaBajarItem": "Bajar el elemento seleccionado",
    "ariaSeleccionarItem": "Elemento {n}: {texto}. Toca para seleccionarlo.",
    "ariaItemHecho": "Elemento hecho: {texto}",
    "ariaItemPendiente": "Elemento pendiente: {texto}. Toca para marcar como hecho.",
    "ariaQuitarItem": "Quitar {texto}",
    "btnGuardarLista": "ðŸ’¾ Guardar lista",
    "btnVaciarLista": "ðŸ—‘ï¸ Vaciar",
    "ariaVaciarLista": "Vaciar la lista actual",
    "listaGuardadaFeedback": "Â¡Lista guardada! Ganas 1 estrella.",
    "listaBorradaFeedback": "Lista borrada.",
    "listaActualVacia": "Tu lista estÃ¡ vacÃ­a todavÃ­a. Escribe arriba y pulsa AÃ±adir.",
    "progresoCrear": "{hechos} de {total} hechos",
    "progresoCrearCompleta": "Â¡Lista terminada! Has marcado todos los elementos.",
    "seleccionaParaMover": "Toca un elemento para seleccionarlo y luego usa las flechas para cambiarlo de sitio.",
    "elementoAnadidoFeedback": "AÃ±adido: {texto}",
    "elementoBorradoFeedback": "Borrado: {texto}",
    "elementoMovidoFeedback": "Movido al puesto {pos}.",
    "elementoHechoFeedback": "Hecho: {texto}",
    "elementoPendienteFeedback": "Deshecho: {texto}",
    "selectorVacio": "Toca un elemento para seleccionarlo.",
    "nombreRequerido": "Pon un nombre a la lista para empezar.",
    "promptNombreListaDefault": "Mi lista",
    "tusListas": "Tus listas guardadas",
    "elementosCount": "{n} elementos",
    "ariaVerLista": "Ver la lista {nombre}",
    "ariaEscucharLista": "Escuchar la lista {nombre}",
    "ariaAbrirLista": "Abrir la lista {nombre} para seguir editÃ¡ndola",
    "ariaBorrarLista": "Borrar la lista {nombre}",
  }, 'es');
})();
