/* ============================================================
   Routime — Textos de lista-tareas (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "🗒️ Lista de Tareas",
    "instruccion": "Toca las tareas en el orden correcto, de primero a último.",
    "instruccionNivel": " Primero elige el nivel.",
    "elegirNivel": "Elige el nivel",
    "etiquetaOrden": "Tu orden",
    "etiquetaTareas": "Tareas",
    "ariaTarea": "Tarea",
    "veces": "veces",
    "resumenFinal": "Has ganado {n} estrellas. Ahora tienes {total} estrellas.",
    "btnOtroNivel": "Elegir otro nivel",
    "contexto": "Tienes varias tareas que hacer a lo largo del día. Tienes que ordenarlas para hacerlas en un buen orden.",
    "pista": "🤔 Piensa: ¿qué es lo primero que tienes que hacer hoy?",
    "explicacion": "✅ Así se organiza un día. Empezar por lo importante hace que todo vaya más fácil.",
    "transferencia": "Esto te servirá para organizar tu día real: en casa, en el cole o cuando hay muchas cosas a la vez.",
    "nivelListasTitulo": "Nivel 3",
    "nivelListasDescripcion": "Crea tu lista",
    "nivelListasEstrellas": 1,
    "nivelListasBoton": "Empezar",
    "crearTitulo": "📝 Crea tu lista",
    "crearInstruccion": "Practica creando una lista: añade cosas, cámbialas de orden, márcalas como hechas y bórralas.",
    "transferenciaCrear": "Esta lista es de práctica. Se queda en este dispositivo y te ayuda a entrenar cómo se hace una lista de verdad.",
    "consejoListaTitulo": "💡 Cómo hacer una buena lista",
    "consejoListaPaso1": "Piensa qué tienes que hacer.",
    "consejoListaPaso2": "Apunta cada cosa en la lista.",
    "consejoListaPaso3": "Ponlas en el orden en que las vas a hacer.",
    "consejoListaPaso4": "Márcalas como hechas cuando termines.",
    "btnMisListas": "📋 Mis listas",
    "ariaMisListas": "Volver a tus listas para crear otra, abrirla o borrarla",
    "labelNombreLista": "Nombre de la lista",
    "ariaNombreLista": "Nombre de la lista",
    "btnEmpezarCrear": "Empezar",
    "placeholderInputItem": "Escribe una cosa...",
    "ariaInputItem": "Escribe un elemento de tu lista",
    "btnAnadirItem": "➕ Añadir",
    "btnHechoItem": "✔ Hecho",
    "btnPendienteItem": "Marcar como hecho",
    "ariaBtnAnadirItem": "Añadir a la lista",
    "ariaSubirItem": "Subir el elemento seleccionado",
    "ariaBajarItem": "Bajar el elemento seleccionado",
    "ariaSeleccionarItem": "Elemento {n}: {texto}. Toca para seleccionarlo.",
    "ariaItemHecho": "Elemento hecho: {texto}",
    "ariaItemPendiente": "Elemento pendiente: {texto}. Toca para marcar como hecho.",
    "ariaQuitarItem": "Quitar {texto}",
    "btnGuardarLista": "💾 Guardar lista",
    "btnVaciarLista": "🗑️ Vaciar",
    "ariaVaciarLista": "Vaciar la lista actual",
    "listaGuardadaFeedback": "¡Lista guardada! Ganas 1 estrella.",
    "listaBorradaFeedback": "Lista borrada.",
    "listaActualVacia": "Tu lista está vacía todavía. Escribe arriba y pulsa Añadir.",
    "progresoCrear": "{hechos} de {total} hechos",
    "progresoCrearCompleta": "¡Lista terminada! Has marcado todos los elementos.",
    "seleccionaParaMover": "Toca un elemento para seleccionarlo y luego usa las flechas para cambiarlo de sitio.",
    "elementoAnadidoFeedback": "Añadido: {texto}",
    "elementoBorradoFeedback": "Borrado: {texto}",
    "elementoMovidoFeedback": "Movido al puesto {pos}.",
    "elementoHechoFeedback": "Hecho: {texto}",
    "elementoPendienteFeedback": "Deshecho: {texto}",
    "selectorVacio": "Toca un elemento para seleccionarlo.",
    "nombreRequerido": "Pon un nombre a la lista para empezar.",
    "promptNombreListaDefault": "Mi lista",
    "tusListas": "Tus listas guardadas",
    "elementosCount": "{n} elementos",
    "ariaVerLista": "Ver la lista {nombre}",
    "ariaEscucharLista": "Escuchar la lista {nombre}",
    "ariaAbrirLista": "Abrir la lista {nombre} para seguir editándola",
    "ariaBorrarLista": "Borrar la lista {nombre}",
  }, 'es');
})();
