/* ============================================================
   Routime — Textos de lista-tareas (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "🗒️ Task List",
    "instruccion": "Touch the tasks in the right order, from first to last.",
    "instruccionNivel": " First, choose the level.",
    "elegirNivel": "Choose the level",
    "etiquetaOrden": "Your order",
    "etiquetaTareas": "Tasks",
    "ariaTarea": "Task",
    "veces": "times",
    "resumenFinal": "You won {n} stars. You now have {total} stars.",
    "btnOtroNivel": "Choose another level",
    "contexto": "You have several tasks to do during the day. Put them in a good order.",
    "pista": "🤔 Think: what do you have to do first today?",
    "explicacion": "✅ That is how to plan a day. Starting with the important things makes everything easier.",
    "transferencia": "This will help you organise your real day: at home, at school or when there is a lot to do.",
    "nivelListasTitulo": "Level 3",
    "nivelListasDescripcion": "Create your list",
    "nivelListasEstrellas": 1,
    "nivelListasBoton": "Start",
    "crearTitulo": "📝 Create your list",
    "crearInstruccion": "Practise making a list: add things, change the order, mark them as done and delete them.",
    "transferenciaCrear": "This list is for practice. It stays on this device and helps you train how to make a real list.",
    "consejoListaTitulo": "💡 How to make a good list",
    "consejoListaPaso1": "Think about what you have to do.",
    "consejoListaPaso2": "Write down each thing on the list.",
    "consejoListaPaso3": "Put them in the order you will do them.",
    "consejoListaPaso4": "Mark them as done when you finish them.",
    "btnMisListas": "📋 My lists",
    "ariaMisListas": "Go back to your lists to create another one, open it or delete it",
    "labelNombreLista": "Name of the list",
    "ariaNombreLista": "Name of the list",
    "btnEmpezarCrear": "Start",
    "placeholderInputItem": "Write something...",
    "ariaInputItem": "Write an item for your list",
    "btnAnadirItem": "➕ Add",
    "btnHechoItem": "✔ Done",
    "btnPendienteItem": "Mark as done",
    "ariaBtnAnadirItem": "Add to the list",
    "ariaSubirItem": "Move the selected item up",
    "ariaBajarItem": "Move the selected item down",
    "ariaSeleccionarItem": "Item {n}: {texto}. Tap to select it.",
    "ariaItemHecho": "Item done: {texto}",
    "ariaItemPendiente": "Item pending: {texto}. Tap to mark as done.",
    "ariaQuitarItem": "Remove {texto}",
    "btnGuardarLista": "💾 Save list",
    "btnVaciarLista": "🗑️ Clear",
    "ariaVaciarLista": "Clear the current list",
    "listaGuardadaFeedback": "List saved! You earn 1 star.",
    "listaBorradaFeedback": "List deleted.",
    "listaActualVacia": "Your list is empty for now. Type above and tap Add.",
    "progresoCrear": "{hechos} of {total} done",
    "progresoCrearCompleta": "List finished! You marked all the items.",
    "seleccionaParaMover": "Tap an item to select it, then use the arrows to move it.",
    "elementoAnadidoFeedback": "Added: {texto}",
    "elementoBorradoFeedback": "Removed: {texto}",
    "elementoMovidoFeedback": "Moved to position {pos}.",
    "elementoHechoFeedback": "Done: {texto}",
    "elementoPendienteFeedback": "Undone: {texto}",
    "selectorVacio": "Tap an item to select it.",
    "nombreRequerido": "Give the list a name to start.",
    "promptNombreListaDefault": "My list",
    "tusListas": "Your saved lists",
    "elementosCount": "{n} items",
    "ariaVerLista": "View the {nombre} list",
    "ariaEscucharLista": "Listen to the {nombre} list",
    "ariaAbrirLista": "Open the {nombre} list to keep editing it",
    "ariaBorrarLista": "Delete the {nombre} list",
  }, 'en');
})();
