/* ============================================================
   Routime — Textos de rutinas (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "📋 Mis Rutinas",
    "tabPredefinidas": "Rutinas predefinidas",
    "tabPropias": "Mis listas",
    "seccionManana": "🌅 Por la mañana",
    "seccionComida": "🍽️ Comidas",
    "seccionLimpieza": "🧹 Tareas de la casa",
    "seccionPersonal": "🪥 Cuidado personal",
    "seccionMascotas": "🐶 Mascotas",
    "seccionTarde": "☀️ Por la tarde",
    "seccionSalida": "🚪 Salir de casa",
    "seccionNoche": "🌙 Por la noche",
    "subseccionPasos": "Pasos",
    "subseccionOrdenar": "Ordenar",
    "btnEmpezar": "Empezar",
    "btnRepetir": "Hacer otra vez",
    "btnPracticarLista": "Practicar",
    "btnHecho": "Ya lo he hecho",
    "ariaPasoHecho": "Paso hecho",
    "completadaHoy": "✔ Completada hoy",
    "rutinaCompletadaTitulo": "¡Rutina completada!",
    "resumenFinal": "Has terminado la rutina \"{nombre}\". Ganas 1 estrella.",
    "btnOtraRutina": "Ver mis rutinas",
    "btnOrdenar": "🧩 Ordena la rutina",
    "instruccionOrdenar": "Toca el paso que quieres mover. Luego usa las flechas.",
    "etiquetaTuOrden": "Tu orden",
    "etiquetaPasosDisponibles": "Pasos",
    "ordenTitulo": "🧩 Ordena: {nombre}",
    "btnComprobar": "Comprobar",
    "btnPista": "💡 Pista",
    "btnResolver": "Ver solución",
    "ariaSubir": "Subir el paso seleccionado",
    "ariaBajar": "Bajar el paso seleccionado",
    "ariaSeleccionarPaso": "Paso {n}: {texto}. Toca para seleccionarlo.",
    "pistaOrdenar": "Fíjate en el hueco {posicion}: ahí va «{primero}». Pulsa sobre el hueco y elige ese paso.",
    "resolverOrdenar": "Así queda la rutina en orden. Esta vez no se gana estrella, pero puedes volver a intentarlo en otra rutina.",
    "ordenCorrecto": "¡Muy bien! La rutina está en orden. Ganas 1 estrella.",
    "ordenIncorrecto": "Casi. Vuelve a intentarlo. Mira el primer paso.",
    "ordenIncompleto": "Coloca todos los pasos antes de comprobar.",
    "ariaSlotLleno": "Puesto {n}: {texto}. Toca para quitarlo de aquí.",
    "ariaSlotVacio": "Puesto {n} vacío. Toca un paso de la derecha para colocarlo aquí.",
    "ariaPasoDisponible": "Paso disponible: {texto}. Tócalo para colocarlo en el primer puesto libre.",
  "contexto": "Estás siguiendo una rutina de cada día paso a paso. Marcar cada paso te ayuda a no saltarte nada.",
  "pista": "🤔 Mira el nombre de la rutina. ¿Por dónde se empieza siempre?",
  "explicacion": "✅ Si lo haces todos los días, pronto lo harás solo/a sin necesitar la lista.",
  "transferencia": "Esto te servirá para hacer las tareas de casa y de cuidado por ti mismo/a: ya no dependerás de que te lo recuerden.",
    "seccionListasLibres": "📝 Crea tus listas",
    "listasLibresDescripcion": "Practica hacer tus propias listas.",
    "tarjetaListasLibresNombre": "Crea una lista",
    "tarjetaListasLibresDescripcion": "Escribe lo que quieras recordar.",
    "listaLibreTitulo": "📝 Crea tu lista",
    "listaLibreInstruccion": "Escribe las cosas de tu lista. Tú decides el orden.",
    "listaLibreTransferencia": "Te sirve para organizar tareas, compras o lo que quieras recordar.",
    "placeholderInputItem": "Escribe una cosa...",
    "ariaInputItem": "Escribe un elemento de tu lista",
    "btnAnadirItem": "➕ Añadir",
    "ariaBtnAnadirItem": "Añadir a la lista",
    "listaActualVacia": "Tu lista está vacía todavía.",
    "ariaQuitarItem": "Quitar {texto}",
    "ariaSubirItem": "Subir {texto}",
    "ariaBajarItem": "Bajar {texto}",
    "btnGuardarLista": "💾 Guardar lista",
    "btnGuardarCambios": "💾 Guardar cambios",
    "btnVaciarLista": "🗑️ Vaciar",
    "ariaVaciarLista": "Vaciar la lista actual",
    "promptNombreLista": "¿Cómo quieres llamar a tu lista?",
    "ariaNombreLista": "Nombre de la lista",
    "promptNombreListaDefault": "Mi lista",
    "btnConfirmarGuardarLista": "✅ Guardar",
    "listaGuardadaFeedback": "¡Lista guardada! Ganas 1 estrella.",
    "listaActualizadaFeedback": "¡Lista actualizada!",
    "listaBorradaFeedback": "Lista borrada.",
    "tusListas": "Tus listas guardadas",
    "elementosCount": "{n} elementos",
    "ariaEscucharLista": "Escuchar {nombre}",
    "ariaEditarLista": "Editar {nombre}",
    "ariaBorrarLista": "Borrar {nombre}",
    "ariaVerLista": "Ver los elementos de {nombre}",
    "editandoListaAviso": "✏️ Editando: {nombre}",
    "btnCancelarEdicion": "Cancelar edición",
  }, 'es');
})();
