/* ============================================================
   Routime — Textos de rutinas (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "📋 My Routines",
    "seccionManana": "🌅 In the morning",
    "seccionComida": "🍽️ Meals",
    "seccionLimpieza": "🧹 Household tasks",
    "seccionPersonal": "🪥 Personal care",
    "seccionMascotas": "🐶 Pets",
    "seccionTarde": "☀️ In the afternoon",
    "seccionSalida": "🚪 Leaving home",
    "seccionNoche": "🌙 At night",
    "subseccionPasos": "Steps",
    "subseccionOrdenar": "Order",
    "btnEmpezar": "Start",
    "btnRepetir": "Do again",
    "btnHecho": "I've done it",
    "ariaPasoHecho": "Step done",
    "completadaHoy": "✔ Done today",
    "rutinaCompletadaTitulo": "Routine complete!",
    "resumenFinal": "You finished the \"{nombre}\" routine. You earn 1 star.",
    "btnOtraRutina": "See my routines",
    "btnOrdenar": "🧩 Order the routine",
    "instruccionOrdenar": "Tap the step you want to move. Then use the arrows.",
    "etiquetaTuOrden": "Your order",
    "etiquetaPasosDisponibles": "Steps",
    "ordenTitulo": "🧩 Order: {nombre}",
    "btnComprobar": "Check",
    "btnPista": "💡 Hint",
    "btnResolver": "Show solution",
    "ariaSubir": "Move the selected step up",
    "ariaBajar": "Move the selected step down",
    "ariaSeleccionarPaso": "Step {n}: {texto}. Tap to select it.",
    "pistaOrdenar": "Look at slot {posicion}: «{primero}» goes there. Tap the slot and pick that step.",
    "resolverOrdenar": "This is the routine in order. You don't earn a star this time, but you can try another routine on your own.",
    "ordenCorrecto": "Well done! The routine is in order. You earn 1 star.",
    "ordenIncorrecto": "Almost. Try again. Look at the first step.",
    "ordenIncompleto": "Place all the steps before checking.",
    "ariaSlotLleno": "Slot {n}: {texto}. Tap to remove it from here.",
    "ariaSlotVacio": "Empty slot {n}. Tap a step on the right to place it here.",
    "ariaPasoDisponible": "Available step: {texto}. Tap it to place it in the first empty slot.",
  "contexto": "You are following an everyday routine step by step. Ticking each step helps you not skip anything.",
  "pista": "🤔 Look at the name of the routine. Where do you always start?",
  "explicacion": "✅ If you do it every day, you will soon do it on your own without needing the list.",
  "transferencia": "This will help you do chores and self-care on your own: you will not need to be reminded any more.",
    "seccionListasLibres": "📝 Create your lists",
    "listasLibresDescripcion": "Practise making your own lists.",
    "tarjetaListasLibresNombre": "Create a list",
    "tarjetaListasLibresDescripcion": "Write down what you want to remember.",
    "listaLibreTitulo": "📝 Create your list",
    "listaLibreInstruccion": "Write the things on your list. You choose the order.",
    "listaLibreTransferencia": "This helps you organise tasks, shopping, or anything you want to remember.",
    "placeholderInputItem": "Write something...",
    "ariaInputItem": "Write an item for your list",
    "btnAnadirItem": "➕ Add",
    "ariaBtnAnadirItem": "Add to the list",
    "listaActualVacia": "Your list is empty for now.",
    "ariaQuitarItem": "Remove {texto}",
    "ariaSubirItem": "Move {texto} up",
    "ariaBajarItem": "Move {texto} down",
    "btnGuardarLista": "💾 Save list",
    "btnGuardarCambios": "💾 Save changes",
    "btnVaciarLista": "🗑️ Clear",
    "ariaVaciarLista": "Clear the current list",
    "promptNombreLista": "What do you want to call your list?",
    "ariaNombreLista": "Name of the list",
    "promptNombreListaDefault": "My list",
    "btnConfirmarGuardarLista": "✅ Save",
    "listaGuardadaFeedback": "List saved! You earn 1 star.",
    "listaActualizadaFeedback": "List updated!",
    "listaBorradaFeedback": "List deleted.",
    "tusListas": "Your saved lists",
    "elementosCount": "{n} items",
    "ariaEscucharLista": "Listen to {nombre}",
    "ariaEditarLista": "Edit {nombre}",
    "ariaBorrarLista": "Delete {nombre}",
    "ariaVerLista": "View the items in {nombre}",
    "editandoListaAviso": "✏️ Editing: {nombre}",
    "btnCancelarEdicion": "Cancel editing",
  }, 'en');
})();
