/* ============================================================
   Routime — Textos de rutinas (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "📋 My Routines",
    "predefinedTab": "Preset routines",
    "ownTab": "My lists",
    "sectionMorning": "🌅 In the morning",
    "sectionLunch": "🍽️ Meals",
    "sectionCleaning": "🧹 Household tasks",
    "sectionPersonal": "🪥 Personal care",
    "sectionPets": "🐶 Pets",
    "sectionAfternoon": "☀️ In the afternoon",
    "sectionOuting": "🚪 Leaving home",
    "sectionNight": "🌙 At night",
    "subsectionSteps": "Steps",
    "subsectionOrder": "Order",
    "btnEmpezar": "Start",
    "btnRepetir": "Do again",
    "btnPracticarLista": "Practise",
    "btnDone": "I've done it",
    "ariaStepDone": "Step done",
    "completedToday": "✔ Done today",
    "routineCompletedTitle": "Routine complete!",
    "resumenFinal": "You finished the \"{name}\" routine. You earn 1 star.",
    "btnAnotherRoutine": "See my routines",
    "btnOrder": "🧩 Order the routine",
    "orderInstruction": "Tap the step you want to move. Then use the arrows.",
    "labelYourOrder": "Your order",
    "labelAvailableSteps": "Steps",
    "ordenTitulo": "🧩 Order: {name}",
    "btnCheck": "Check",
    "btnHint": "💡 Hint",
    "btnResolve": "Show solution",
    "ariaSubir": "Move the selected step up",
    "ariaBajar": "Move the selected step down",
    "ariaSeleccionarPaso": "Step {n}: {text}. Tap to select it.",
    "hintOrder": "Look at slot {posicion}: «{primero}» goes there. Tap the slot and pick that step.",
    "resolveOrder": "This is the routine in order. You don't earn a star this time, but you can try another routine on your own.",
    "ordenCorrecto": "Well done! The routine is in order. You earn 1 star.",
    "ordenIncorrecto": "Almost. Try again. Look at the first step.",
    "ordenIncompleto": "Place all the steps before checking.",
    "ariaSlotFilled": "Slot {n}: {text}. Tap to remove it from here.",
    "ariaSlotEmpty": "Empty slot {n}. Tap a step on the right to place it here.",
    "ariaStepAvailable": "Available step: {text}. Tap it to place it in the first empty slot.",
  "contexto": "You are following an everyday routine step by step. Ticking each step helps you not skip anything.",
  "pista": "🤔 Look at the name of the routine. Where do you always start?",
  "explicacion": "✅ If you do it every day, you will soon do it on your own without needing the list.",
  "transferencia": "This will help you do chores and self-care on your own: you will not need to be reminded any more.",
    "freeListsSection": "📝 Create your lists",
    "freeListsDescription": "Practise making your own lists.",
    "freeListCardName": "Create a list",
    "freeListCardDescription": "Write down what you want to remember.",
    "freeListTitle": "📝 Create your list",
    "freeListInstruction": "Write the things on your list. You choose the order.",
    "freeListTransfer": "This helps you organise tasks, shopping, or anything you want to remember.",
    "placeholderInputItem": "Write something...",
    "ariaInputItem": "Write an item for your list",
    "btnAddItem": "➕ Add",
    "ariaBtnAnadirItem": "Add to the list",
    "currentListEmpty": "Your list is empty for now.",
    "ariaRemoveItem": "Remove {text}",
    "ariaMoveUpItem": "Move {text} up",
    "ariaMoveDownItem": "Move {text} down",
    "btnSaveList": "💾 Save list",
    "btnGuardarCambios": "💾 Save changes",
    "btnClearList": "🗑️ Clear",
    "ariaVaciarLista": "Clear the current list",
    "promptListName": "What do you want to call your list?",
    "ariaNombreLista": "Name of the list",
    "promptListNameDefault": "My list",
    "btnConfirmSaveList": "✅ Save",
    "listSavedFeedback": "List saved! You earn 1 star.",
    "listUpdatedFeedback": "List updated!",
    "listDeletedFeedback": "List deleted.",
    "yourLists": "Your saved lists",
    "elementosCount": "{n} items",
    "ariaListenList": "Listen to {name}",
    "ariaEditList": "Edit {name}",
    "ariaDeleteList": "Delete {name}",
    "ariaViewList": "View the items in {name}",
    "editandoListaAviso": "✏️ Editing: {name}",
    "btnCancelEdit": "Cancel editing",
  }, 'en');
})();
