/* ============================================================
   Routime — Textos de rutinas (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "📋 Mis Rutinas",
    "predefinedTab": "Rutinas predefinidas",
    "ownTab": "Mis listas",
    "sectionMorning": "🌅 Por la mañana",
    "sectionLunch": "🍽️ Comidas",
    "sectionCleaning": "🧹 Tareas de la casa",
    "sectionPersonal": "🪥 Cuidado personal",
    "sectionPets": "🐶 Mascotas",
    "sectionAfternoon": "☀️ Por la tarde",
    "sectionOuting": "🚪 Salir de casa",
    "sectionNight": "🌙 Por la noche",
    "subsectionSteps": "Pasos",
    "subsectionOrder": "Ordenar",
    "btnEmpezar": "Empezar",
    "btnRepetir": "Hacer otra vez",
    "btnPracticarLista": "Practicar",
    "btnDone": "Ya lo he done",
    "ariaStepDone": "Paso done",
    "completedToday": "✔ Completada hoy",
    "routineCompletedTitle": "¡Rutina completada!",
    "resumenFinal": "Has terminado la rutina \"{name}\". Ganas 1 estrella.",
    "btnAnotherRoutine": "Ver mis rutinas",
    "btnOrder": "🧩 Ordena la rutina",
    "orderInstruction": "Toca el paso que quieres mover. Luego usa las flechas.",
    "labelYourOrder": "Tu orden",
    "labelAvailableSteps": "Pasos",
    "ordenTitulo": "🧩 Ordena: {name}",
    "btnCheck": "Comprobar",
    "btnHint": "💡 Pista",
    "btnResolve": "Ver solución",
    "ariaSubir": "Subir el paso selected",
    "ariaBajar": "Bajar el paso selected",
    "ariaSeleccionarPaso": "Paso {n}: {text}. Toca para seleccionarlo.",
    "hintOrder": "Fíjate en el hueco {posicion}: ahí va «{primero}». Pulsa sobre el hueco y elige ese paso.",
    "resolveOrder": "Así queda la rutina en orden. Esta vez no se gana estrella, pero puedes volver a intentarlo en otra rutina.",
    "ordenCorrecto": "¡Muy bien! La rutina está en orden. Ganas 1 estrella.",
    "ordenIncorrecto": "Casi. Vuelve a intentarlo. Mira el primer paso.",
    "ordenIncompleto": "Coloca todos los steps antes de comprobar.",
    "ariaSlotFilled": "Puesto {n}: {text}. Toca para quitarlo de aquí.",
    "ariaSlotEmpty": "Puesto {n} vacío. Toca un paso de la derecha para colocarlo aquí.",
    "ariaStepAvailable": "Paso available: {text}. Tócalo para colocarlo en el primer puesto libre.",
  "contexto": "Estás siguiendo una rutina de cada día paso a paso. Marcar cada paso te ayuda a no saltarte nada.",
  "pista": "🤔 Mira el name de la rutina. ¿Por dónde se empieza siempre?",
  "explicacion": "✅ Si lo haces todos los días, pronto lo harás solo/a sin necesitar la lista.",
  "transferencia": "Esto te servirá para hacer las tareas de casa y de cuidado por ti mismo/a: ya no dependerás de que te lo recuerden.",
    "freeListsSection": "📝 Crea tus listas",
    "freeListsDescription": "Practica hacer tus propias listas.",
    "freeListCardName": "Crea una lista",
    "freeListCardDescription": "Escribe lo que quieras recordar.",
    "freeListTitle": "📝 Crea tu lista",
    "freeListInstruction": "Escribe las cosas de tu lista. Tú decides el orden.",
    "freeListTransfer": "Te sirve para organizar tareas, compras o lo que quieras recordar.",
    "placeholderInputItem": "Escribe una cosa...",
    "ariaInputItem": "Escribe un elemento de tu lista",
    "btnAddItem": "➕ Añadir",
    "ariaBtnAnadirItem": "Añadir a la lista",
    "currentListEmpty": "Tu lista está vacía todavía.",
    "ariaRemoveItem": "Quitar {text}",
    "ariaMoveUpItem": "Subir {text}",
    "ariaMoveDownItem": "Bajar {text}",
    "btnSaveList": "💾 Guardar lista",
    "btnGuardarCambios": "💾 Guardar cambios",
    "btnClearList": "🗑️ Vaciar",
    "ariaVaciarLista": "Vaciar la lista current",
    "promptListName": "¿Cómo quieres llamar a tu lista?",
    "ariaNombreLista": "Nombre de la lista",
    "promptListNameDefault": "Mi lista",
    "btnConfirmSaveList": "✅ Guardar",
    "listSavedFeedback": "¡Lista guardada! Ganas 1 estrella.",
    "listUpdatedFeedback": "¡Lista actualizada!",
    "listDeletedFeedback": "Lista borrada.",
    "yourLists": "Tus listas guardadas",
    "elementosCount": "{n} elementos",
    "ariaListenList": "Escuchar {name}",
    "ariaEditList": "Editar {name}",
    "ariaDeleteList": "Borrar {name}",
    "ariaViewList": "Ver los elementos de {name}",
    "editandoListaAviso": "✏️ Editando: {name}",
    "btnCancelEdit": "Cancelar edición",
  }, 'es');
})();
