/* 48 non-graphic preventive simulations, grouped into six topics.
   Real-life (offline) counterpart to tools/social-safety (which covers
   digital/online risks). No clinical or anatomical vocabulary: the
   correct answer always reinforces body autonomy and points to a
   trusted person or health professional — this activity never gives
   direct medical instructions. */
var DATA = {
  es: {
    porRonda: 5,
    niveles: [
      {
        id: 'consentimiento', nombre: 'Mi cuerpo y el consentimiento', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🤗', situacion: 'Un familiar te pide un abrazo pero tú no quieres.', opciones: ['Digo que no quiero, y está bien decirlo', 'Abrazo aunque no quiera, para no ofender', 'Me escondo sin decir nada'], correcta: 0, pista: '🤔 ¿Tu cuerpo es tuyo? ¿Puedes decidir?', explicacion: '✅ Tu cuerpo es tuyo. Puedes decir que no a un abrazo, aunque sea alguien conocido.' },
          { picto: '🏥', situacion: 'Vas al médico y necesita revisarte el cuerpo.', opciones: ['Pregunto si puede venir conmigo una persona de confianza', 'Voy sola/o sin preguntar nada', 'Digo que no a cualquier revisión'], correcta: 0, pista: '🤔 ¿Puedes pedir que alguien de confianza te acompañe?', explicacion: '✅ Puedes pedir que te acompañe una persona de confianza en una revisión médica. Es tu derecho.' },
          { picto: '🚫', situacion: 'Alguien te toca de una forma que no te gusta.', opciones: ['Digo que pare y lo cuento a una persona de confianza', 'No digo nada para no molestar', 'Espero a que se le pase'], correcta: 0, pista: '🤔 ¿Puedes decir que pare?', explicacion: '✅ Puedes decir que pare, siempre. Y puedes contarlo a alguien de confianza.' },
          { picto: '🔒', situacion: 'Quieres cerrar la puerta cuando te cambias de ropa.', opciones: ['Cierro la puerta, mi intimidad importa', 'No cierro la puerta, da igual', 'Solo cierro si hay alguien mirando'], correcta: 0, pista: '🤔 ¿Tienes derecho a intimidad?', explicacion: '✅ Tienes derecho a intimidad. Puedes cerrar la puerta cuando lo necesites.' },
          { picto: '🙅', situacion: 'Una persona insiste en besarte y tú no quieres.', opciones: ['Digo que no quiero, las veces que haga falta', 'Le dejo para que no se enfade', 'Me quedo quieta/o sin decir nada'], correcta: 0, pista: '🤔 ¿Puedes repetir un no las veces que haga falta?', explicacion: '✅ Puedes decir que no las veces que haga falta. Un no se respeta siempre.' },
          { picto: '🧑‍⚕️', situacion: 'En una consulta médica te piden quitarte ropa para una revisión necesaria.', opciones: ['Pregunto para qué es y pido que esté alguien de confianza', 'Lo hago sin preguntar nada', 'Me niego a cualquier revisión'], correcta: 0, pista: '🤔 ¿Puedes preguntar y pedir compañía?', explicacion: '✅ Puedes preguntar para qué es una revisión y pedir que te acompañe alguien de confianza.' },
          { picto: '💬', situacion: 'Un amigo te dice que si de verdad confías en él, le dejarás ver tu cuerpo.', opciones: ['Le digo que la confianza no obliga a eso', 'Se lo permito para que no se enfade', 'Dudo pero acabo aceptando'], correcta: 0, pista: '🤔 ¿La confianza obliga a algo con tu cuerpo?', explicacion: '✅ La confianza no obliga a nada con tu cuerpo. Un amigo de verdad respeta un no.' },
          { picto: '🖐️', situacion: 'No sabes si puedes decir que no a algo que no te gusta con tu cuerpo.', opciones: ['Sí puedo decir que no, siempre, aunque ya haya empezado', 'Solo puedo decir que no al principio', 'Si ya dije que sí antes, no puedo cambiar de idea'], correcta: 0, pista: '🤔 ¿Puedes cambiar de idea en cualquier momento?', explicacion: '✅ Puedes decir que no en cualquier momento, aunque antes dijeras que sí.' },
          { picto: '🚗', situacion: 'Un familiar te pide un beso en la mejilla para despedirse y tú no quieres.', opciones: ['Digo que prefiero decir adiós de otra forma', 'Le doy el beso aunque no quiera', 'Me escondo sin decir nada'], correcta: 0, pista: '🤔 ¿Puedes elegir cómo despedirte?', explicacion: '✅ Puedes elegir cómo despedirte. Un abrazo, un choque de manos o un adiós con la mano también valen.' },
          { picto: '🛌', situacion: 'Alguien entra en tu habitación sin llamar mientras te estás cambiando.', opciones: ['Le pido que llame antes de entrar', 'No digo nada aunque me incomode', 'Dejo la puerta abierta a partir de ahora'], correcta: 0, pista: '🤔 ¿Puedes pedir que llamen antes de entrar?', explicacion: '✅ Puedes pedir privacidad. Pedir que llamen antes de entrar es tu derecho.' },
          { picto: '🏊', situacion: 'En la piscina, alguien te toca la espalda de broma y a ti no te hace gracia.', opciones: ['Le digo que no me gusta y que pare', 'Me río aunque no me guste', 'Le hago lo mismo a otra persona'], correcta: 0, pista: '🤔 ¿Puedes decir que algo no te gusta aunque sea "broma"?', explicacion: '✅ Puedes decir que algo no te gusta, aunque la otra persona diga que es broma.' },
          { picto: '🤔', situacion: 'No sabes si tienes que dar explicaciones cuando dices que no quieres que te toquen.', opciones: ['No tengo que dar explicaciones, un no basta', 'Tengo que explicar bien el motivo', 'Solo puedo decir que no si tengo una buena razón'], correcta: 0, pista: '🤔 ¿Un no necesita siempre una explicación larga?', explicacion: '✅ No hace falta dar explicaciones. Un no es suficiente por sí mismo.' }
        ]
      },
      {
        id: 'relaciones', nombre: 'Relaciones sanas', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🚷', situacion: 'Tu pareja no te deja ver a tus amigos/as.', opciones: ['Hablo con alguien de confianza, eso no es normal', 'Dejo de ver a mis amigos/as para tener paz', 'Le doy explicaciones cada vez que quiero salir'], correcta: 0, pista: '🤔 ¿Una relación sana te aleja de la gente que quieres?', explicacion: '✅ Una relación sana no te aísla de la gente que quieres. Eso es una señal de alarma.' },
          { picto: '📱', situacion: 'Tu pareja quiere leer todos tus mensajes y saber dónde estás siempre.', opciones: ['Pongo un límite: mi privacidad importa, y pido apoyo si insiste', 'Le doy acceso a todo para que confíe en mí', 'Le enseño solo algunos mensajes'], correcta: 0, pista: '🤔 ¿La confianza necesita controlar todo lo que haces?', explicacion: '✅ Controlar tus mensajes y tus movimientos no es amor, es control. Puedes pedir ayuda.' },
          { picto: '😢', situacion: 'Después de una discusión, tu pareja te dice que es tu culpa de todo lo que pasa.', opciones: ['Pienso que no siempre es culpa mía, y hablo con alguien de confianza', 'Le creo, seguro que tiene razón', 'Me disculpo aunque no sepa por qué'], correcta: 0, pista: '🤔 ¿En una pareja la culpa es siempre de una sola persona?', explicacion: '✅ En una relación sana, la responsabilidad se comparte. Nadie tiene siempre toda la culpa.' },
          { picto: '🎁', situacion: 'Tu pareja te hace regalos caros y luego te pide cosas que no quieres hacer.', opciones: ['Digo que no, un regalo no me obliga a nada', 'Hago lo que pide porque me hizo un regalo', 'Acepto para no parecer desagradecido/a'], correcta: 0, pista: '🤔 ¿Un regalo te obliga a algo?', explicacion: '✅ Un regalo no te obliga a nada. Puedes decir que no aunque te hayan hecho un regalo.' },
          { picto: '🚪', situacion: 'Quieres terminar una relación pero tienes miedo de decirlo.', opciones: ['Tengo derecho a terminar una relación cuando quiera, y puedo pedir apoyo', 'Sigo en la relación aunque no quiera', 'Espero a que la otra persona lo adivine'], correcta: 0, pista: '🤔 ¿Tienes derecho a decidir terminar una relación?', explicacion: '✅ Tienes derecho a terminar una relación cuando quieras. Una persona de confianza puede ayudarte a hacerlo con seguridad.' },
          { picto: '👏', situacion: 'Tu pareja te anima a hacer cosas que te gustan y respeta cuando dices que no.', opciones: ['Eso es una señal de una relación sana', 'Eso significa que no le importo', 'Debería preocuparme por eso'], correcta: 0, pista: '🤔 ¿El respeto y el apoyo son buenas señales?', explicacion: '✅ Respetar tus gustos y tus límites es una señal de una relación sana. ¡Bien reconocido!' },
          { picto: '😨', situacion: 'Tienes miedo de tu pareja porque a veces grita o rompe cosas cuando se enfada.', opciones: ['Lo cuento a una persona de confianza, eso no es seguro', 'No digo nada para no provocarle', 'Pienso que es normal si luego pide perdón'], correcta: 0, pista: '🤔 ¿Dar miedo es parte de una relación sana?', explicacion: '✅ Si tienes miedo de tu pareja, eso no es seguro. Cuéntaselo a una persona de confianza.' },
          { picto: '🤝', situacion: 'No sabes si lo que sientes en tu relación es normal o no.', opciones: ['Hablarlo con una persona de confianza me puede ayudar a verlo claro', 'Prefiero no hablarlo con nadie', 'Pienso que preguntar es exagerar'], correcta: 0, pista: '🤔 ¿Hablarlo con alguien puede ayudarte?', explicacion: '✅ Hablar con una persona de confianza o un profesional te puede ayudar a ver la relación con más claridad.' },
          { picto: '📵', situacion: 'Tu pareja se enfada si hablas con tus amigos y quiere que dejes de quedar con ellos.', opciones: ['Hablo con alguien de confianza, eso no es sano', 'Dejo de quedar con mis amigos', 'Quedo con ellos a escondidas'], correcta: 0, pista: '🤔 ¿Una pareja sana te pide que dejes a tus amigos?', explicacion: '✅ Una relación sana no te pide elegir entre tu pareja y tus amistades.' },
          { picto: '🙏', situacion: 'Tu pareja se disculpa de verdad después de un error y cambia su comportamiento.', opciones: ['Eso es una señal sana si el cambio es real', 'Nunca hay que aceptar una disculpa', 'Tengo que estar enfadado/a para siempre'], correcta: 0, pista: '🤔 ¿Puede una relación mejorar con el tiempo?', explicacion: '✅ Disculparse de verdad y cambiar el comportamiento es parte de una relación sana.' },
          { picto: '⏳', situacion: 'Sientes que vas más rápido de lo que te gustaría en una relación nueva y quieres ir más despacio.', opciones: ['Digo que quiero ir más despacio, y eso está bien', 'Sigo el ritmo del otro aunque no quiera', 'No digo nada por miedo a que se enfade'], correcta: 0, pista: '🤔 ¿Puedes marcar tu propio ritmo en una relación?', explicacion: '✅ Puedes marcar tu propio ritmo. Una pareja sana lo respeta.' },
          { picto: '🗣️', situacion: 'Tu pareja te escucha cuando le cuentas algo que te preocupa, sin quitarle importancia.', opciones: ['Eso es una señal de una relación sana', 'Eso significa que soy débil por contarlo', 'Debería guardarme siempre mis preocupaciones'], correcta: 0, pista: '🤔 ¿Ser escuchado/a es una buena señal?', explicacion: '✅ Sentirte escuchado/a y no juzgado/a es una señal de una relación sana.' }
        ]
      },
      {
        id: 'anticoncepcion', nombre: 'Anticoncepción', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '❓', situacion: 'Quieres saber qué métodos anticonceptivos existen.', opciones: ['Pregunto a un profesional de la salud (médico, matrona, centro de salud)', 'Busco solo en internet y lo que diga una amistad', 'No pregunto porque me da vergüenza'], correcta: 0, pista: '🤔 ¿Quién te puede explicar esto de forma segura?', explicacion: '✅ Un profesional de la salud te explica las opciones y cuál te conviene, sin ningún problema.' },
          { picto: '💊', situacion: 'Una amistad te da una pastilla y dice que es anticonceptiva.', opciones: ['No la tomo sin que me lo indique un profesional de la salud', 'La tomo porque mi amistad lo dice', 'La tomo sin preguntar nada'], correcta: 0, pista: '🤔 ¿Puedes tomar medicinas sin que te las indique un profesional?', explicacion: '✅ Nunca tomes una medicina que no te indique un profesional de la salud. Puede ser peligroso.' },
          { picto: '👩‍⚕️', situacion: 'No sabes a quién preguntar sobre anticoncepción.', opciones: ['Puedo ir a un centro de salud o hablar con mi médico de cabecera', 'Solo puedo preguntarlo a mis amistades', 'No hay nadie a quien preguntar'], correcta: 0, pista: '🤔 ¿Existen lugares donde te pueden ayudar con esto?', explicacion: '✅ Un centro de salud o tu médico de cabecera pueden ayudarte con toda confianza y sin juzgarte.' },
          { picto: '🤰', situacion: 'Te preocupa un posible embarazo y no sabes qué hacer.', opciones: ['Voy a un centro de salud o se lo cuento a una persona de confianza', 'No hago nada y espero a ver qué pasa', 'Se lo pregunto solo a amistades'], correcta: 0, pista: '🤔 ¿Quién puede ayudarte de forma segura y rápida?', explicacion: '✅ Un centro de salud te puede informar y ayudar cuanto antes. No tienes que resolverlo sola/o.' },
          { picto: '🙋', situacion: 'Te da vergüenza preguntar sobre anticoncepción en la consulta médica.', opciones: ['Aun con vergüenza, tengo derecho a preguntar y me pueden ayudar', 'No pregunto por la vergüenza', 'Espero a que se me pase la vergüenza para siempre'], correcta: 0, pista: '🤔 ¿La vergüenza debe impedir que pidas ayuda?', explicacion: '✅ Los profesionales de la salud están para ayudarte, sin juzgarte. Preguntar es un derecho.' },
          { picto: '🔐', situacion: 'Quieres que lo que hables con un profesional de la salud sea privado.', opciones: ['Puedo pedir que sea confidencial, es mi derecho', 'Todo lo que digo se cuenta a mi familia sin que yo lo sepa', 'No puedo pedir privacidad en la consulta'], correcta: 0, pista: '🤔 ¿Tienes derecho a la privacidad en una consulta?', explicacion: '✅ Tienes derecho a la confidencialidad con un profesional de la salud. Puedes preguntarlo tranquilamente.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Tu pareja no quiere usar ningún método de protección y tú sí quieres.', opciones: ['Mi decisión sobre mi cuerpo importa, y puedo pedir apoyo si insiste', 'Hago lo que mi pareja prefiera', 'No digo nada para evitar una discusión'], correcta: 0, pista: '🤔 ¿Tu opinión sobre tu propio cuerpo cuenta?', explicacion: '✅ Tu decisión sobre tu cuerpo y tu salud importa siempre. Puedes pedir ayuda si no se respeta.' },
          { picto: '📅', situacion: 'No entiendes bien la información que te ha dado un profesional de la salud.', opciones: ['Puedo pedir que me lo expliquen otra vez, más despacio', 'Finjo que lo he entendido', 'No vuelvo a preguntar nunca más'], correcta: 0, pista: '🤔 ¿Puedes pedir que te lo expliquen de otra forma?', explicacion: '✅ Puedes pedir que te lo expliquen de nuevo, más despacio o con dibujos. Es tu derecho entenderlo.' },
          { picto: '📚', situacion: 'Quieres informarte bien antes de tomar una decisión sobre anticoncepción.', opciones: ['Pido información a un profesional de la salud, con calma', 'Decido rápido sin informarme', 'Sigo lo que dice cualquier vídeo de internet'], correcta: 0, pista: '🤔 ¿Dónde puedes conseguir información fiable?', explicacion: '✅ Un profesional de la salud te da información fiable y sin prisas.' },
          { picto: '🧑‍⚕️', situacion: 'No entiendes bien cómo funciona un método anticonceptivo que te han explicado.', opciones: ['Pido que me lo expliquen de otra manera', 'Finjo que lo he entendido', 'Decido no usar ningún método por si acaso'], correcta: 0, pista: '🤔 ¿Puedes pedir que te lo expliquen de nuevo?', explicacion: '✅ Puedes pedir que te lo expliquen cuantas veces necesites. Entenderlo bien es importante.' },
          { picto: '👪', situacion: 'Quieres hablar de anticoncepción con tu familia, pero no sabes cómo empezar.', opciones: ['Puedo pedir ayuda a un profesional para hablarlo si me cuesta', 'No lo hablo nunca con nadie', 'Espero a que ellos lo saquen primero'], correcta: 0, pista: '🤔 ¿Un profesional puede ayudarte a tener esta conversación?', explicacion: '✅ Un profesional de la salud puede ayudarte a preparar esa conversación si te resulta difícil.' },
          { picto: '🔁', situacion: 'Has cambiado de opinión sobre el método anticonceptivo que usabas.', opciones: ['Puedo consultarlo de nuevo con un profesional de la salud', 'Tengo que seguir igual aunque no quiera', 'Lo decido yo solo/a sin consultar a nadie'], correcta: 0, pista: '🤔 ¿Puedes cambiar de decisión con ayuda profesional?', explicacion: '✅ Puedes revisar tu decisión con un profesional de la salud siempre que lo necesites.' }
        ]
      },
      {
        id: 'higiene', nombre: 'Higiene y salud sexual', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🩹', situacion: 'Notas algo raro en tu cuerpo y no sabes si es normal.', opciones: ['Voy al médico o al centro de salud a preguntar', 'Espero a ver si se pasa solo', 'Se lo pregunto solo a una amistad'], correcta: 0, pista: '🤔 ¿Quién puede revisarlo con seguridad?', explicacion: '✅ Un profesional de la salud puede revisarlo y explicarte qué pasa, sin ningún problema.' },
          { picto: '🧼', situacion: 'Quieres saber qué hábitos de higiene son importantes para tu cuerpo.', opciones: ['Pregunto a un profesional de la salud o a una persona de confianza', 'No pregunto porque debería saberlo ya', 'Copio lo que hacen mis amistades sin preguntar'], correcta: 0, pista: '🤔 ¿Está bien pedir que te lo expliquen?', explicacion: '✅ Puedes preguntar sobre higiene sin vergüenza. Un profesional o una persona de confianza te puede orientar.' },
          { picto: '🛡️', situacion: 'Alguien te dice que usar protección no es necesario si confías en la otra persona.', opciones: ['La protección es importante, confiar no la sustituye', 'Le creo y no uso protección', 'Solo la uso si me lo piden'], correcta: 0, pista: '🤔 ¿La confianza sustituye a la protección?', explicacion: '✅ La confianza no sustituye a la protección. Un profesional de la salud te puede explicar por qué es importante.' },
          { picto: '🚑', situacion: 'Te preocupa haber estado en una situación de riesgo para tu salud.', opciones: ['Voy a un centro de salud cuanto antes a preguntar', 'Espero a ver si tengo síntomas', 'No se lo cuento a nadie por vergüenza'], correcta: 0, pista: '🤔 ¿Es mejor preguntar pronto?', explicacion: '✅ Ante cualquier duda, un centro de salud te puede atender pronto y con confidencialidad.' },
          { picto: '🗣️', situacion: 'Te da vergüenza hablar de estos temas con un profesional de la salud.', opciones: ['Los profesionales están acostumbrados y no me van a juzgar', 'Prefiero no ir nunca a preguntar esto', 'Solo hablo de esto con amistades'], correcta: 0, pista: '🤔 ¿Un profesional de la salud está para ayudarte sin juzgar?', explicacion: '✅ Un profesional de la salud ha hablado de esto muchas veces. Está para ayudarte, no para juzgarte.' },
          { picto: '🧴', situacion: 'No sabes si necesitas usar protección en una relación.', opciones: ['Puedo preguntarlo a un profesional de la salud para estar segura/o', 'Doy por hecho que no hace falta', 'Le pregunto solo a mi pareja'], correcta: 0, pista: '🤔 ¿A quién puedes preguntar para estar segura/o?', explicacion: '✅ Un profesional de la salud te puede explicar cuándo y por qué usar protección.' },
          { picto: '📋', situacion: 'Un profesional de la salud te propone hacerte una revisión rutinaria de salud sexual.', opciones: ['Puedo aceptar y preguntar todo lo que necesite saber', 'Digo que no porque me da miedo', 'Lo dejo para otro momento sin decidir'], correcta: 0, pista: '🤔 ¿Una revisión rutinaria puede ayudarte a cuidarte?', explicacion: '✅ Una revisión rutinaria te ayuda a cuidar tu salud. Puedes preguntar todo lo que necesites.' },
          { picto: '💗', situacion: 'No sabes si lo que sientes sobre tu cuerpo o tu salud es normal preguntarlo.', opciones: ['Siempre es normal preguntar sobre mi cuerpo y mi salud', 'Solo puedo preguntar si es algo grave', 'Debería saberlo todo sin preguntar'], correcta: 0, pista: '🤔 ¿Siempre está bien preguntar sobre tu salud?', explicacion: '✅ Siempre está bien preguntar sobre tu cuerpo y tu salud. No hay preguntas tontas.' },
          { picto: '🧴', situacion: 'No sabes con qué frecuencia es recomendable cambiar ciertos hábitos de higiene íntima.', opciones: ['Se lo pregunto a un profesional de la salud', 'Lo dejo pasar sin preguntar', 'Copio lo que hacen mis amigos sin más'], correcta: 0, pista: '🤔 ¿Quién puede darte una respuesta fiable?', explicacion: '✅ Un profesional de la salud puede darte pautas claras y sin vergüenza.' },
          { picto: '🩺', situacion: 'Notas molestias que no sabes identificar y te preocupa que sean importantes.', opciones: ['Pido cita con un profesional de la salud para que lo revise', 'Espero mucho tiempo a ver si se pasa solo', 'Se lo pregunto solo a desconocidos de internet'], correcta: 0, pista: '🤔 ¿Es mejor consultarlo pronto?', explicacion: '✅ Ante cualquier molestia, un profesional de la salud puede revisarlo pronto y con confidencialidad.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Un amigo te da consejos de salud sexual que no sabes si son ciertos.', opciones: ['Lo compruebo con un profesional de la salud antes de seguirlo', 'Sigo el consejo de mi amigo sin comprobarlo', 'Ignoro el tema por completo'], correcta: 0, pista: '🤔 ¿Los consejos de amigos siempre son fiables?', explicacion: '✅ Los consejos de amigos no siempre son correctos. Un profesional de la salud te da información fiable.' },
          { picto: '📅', situacion: 'No sabes cada cuánto tiempo conviene hacerse una revisión de salud sexual.', opciones: ['Se lo pregunto a un profesional de la salud', 'Decido no hacerme ninguna revisión nunca', 'Sigo lo que hacen mis amigos sin preguntar'], correcta: 0, pista: '🤔 ¿Quién te puede orientar sobre la frecuencia adecuada?', explicacion: '✅ Un profesional de la salud te puede indicar cada cuánto conviene revisarte.' }
        ]
      },
      {
        id: 'presion', nombre: 'Presión y decisión', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '💞', situacion: 'Tu pareja te dice que si le quieres de verdad, tienes que demostrarlo manteniendo relaciones.', opciones: ['El amor no obliga a eso; puedo decir que no y pedir apoyo', 'Lo hago para que vea que le quiero', 'Lo hago aunque no quiera, para no perderle'], correcta: 0, pista: '🤔 ¿El amor verdadero obliga a algo con tu cuerpo?', explicacion: '✅ Querer a alguien no te obliga a hacer nada con tu cuerpo. Una persona de confianza puede ayudarte a verlo claro.' },
          { picto: '😟', situacion: 'Te sientes culpable por querer decir que no a algo con tu cuerpo.', opciones: ['No tengo que sentir culpa por proteger mi cuerpo, y puedo hablarlo con alguien de confianza', 'Sigo aunque me sienta mal, para no decepcionar', 'Finjo que no me importa'], correcta: 0, pista: '🤔 ¿Está bien sentir lo que sientes?', explicacion: '✅ No tienes que sentir culpa por decir que no. Cuidarte está bien. Hablarlo con alguien de confianza te ayuda.' },
          { picto: '🫂', situacion: 'Una persona conocida insiste en tocarte o abrazarte aunque le digas que no.', opciones: ['Mantengo mi no y se lo cuento a una persona de confianza', 'Cedo para que pare de insistir', 'Me voy sin decir nada y no lo cuento'], correcta: 0, pista: '🤔 ¿Un no se mantiene aunque la otra persona insista?', explicacion: '✅ Un no se mantiene siempre. Si alguien insiste, es importante contarlo a una persona de confianza.' },
          { picto: '🤐', situacion: 'Alguien te amenaza con contar algo íntimo tuyo si no haces lo que pide.', opciones: ['Lo cuento a una persona de confianza, eso es chantaje y no es tu culpa', 'Hago lo que pide para que no lo cuente', 'Le suplico que no lo cuente y no pido ayuda'], correcta: 0, pista: '🤔 ¿Amenazar con algo íntimo para obligarte es aceptable?', explicacion: '✅ Eso es chantaje y no está bien. No es tu culpa. Una persona de confianza puede actuar para protegerte.' },
          { picto: '🎉', situacion: 'En una fiesta, unas amigas te presionan para que bebas alcohol o hagas cosas que no quieres.', opciones: ['Puedo decir que no y buscar a una persona de confianza', 'Lo hago para encajar en el grupo', 'Me alejo sin avisar a nadie'], correcta: 0, pista: '🤔 ¿Encajar en un grupo vale más que tu seguridad?', explicacion: '✅ Nadie debería presionarte. Puedes decir que no y buscar a una persona de confianza. Tu seguridad va primero.' },
          { picto: '📵', situacion: 'Una persona te pide fotos íntimas y dice que si no se las das, no te quiere.', opciones: ['No se las doy y lo cuento a una persona de confianza, eso es una forma de presión', 'Se las doy para que no se enfade', 'Le doy algunas para que se calle'], correcta: 0, pista: '🤔 ¿El cariño se demuestra con fotos íntimas?', explicacion: '✅ Nadie tiene derecho a pedirte eso. Una persona de confianza puede ayudarte a manejar la situación con seguridad.' },
          { picto: '🎁', situacion: 'Alguien te ofrece dinero o regalos a cambio de hacer algo con tu cuerpo que no quieres.', opciones: ['Nada compra tu derecho a decir que no; lo cuento a una persona de confianza', 'Acepto porque el regalo me viene bien', 'Lo pienso, pero al final acepto'], correcta: 0, pista: '🤔 ¿Un regalo o dinero te obliga a algo con tu cuerpo?', explicacion: '✅ Un regalo o dinero nunca te obliga a nada con tu cuerpo. Cuéntaselo a una persona de confianza.' },
          { picto: '🤝', situacion: 'Sientes que algo no está bien en una relación, pero no sabes cómo salir.', opciones: ['Hablo con una persona de confianza para trazar un plan seguro', 'Sigo igual porque no sé qué hacer', 'Corto la relación de golpe, sin ayuda'], correcta: 0, pista: '🤔 ¿Pedir ayuda para salir es válido?', explicacion: '✅ Pedir ayuda para salir de una relación que no es segura es válido. Una persona de confianza puede acompañarte.' },
          { picto: '📱', situacion: 'Alguien te presiona por mensajes para que hagas algo con tu cuerpo que no quieres.', opciones: ['No respondo a esa presión y lo cuento a alguien de confianza', 'Cedo para que deje de insistir por mensaje', 'Bloqueo pero no se lo cuento a nadie'], correcta: 0, pista: '🤔 ¿La presión por mensaje es menos grave que en persona?', explicacion: '✅ La presión también es grave por mensaje. Puedes cortar la conversación y contarlo a alguien de confianza.' },
          { picto: '🎭', situacion: 'Sientes que tienes que fingir que quieres algo con tu cuerpo para que la otra persona no se sienta mal.', opciones: ['Mis sentimientos importan tanto como los suyos', 'Finjo para no herir sus sentimientos', 'Me callo lo que siento de verdad'], correcta: 0, pista: '🤔 ¿Tus sentimientos importan igual que los de la otra persona?', explicacion: '✅ Tus sentimientos importan igual. No tienes que fingir con tu cuerpo para cuidar los sentimientos de otra persona.' },
          { picto: '🚫', situacion: 'Alguien te dice que ya es "demasiado tarde para decir que no" porque ya habíais empezado algo.', opciones: ['Sé que puedo decir que no en cualquier momento', 'Pienso que ya no puedo parar', 'Sigo aunque no quiera, por no quedar mal'], correcta: 0, pista: '🤔 ¿Puedes cambiar de opinión en cualquier momento?', explicacion: '✅ Siempre puedes decir que no, incluso si algo ya había empezado.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Un grupo de amistades comenta cosas íntimas de otra persona y te piden tu opinión sobre su cuerpo.', opciones: ['Digo que no me parece bien hablar así de nadie', 'Opino igual que el grupo para no quedar mal', 'Cuento algo íntimo mío también'], correcta: 0, pista: '🤔 ¿Está bien hablar del cuerpo de otra persona sin su permiso?', explicacion: '✅ No está bien opinar sobre el cuerpo de otra persona sin su permiso. Puedes decir que no te parece bien.' }
        ]
      },
      {
        id: 'proteccion', nombre: 'Protección e infecciones', descripcion: '8 casos', estrellas: 1,
        casos: [
          { picto: '🛡️', situacion: 'Quieres saber cómo se usa correctamente un método de protección.', opciones: ['Pregunto a un profesional de la salud y me lo explica bien', 'Lo aprendo probando yo sola/o', 'Lo que dice internet me vale'], correcta: 0, pista: '🤔 ¿Quién te enseña a usarlo bien y seguro?', explicacion: '✅ Un profesional de la salud te enseña a usarlo bien y te resuelve dudas. Es la fuente más segura.' },
          { picto: '📍', situacion: 'No sabes dónde comprar protección o te da vergüenza comprarla.', opciones: ['Se puede comprar en farmacia u otros sitios; puedo pedir a alguien de confianza que me acompañe', 'No la compro por vergüenza', 'Pido a una amistad que la compre por mí'], correcta: 0, pista: '🤔 ¿Se puede comprar con discreción?', explicacion: '✅ Se puede comprar en farmacias y otros sitios. Si te da vergüenza, una persona de confianza puede acompañarte.' },
          { picto: '⚠️', situacion: 'Mantuviste relaciones sin protección y te preocupa haber podido contraer una infección.', opciones: ['Voy a un centro de salud cuanto antes, sin esperar síntomas', 'Espero a ver si me sale algo para entonces ir', 'No se lo cuento a nadie por miedo'], correcta: 0, pista: '🤔 ¿Conviene esperar o actuar pronto?', explicacion: '✅ Conviene ir al centro de salud cuanto antes. Muchas infecciones se tratan mejor cuando se cogen a tiempo.' },
          { picto: '🩺', situacion: 'El profesional de la salud te pide hacerte pruebas para descartar una infección de transmisión sexual.', opciones: ['Acepto y pregunto todo lo que quiera saber; es confidencial', 'Digo que no porque me da miedo el resultado', 'Lo aplazo sin fecha, porque no me siento preparada'], correcta: 0, pista: '🤔 ¿Hacerse las pruebas te ayuda a cuidarte?', explicacion: '✅ Hacerse las pruebas es cuidarse. La información es confidencial y puedes preguntar todas las dudas que tengas.' },
          { picto: '💊', situacion: 'Se rompió el preservativo o hubo un problema con la protección.', opciones: ['Voy a un centro de salud a preguntar, también por la anticoncepción de emergencia', 'Espero a ver qué pasa', 'Comento el problema solo con amistades y decido yo'], correcta: 0, pista: '🤔 ¿Quién te puede orientar rápido?', explicacion: '✅ El centro de salud te orienta sin juzgar y te explica si conviene usar la anticoncepción de emergencia. Actuar pronto es importante.' },
          { picto: '👥', situacion: 'Tu pareja se enfada porque le pides que use protección y dice que es desconfianza.', opciones: ['Cuidarse es responsabilidad de las dos personas; puedo pedir ayuda si insiste', 'Acepto no usar protección para que no se enfade', 'Le doy plantón sin explicarme'], correcta: 0, pista: '🤔 ¿Pedir protección es desconfianza?', explicacion: '✅ Pedir protección es cuidarse, no desconfiar. Si alguien se enfada por eso, es importante pedir apoyo a alguien de confianza.' },
          { picto: '📅', situacion: 'No recuerdas cuándo fue tu última revisión de salud sexual.', opciones: ['Pido cita en el centro de salud para una revisión rutinaria', 'No la hago porque creo que no hace falta', 'Espero a tener algún síntoma'], correcta: 0, pista: '🤔 ¿Una revisión rutinaria ayuda aunque no haya síntomas?', explicacion: '✅ Una revisión rutinaria ayuda a detectar cosas a tiempo y a resolver dudas. Se puede pedir en el centro de salud.' },
          { picto: '💬', situacion: 'Una persona de tu entorno te dice que las infecciones de transmisión sexual solo les pasan a otras personas.', opciones: ['Eso no es cierto; a cualquiera le puede pasar y por eso conviene cuidarse', 'Le creo y dejo de usar protección', 'No le contesto pero tampoco me informo'], correcta: 0, pista: '🤔 ¿A quién le puede pasar?', explicacion: '✅ Eso es un mito. A cualquier persona sexualmente activa le puede pasar. Por eso conviene usar protección y hacer revisiones.' },
          { picto: '📖', situacion: 'Quieres entender mejor por qué es importante la protección, más allá de lo que te han contado.', opciones: ['Pregunto a un profesional de la salud para entenderlo bien', 'Doy por hecho que ya lo sé todo', 'Pregunto solo a mis amistades'], correcta: 0, pista: '🤔 ¿Quién te da la información más fiable?', explicacion: '✅ Un profesional de la salud te explica bien el porqué, sin prisas ni juicios.' },
          { picto: '🗓️', situacion: 'No recuerdas si usaste protección correctamente la última vez y tienes dudas.', opciones: ['Consulto mis dudas con un profesional de la salud', 'No le doy importancia', 'Se lo pregunto solo a internet'], correcta: 0, pista: '🤔 ¿Es mejor resolver la duda pronto?', explicacion: '✅ Ante cualquier duda, un profesional de la salud te puede orientar con confianza.' },
          { picto: '💬', situacion: 'Te cuesta hablar con tu pareja sobre usar protección.', opciones: ['Puedo practicar cómo decirlo o pedir apoyo a un profesional', 'Prefiero no hablarlo nunca', 'Dejo que decida solo mi pareja'], correcta: 0, pista: '🤔 ¿Puedes prepararte para tener esa conversación?', explicacion: '✅ Puedes practicar cómo decirlo o pedir ayuda a un profesional para sentirte más segura/o hablándolo.' },
          { picto: '🏥', situacion: 'Te preocupa haber estado en una situación de riesgo hace tiempo y no dijiste nada.', opciones: ['Nunca es tarde para ir a un centro de salud a preguntar', 'Como ya pasó tiempo, ya no hago nada', 'Solo lo hablo con amistades'], correcta: 0, pista: '🤔 ¿Es tarde para pedir ayuda aunque haya pasado tiempo?', explicacion: '✅ Nunca es tarde para preguntar en un centro de salud, aunque haya pasado tiempo.' }
        ]
      }
    ]
  },
  en: {
    porRonda: 5,
    niveles: [
      {
        id: 'consent', nombre: 'My body and consent', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🤗', situacion: 'A family member asks for a hug but you do not want one.', opciones: ['I say I do not want to, and that is okay', 'I hug anyway so I do not offend them', 'I hide without saying anything'], correcta: 0, pista: '🤔 Is your body yours? Can you decide?', explicacion: '✅ Your body is yours. You can say no to a hug, even from someone you know.' },
          { picto: '🏥', situacion: 'You go to the doctor and they need to examine your body.', opciones: ['I ask if a trusted person can come with me', 'I go alone without asking anything', 'I say no to any examination'], correcta: 0, pista: '🤔 Can you ask someone you trust to come with you?', explicacion: '✅ You can ask a trusted person to be with you during a medical exam. It is your right.' },
          { picto: '🚫', situacion: 'Someone touches you in a way you do not like.', opciones: ['I say stop and tell a trusted person', 'I say nothing so I do not bother them', 'I wait for it to stop on its own'], correcta: 0, pista: '🤔 Can you say stop?', explicacion: '✅ You can always say stop. And you can tell someone you trust.' },
          { picto: '🔒', situacion: 'You want to close the door when you change your clothes.', opciones: ['I close the door, my privacy matters', 'I do not close it, it does not matter', 'I only close it if someone is watching'], correcta: 0, pista: '🤔 Do you have a right to privacy?', explicacion: '✅ You have a right to privacy. You can close the door whenever you need to.' },
          { picto: '🙅', situacion: 'Someone keeps trying to kiss you and you do not want to.', opciones: ['I say no, as many times as I need to', 'I let them so they do not get upset', 'I stay still and say nothing'], correcta: 0, pista: '🤔 Can you repeat a no as many times as you need?', explicacion: '✅ You can say no as many times as you need. A no is always respected.' },
          { picto: '🧑‍⚕️', situacion: 'At a medical appointment they ask you to remove clothing for a needed exam.', opciones: ['I ask what it is for and ask for a trusted person to be there', 'I do it without asking anything', 'I refuse any exam at all'], correcta: 0, pista: '🤔 Can you ask questions and ask for company?', explicacion: '✅ You can ask what an exam is for and ask a trusted person to be with you.' },
          { picto: '💬', situacion: 'A friend says that if you really trust them, you will let them see your body.', opciones: ['I tell them trust does not require that', 'I allow it so they do not get upset', 'I hesitate but end up agreeing'], correcta: 0, pista: '🤔 Does trust require anything with your body?', explicacion: '✅ Trust does not require anything with your body. A real friend respects a no.' },
          { picto: '🖐️', situacion: 'You are not sure if you can say no to something you do not like with your body.', opciones: ['Yes, I can say no, always, even if it already started', 'I can only say no at the beginning', 'If I said yes before, I cannot change my mind'], correcta: 0, pista: '🤔 Can you change your mind at any moment?', explicacion: '✅ You can say no at any moment, even if you said yes before.' },
          { picto: '🚗', situacion: 'A family member asks for a kiss on the cheek to say goodbye and you do not want to.', opciones: ['I say I would rather say goodbye another way', 'I give the kiss even though I do not want to', 'I hide without saying anything'], correcta: 0, pista: '🤔 Can you choose how to say goodbye?', explicacion: '✅ You can choose how to say goodbye. A hug, a high five or a wave also work.' },
          { picto: '🛌', situacion: 'Someone comes into your room without knocking while you are changing.', opciones: ['I ask them to knock before coming in', 'I say nothing even though it bothers me', 'I leave the door open from now on'], correcta: 0, pista: '🤔 Can you ask people to knock before entering?', explicacion: '✅ You can ask for privacy. Asking people to knock first is your right.' },
          { picto: '🏊', situacion: 'At the pool, someone touches your back as a joke and you do not find it funny.', opciones: ['I tell them I do not like it and to stop', 'I laugh even though I do not like it', 'I do the same to someone else'], correcta: 0, pista: '🤔 Can you say something bothers you even if it was "a joke"?', explicacion: '✅ You can say something bothers you, even if the other person calls it a joke.' },
          { picto: '🤔', situacion: 'You are not sure if you have to explain yourself when you say you do not want to be touched.', opciones: ['I do not have to explain myself, a no is enough', 'I have to explain the reason well', 'I can only say no if I have a good reason'], correcta: 0, pista: '🤔 Does a no always need a long explanation?', explicacion: '✅ You do not need to explain yourself. A no is enough on its own.' }
        ]
      },
      {
        id: 'relationships', nombre: 'Healthy relationships', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🚷', situacion: 'Your partner does not let you see your friends.', opciones: ['I talk to someone I trust, that is not normal', 'I stop seeing my friends for peace', 'I explain myself every time I want to go out'], correcta: 0, pista: '🤔 Does a healthy relationship keep you away from people you love?', explicacion: '✅ A healthy relationship does not isolate you from people you love. That is a warning sign.' },
          { picto: '📱', situacion: 'Your partner wants to read all your messages and always know where you are.', opciones: ['I set a boundary: my privacy matters, and I ask for support if they insist', 'I give them access to everything so they trust me', 'I only show them some messages'], correcta: 0, pista: '🤔 Does trust need to control everything you do?', explicacion: '✅ Controlling your messages and movements is not love, it is control. You can ask for help.' },
          { picto: '😢', situacion: 'After an argument, your partner tells you everything that happens is your fault.', opciones: ['I think it is not always my fault, and I talk to someone I trust', 'I believe them, they are probably right', 'I apologise even if I do not know why'], correcta: 0, pista: '🤔 In a couple, is the blame always one person’s?', explicacion: '✅ In a healthy relationship, responsibility is shared. No one is always entirely to blame.' },
          { picto: '🎁', situacion: 'Your partner gives you expensive gifts and then asks for things you do not want to do.', opciones: ['I say no, a gift does not obligate me to anything', 'I do what they ask because they gave me a gift', 'I agree so I do not seem ungrateful'], correcta: 0, pista: '🤔 Does a gift obligate you to something?', explicacion: '✅ A gift does not obligate you to anything. You can say no even after receiving a gift.' },
          { picto: '🚪', situacion: 'You want to end a relationship but you are afraid to say it.', opciones: ['I have the right to end a relationship whenever I want, and I can ask for support', 'I stay in the relationship even if I do not want to', 'I wait for the other person to guess'], correcta: 0, pista: '🤔 Do you have the right to decide to end a relationship?', explicacion: '✅ You have the right to end a relationship whenever you want. A trusted person can help you do it safely.' },
          { picto: '👏', situacion: 'Your partner encourages things you enjoy and respects it when you say no.', opciones: ['That is a sign of a healthy relationship', 'That means I do not matter to them', 'I should worry about that'], correcta: 0, pista: '🤔 Are respect and support good signs?', explicacion: '✅ Respecting your likes and your limits is a sign of a healthy relationship. Well spotted!' },
          { picto: '😨', situacion: 'You are afraid of your partner because they sometimes shout or break things when angry.', opciones: ['I tell someone I trust, that is not safe', 'I say nothing so I do not provoke them', 'I think it is normal if they apologise afterwards'], correcta: 0, pista: '🤔 Is fear part of a healthy relationship?', explicacion: '✅ If you are afraid of your partner, that is not safe. Tell someone you trust.' },
          { picto: '🤝', situacion: 'You are not sure if what you feel in your relationship is normal or not.', opciones: ['Talking about it with someone I trust can help me see it clearly', 'I prefer not to talk about it with anyone', 'I think asking about it is overreacting'], correcta: 0, pista: '🤔 Can talking to someone help you?', explicacion: '✅ Talking to a trusted person or a professional can help you see the relationship more clearly.' },
          { picto: '📵', situacion: 'Your partner gets upset if you talk to your friends and wants you to stop seeing them.', opciones: ['I talk to someone I trust, that is not healthy', 'I stop seeing my friends', 'I see them in secret'], correcta: 0, pista: '🤔 Does a healthy partner ask you to give up your friends?', explicacion: '✅ A healthy relationship does not ask you to choose between your partner and your friendships.' },
          { picto: '🙏', situacion: 'Your partner truly apologizes after a mistake and changes their behaviour.', opciones: ['That is a healthy sign if the change is real', 'You should never accept an apology', 'I have to stay angry forever'], correcta: 0, pista: '🤔 Can a relationship improve over time?', explicacion: '✅ Truly apologizing and changing behaviour is part of a healthy relationship.' },
          { picto: '⏳', situacion: 'You feel like things are moving faster than you would like in a new relationship and want to slow down.', opciones: ['I say I want to slow down, and that is okay', "I keep the other person's pace even if I do not want to", 'I say nothing out of fear they will get angry'], correcta: 0, pista: '🤔 Can you set your own pace in a relationship?', explicacion: '✅ You can set your own pace. A healthy partner respects that.' },
          { picto: '🗣️', situacion: 'Your partner listens when you tell them something that worries you, without dismissing it.', opciones: ['That is a sign of a healthy relationship', 'That means I am weak for sharing it', 'I should always keep my worries to myself'], correcta: 0, pista: '🤔 Is being listened to a good sign?', explicacion: '✅ Feeling listened to and not judged is a sign of a healthy relationship.' }
        ]
      },
      {
        id: 'contraception', nombre: 'Contraception', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '❓', situacion: 'You want to know what contraceptive methods exist.', opciones: ['I ask a health professional (doctor, midwife, health centre)', 'I only search online or ask a friend', 'I do not ask because I feel embarrassed'], correcta: 0, pista: '🤔 Who can explain this to you safely?', explicacion: '✅ A health professional explains the options and which one suits you, with no problem at all.' },
          { picto: '💊', situacion: 'A friend gives you a pill and says it is a contraceptive.', opciones: ['I do not take it unless a health professional tells me to', 'I take it because my friend says so', 'I take it without asking anything'], correcta: 0, pista: '🤔 Can you take medicine without a professional telling you to?', explicacion: '✅ Never take medicine that a health professional has not told you to take. It can be dangerous.' },
          { picto: '👩‍⚕️', situacion: 'You do not know who to ask about contraception.', opciones: ['I can go to a health centre or talk to my family doctor', 'I can only ask my friends', 'There is no one to ask'], correcta: 0, pista: '🤔 Are there places that can help you with this?', explicacion: '✅ A health centre or your family doctor can help you, confidentially and without judging you.' },
          { picto: '🤰', situacion: 'You are worried about a possible pregnancy and do not know what to do.', opciones: ['I go to a health centre or tell someone I trust', 'I do nothing and wait to see what happens', 'I only ask friends about it'], correcta: 0, pista: '🤔 Who can help you safely and quickly?', explicacion: '✅ A health centre can inform and help you as soon as possible. You do not have to solve it alone.' },
          { picto: '🙋', situacion: 'You feel embarrassed asking about contraception at a medical appointment.', opciones: ['Even with embarrassment, I have the right to ask and they can help me', 'I do not ask because of embarrassment', 'I wait for the embarrassment to go away forever'], correcta: 0, pista: '🤔 Should embarrassment stop you asking for help?', explicacion: '✅ Health professionals are there to help you, without judging. Asking is a right.' },
          { picto: '🔐', situacion: 'You want what you discuss with a health professional to stay private.', opciones: ['I can ask for it to be confidential, it is my right', 'Everything I say is told to my family without me knowing', 'I cannot ask for privacy at an appointment'], correcta: 0, pista: '🤔 Do you have a right to privacy at an appointment?', explicacion: '✅ You have a right to confidentiality with a health professional. You can ask about it calmly.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Your partner does not want to use any protection and you do.', opciones: ['My decision about my body matters, and I can ask for support if they insist', 'I do what my partner prefers', 'I say nothing to avoid an argument'], correcta: 0, pista: '🤔 Does your opinion about your own body count?', explicacion: '✅ Your decision about your body and your health always matters. You can ask for help if it is not respected.' },
          { picto: '📅', situacion: 'You do not fully understand the information a health professional gave you.', opciones: ['I can ask them to explain it again, more slowly', 'I pretend I understood', 'I never ask again'], correcta: 0, pista: '🤔 Can you ask for it to be explained differently?', explicacion: '✅ You can ask for it to be explained again, more slowly or with pictures. It is your right to understand it.' },
          { picto: '📚', situacion: 'You want to be well informed before making a decision about contraception.', opciones: ['I ask a health professional for information, calmly', 'I decide quickly without researching', 'I follow whatever a random video online says'], correcta: 0, pista: '🤔 Where can you get reliable information?', explicacion: '✅ A health professional gives you reliable information without rushing you.' },
          { picto: '🧑‍⚕️', situacion: 'You do not fully understand a contraceptive method that was explained to you.', opciones: ['I ask for it to be explained a different way', 'I pretend I understood', 'I decide not to use any method just in case'], correcta: 0, pista: '🤔 Can you ask for it to be explained again?', explicacion: '✅ You can ask for it to be explained as many times as you need. Understanding it well matters.' },
          { picto: '👪', situacion: 'You want to talk about contraception with your family, but do not know how to start.', opciones: ['I can ask a professional for help starting that conversation', 'I never talk about it with anyone', 'I wait for them to bring it up first'], correcta: 0, pista: '🤔 Can a professional help you have this conversation?', explicacion: '✅ A health professional can help you prepare for that conversation if it feels hard.' },
          { picto: '🔁', situacion: 'You have changed your mind about the contraceptive method you were using.', opciones: ['I can check it again with a health professional', 'I have to keep using it even if I do not want to', 'I decide alone without asking anyone'], correcta: 0, pista: '🤔 Can you change your decision with professional help?', explicacion: '✅ You can review your decision with a health professional whenever you need to.' }
        ]
      },
      {
        id: 'health', nombre: 'Hygiene and sexual health', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🩹', situacion: 'You notice something unusual on your body and do not know if it is normal.', opciones: ['I go to the doctor or health centre to ask', 'I wait to see if it goes away on its own', 'I only ask a friend about it'], correcta: 0, pista: '🤔 Who can check it safely?', explicacion: '✅ A health professional can check it and explain what is happening, with no problem at all.' },
          { picto: '🧼', situacion: 'You want to know which hygiene habits matter for your body.', opciones: ['I ask a health professional or a trusted person', 'I do not ask because I should already know', 'I copy what my friends do without asking'], correcta: 0, pista: '🤔 Is it okay to ask for it to be explained?', explicacion: '✅ You can ask about hygiene without embarrassment. A professional or trusted person can guide you.' },
          { picto: '🛡️', situacion: 'Someone tells you that using protection is not needed if you trust the other person.', opciones: ['Protection matters, trust does not replace it', 'I believe them and do not use protection', 'I only use it if I am asked to'], correcta: 0, pista: '🤔 Does trust replace protection?', explicacion: '✅ Trust does not replace protection. A health professional can explain why it matters.' },
          { picto: '🚑', situacion: 'You are worried you may have been in a situation that was risky for your health.', opciones: ['I go to a health centre as soon as possible to ask', 'I wait to see if I get symptoms', 'I do not tell anyone out of embarrassment'], correcta: 0, pista: '🤔 Is it better to ask early?', explicacion: '✅ Whenever you are unsure, a health centre can see you soon and confidentially.' },
          { picto: '🗣️', situacion: 'You feel embarrassed talking about these topics with a health professional.', opciones: ['Professionals are used to this and will not judge me', 'I would rather never go to ask about this', 'I only talk about this with friends'], correcta: 0, pista: '🤔 Is a health professional there to help without judging?', explicacion: '✅ A health professional has talked about this many times. They are there to help you, not to judge you.' },
          { picto: '🧴', situacion: 'You are not sure if you need to use protection in a relationship.', opciones: ['I can ask a health professional to be sure', 'I assume it is not needed', 'I only ask my partner'], correcta: 0, pista: '🤔 Who can you ask to be sure?', explicacion: '✅ A health professional can explain when and why to use protection.' },
          { picto: '📋', situacion: 'A health professional offers you a routine sexual health check-up.', opciones: ['I can accept and ask everything I need to know', 'I say no because it scares me', 'I put it off without deciding'], correcta: 0, pista: '🤔 Can a routine check-up help you take care of yourself?', explicacion: '✅ A routine check-up helps you take care of your health. You can ask everything you need to.' },
          { picto: '💗', situacion: 'You are not sure if it is normal to ask questions about your body or your health.', opciones: ['It is always normal to ask about my body and my health', 'I can only ask if it is something serious', 'I should know everything without asking'], correcta: 0, pista: '🤔 Is it always okay to ask about your health?', explicacion: '✅ It is always okay to ask about your body and your health. There are no silly questions.' },
          { picto: '🧴', situacion: 'You are not sure how often it is recommended to change certain intimate hygiene habits.', opciones: ['I ask a health professional', 'I let it go without asking', 'I just copy what my friends do'], correcta: 0, pista: '🤔 Who can give you a reliable answer?', explicacion: '✅ A health professional can give you clear guidance without embarrassment.' },
          { picto: '🩺', situacion: 'You notice discomfort you cannot identify and worry it might be serious.', opciones: ['I book an appointment with a health professional to check it', 'I wait a long time to see if it goes away', 'I only ask strangers online'], correcta: 0, pista: '🤔 Is it better to ask about it soon?', explicacion: '✅ Whenever something feels off, a health professional can check it soon and confidentially.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'A friend gives you sexual health advice you are not sure is true.', opciones: ['I check it with a health professional before following it', "I follow my friend's advice without checking", 'I ignore the topic completely'], correcta: 0, pista: '🤔 Is advice from friends always reliable?', explicacion: '✅ Advice from friends is not always correct. A health professional gives you reliable information.' },
          { picto: '📅', situacion: 'You are not sure how often it is a good idea to get a sexual health check-up.', opciones: ['I ask a health professional', 'I decide never to get checked', 'I just follow what my friends do'], correcta: 0, pista: '🤔 Who can guide you on the right frequency?', explicacion: '✅ A health professional can tell you how often you should get checked.' }
        ]
      },
      {
        id: 'pressure', nombre: 'Pressure and decision', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '💞', situacion: 'Your partner says that if you really love them, you have to prove it by having sex.', opciones: ['Love does not require that; I can say no and ask for support', 'I do it to show that I love them', 'I do it even though I do not want to, so I do not lose them'], correcta: 0, pista: '🤔 Does real love require anything with your body?', explicacion: '✅ Loving someone does not require you to do anything with your body. A trusted person can help you see it clearly.' },
          { picto: '😟', situacion: 'You feel guilty for wanting to say no to something with your body.', opciones: ['I do not have to feel guilty for protecting my body; I can talk about it with someone I trust', 'I keep going even though I feel bad, so I do not disappoint', 'I pretend I do not care'], correcta: 0, pista: '🤔 Is it okay to feel what you feel?', explicacion: '✅ You do not have to feel guilty for saying no. Taking care of yourself is okay. Talking it through with someone you trust can help.' },
          { picto: '🫂', situacion: 'A person you know keeps trying to touch or hug you even after you say no.', opciones: ['I keep my no and tell a trusted person about it', 'I give in so they stop insisting', 'I leave without saying anything and do not tell anyone'], correcta: 0, pista: '🤔 Does a no stay even if the other person keeps pushing?', explicacion: '✅ A no always stands. If someone keeps pushing, it is important to tell a trusted person.' },
          { picto: '🤐', situacion: 'Someone threatens to share something private about you unless you do what they ask.', opciones: ['I tell a trusted person; that is blackmail and it is not my fault', 'I do what they ask so they do not share it', 'I beg them not to share it and do not ask for help'], correcta: 0, pista: '🤔 Is it okay to threaten with something private to make someone do something?', explicacion: '✅ That is blackmail and it is not okay. It is not your fault. A trusted person can act to protect you.' },
          { picto: '🎉', situacion: 'At a party, some friends pressure you to drink alcohol or do things you do not want to.', opciones: ['I can say no and look for a trusted person', 'I do it to fit in with the group', 'I leave without telling anyone'], correcta: 0, pista: '🤔 Is fitting in worth more than your safety?', explicacion: '✅ No one should pressure you. You can say no and look for a trusted person. Your safety comes first.' },
          { picto: '📵', situacion: 'Someone asks you for intimate photos and says that if you do not send them, they do not love you.', opciones: ['I do not send them and I tell a trusted person; that is a form of pressure', 'I send them so they do not get upset', 'I send some of them so they leave me alone'], correcta: 0, pista: '🤔 Does love get proven with intimate photos?', explicacion: '✅ No one has the right to ask you for that. A trusted person can help you handle the situation safely.' },
          { picto: '🎁', situacion: 'Someone offers you money or gifts in exchange for doing something with your body that you do not want to.', opciones: ['Nothing buys my right to say no; I tell a trusted person', 'I accept because the gift is useful to me', 'I think about it, but in the end I accept'], correcta: 0, pista: '🤔 Does a gift or money obligate you to anything with your body?', explicacion: '✅ A gift or money never obligates you to anything with your body. Tell a trusted person about it.' },
          { picto: '🤝', situacion: 'You feel something is not right in a relationship, but you do not know how to leave.', opciones: ['I talk to a trusted person to make a safe plan', 'I stay anyway because I do not know what to do', 'I end the relationship suddenly, without help'], correcta: 0, pista: '🤔 Is it okay to ask for help to leave?', explicacion: '✅ It is okay to ask for help to leave a relationship that is not safe. A trusted person can support you.' },
          { picto: '📱', situacion: 'Someone pressures you through messages to do something with your body that you do not want.', opciones: ['I do not give in to that pressure and tell someone I trust', 'I give in so they stop messaging', 'I block them but tell no one'], correcta: 0, pista: '🤔 Is pressure through messages any less serious than in person?', explicacion: '✅ Pressure through messages is just as serious. You can end the conversation and tell someone you trust.' },
          { picto: '🎭', situacion: 'You feel like you have to pretend you want something with your body so the other person does not feel bad.', opciones: ['My feelings matter as much as theirs', 'I pretend so I do not hurt their feelings', 'I stay quiet about how I really feel'], correcta: 0, pista: "🤔 Do your feelings matter as much as the other person's?", explicacion: "✅ Your feelings matter equally. You do not have to fake wanting something with your body to protect someone else's feelings." },
          { picto: '🚫', situacion: 'Someone tells you it is "too late to say no" because you had already started something.', opciones: ['I know I can say no at any moment', 'I think I cannot stop anymore', 'I keep going even though I do not want to, to avoid looking bad'], correcta: 0, pista: '🤔 Can you change your mind at any point?', explicacion: '✅ You can always say no, even if something had already started.' },
          { picto: '🧑‍🤝‍🧑', situacion: "A group of friends comments on someone else's body and asks for your opinion.", opciones: ['I say I do not think it is right to talk about anyone like that', 'I agree with the group so I do not look out of place', 'I share something intimate of my own too'], correcta: 0, pista: "🤔 Is it okay to discuss someone else's body without their permission?", explicacion: "✅ It is not okay to comment on someone else's body without their permission. You can say you do not think it is right." }
        ]
      },
      {
        id: 'protection', nombre: 'Protection and infections', descripcion: '8 cases', estrellas: 1,
        casos: [
          { picto: '🛡️', situacion: 'You want to know how to use a protection method correctly.', opciones: ['I ask a health professional and they explain it well', 'I learn by trying it on my own', 'What the internet says is enough for me'], correcta: 0, pista: '🤔 Who can teach you to use it safely and correctly?', explicacion: '✅ A health professional teaches you to use it correctly and answers your questions. That is the safest source.' },
          { picto: '📍', situacion: 'You do not know where to buy protection, or you feel embarrassed about buying it.', opciones: ['You can buy it at a pharmacy or other places; I can ask a trusted person to come with me', 'I do not buy it because of embarrassment', 'I ask a friend to buy it for me'], correcta: 0, pista: '🤔 Can you buy it discreetly?', explicacion: '✅ You can buy it at pharmacies and other places. If you feel embarrassed, a trusted person can go with you.' },
          { picto: '⚠️', situacion: 'You had sex without protection and you are worried you may have caught an infection.', opciones: ['I go to a health centre as soon as possible, without waiting for symptoms', 'I wait to see if something shows up before going', 'I do not tell anyone out of fear'], correcta: 0, pista: '🤔 Is it better to wait or act quickly?', explicacion: '✅ It is better to go to the health centre as soon as possible. Many infections are treated more easily when caught early.' },
          { picto: '🩺', situacion: 'A health professional suggests tests to rule out a sexually transmitted infection.', opciones: ['I accept and ask everything I want to know; it is confidential', 'I say no because I am afraid of the result', 'I put it off with no date, because I do not feel ready'], correcta: 0, pista: '🤔 Does getting tested help you take care of yourself?', explicacion: '✅ Getting tested is taking care of yourself. The information is confidential and you can ask every question you have.' },
          { picto: '💊', situacion: 'The condom broke or there was a problem with the protection.', opciones: ['I go to a health centre to ask, also about emergency contraception', 'I wait to see what happens', 'I only talk about it with friends and decide on my own'], correcta: 0, pista: '🤔 Who can guide you quickly?', explicacion: '✅ The health centre guides you without judging and explains whether emergency contraception is a good idea. Acting quickly is important.' },
          { picto: '👥', situacion: 'Your partner gets upset because you ask them to use protection and says it means you do not trust them.', opciones: ['Taking care is both people’s job; I can ask for help if they insist', 'I agree not to use protection so they do not get upset', 'I stand them up without explaining'], correcta: 0, pista: '🤔 Is asking for protection a sign of distrust?', explicacion: '✅ Asking for protection is taking care of yourself, not distrust. If someone gets upset about it, ask a trusted person for support.' },
          { picto: '📅', situacion: 'You do not remember when your last sexual health check-up was.', opciones: ['I book an appointment at the health centre for a routine check-up', 'I do not do it because I think it is not needed', 'I wait until I have some symptom'], correcta: 0, pista: '🤔 Does a routine check-up help even without symptoms?', explicacion: '✅ A routine check-up helps catch things early and answers your questions. You can book it at the health centre.' },
          { picto: '💬', situacion: 'Someone around you says sexually transmitted infections only happen to other people.', opciones: ['That is not true; it can happen to anyone, which is why it matters to take care of yourself', 'I believe them and stop using protection', 'I do not reply, but I also do not get informed'], correcta: 0, pista: '🤔 Who can it happen to?', explicacion: '✅ That is a myth. It can happen to any sexually active person. That is why using protection and getting check-ups matters.' },
          { picto: '📖', situacion: 'You want to understand better why protection matters, beyond what you have been told.', opciones: ['I ask a health professional to understand it well', 'I assume I already know everything', 'I only ask my friends'], correcta: 0, pista: '🤔 Who gives you the most reliable information?', explicacion: '✅ A health professional explains the reasons well, without rushing or judging.' },
          { picto: '🗓️', situacion: 'You do not remember if you used protection correctly last time and have doubts.', opciones: ['I ask a health professional about my doubts', 'I do not think it matters', 'I only search online'], correcta: 0, pista: '🤔 Is it better to resolve doubts soon?', explicacion: '✅ Whenever you are unsure, a health professional can guide you confidently.' },
          { picto: '💬', situacion: 'It is hard for you to talk to your partner about using protection.', opciones: ['I can practise how to say it or ask a professional for support', 'I would rather never talk about it', 'I let my partner decide alone'], correcta: 0, pista: '🤔 Can you prepare for that conversation?', explicacion: '✅ You can practise how to say it or ask a professional for help feeling more confident talking about it.' },
          { picto: '🏥', situacion: 'You are worried about a risky situation from a while ago that you never mentioned.', opciones: ['It is never too late to go ask at a health centre', 'Since time has passed, I do nothing now', 'I only talk about it with friends'], correcta: 0, pista: '🤔 Is it too late to ask for help even after some time has passed?', explicacion: '✅ It is never too late to ask at a health centre, even if time has passed.' }
        ]
      }
    ]
  }
};
