(function () {
  'use strict';
  App.i18n.register({
    title: 'Good Manners',
    instruction: 'Listen to the situation. Choose the polite phrase.',
    
    // Levels
    'nivel.nivel1': 'Easy: simple words',
    'nivel.nivel2': 'Medium: in context',
    'nivel.nivel3': 'Hard: complex situations',
    
    // Contexts (scenarios)
    'situacion.dentista': 'At the dentist',
    'situacion.comida': 'At dinner',
    'situacion.regalo': 'Receiving a gift',
    'situacion.tienda': 'In a shop',
    'situacion.puerta': 'At the door',
    'situacion.parada_bus': 'At the bus stop',
    'situacion.manana_casa': 'Morning at home',
    'situacion.colegio_llegada': 'Arriving at school',
    'situacion.tarde_jugando': 'Playing in the afternoon',
    'situacion.noche_dormir': 'Bedtime',
    'situacion.visita': 'A visitor arrives',
    'situacion.despedida_viaje': 'Saying goodbye for a trip',
    'situacion.cafe_ayuda': 'In a café',
    'situacion.ayuda_escaleras': 'Helping on the stairs',
    'situacion.biblioteca': 'In the library',
    'situacion.juego_grupo': 'Playing in a group',
    'situacion.comida_familia': 'Family meal',
    'situacion.parque_banco': 'In the park',
    'situacion.hospital': 'In the hospital',
    'situacion.supermercado': 'In the supermarket',
    'situacion.teléfono': 'Phone call',
    'situacion.ropa_tienda': 'Clothing shop',
    'situacion.paseo_perro': 'Walking a dog',
    'situacion.ascensor': 'In the elevator',
    'situacion.fiesta': 'At a party',
    'situacion.escuela_despedida': 'School dismissal',
    'situacion.calle_parada': 'Crossing the street',
    'situacion.piscina': 'At the swimming pool',
    
    // Messages/dialogue
    'mensaje.medicamento': 'Here is your medicine.',
    'mensaje.comida': 'Here is your food.',
    'mensaje.regalo': 'This is for you. A gift!',
    'mensaje.ayuda_tienda': 'Can I help you find something?',
    'mensaje.paso': 'I need to pass.',
    'mensaje.acerca': 'Excuse me, can I pass?',
    'mensaje.manana': 'Good morning. Time to get up.',
    'mensaje.saludar': 'Good morning, class!',
    'mensaje.despedida_tarde': 'I have to go home.',
    'mensaje.dormir': 'Time to sleep.',
    'mensaje.llegada_visita': 'I\'ve come to visit!',
    'mensaje.viaje': 'I\'m going on a trip. Goodbye!',
    'mensaje.pedido': 'What would you like?',
    'mensaje.escaleras': 'These stairs are hard for me.',
    'mensaje.libro': 'I can help you find a book.',
    'mensaje.juego': 'We are playing together.',
    'mensaje.pass': 'Can you pass me the bread?',
    'mensaje.banco': 'Can I sit here?',
    'mensaje.medicina': 'Here is your medication.',
    'mensaje.producto': 'I am restocking items.',
    'mensaje.llamada': 'I\'m calling you!',
    'mensaje.talla': 'What size do you need?',
    'mensaje.perro': 'Can I pet your dog?',
    'mensaje.piso': 'What floor are you going to?',
    'mensaje.pastel': 'Here is cake for everyone!',
    'mensaje.hasta_manana': 'See you tomorrow!',
    'mensaje.paso_calle': 'Excuse me, I need to pass.',
    'mensaje.turno': 'Wait your turn.',
    
    // Options/answers
    'opcion.gracias': 'Thank you.',
    'opcion.por_favor': 'Please.',
    'opcion.buenos_dias': 'Good morning.',
    'opcion.buenas_noches': 'Good night.',
    'opcion.adios': 'Goodbye.',
    'opcion.hasta_luego': 'See you later.',
    'opcion.hola': 'Hello.',
    'opcion.ceder_paso': 'Of course. Go ahead, please.',
    'opcion.ayuda': 'I\'ll help you.',
    'opcion.puedo_jugar': 'Can I play with you?',
    'opcion.disculpa': 'Excuse me.',
    'opcion.entendido': 'OK. I understand.',
    'opcion.no_gracias': 'No, thank you.',
    'opcion.silencio': '(No answer)',
    'opcion.no': 'No.',
    
    // Feedback messages
    'feedback.correct': 'Very good! That is the correct answer.',
    'feedback.pista': 'Think: what phrase do people use when they want to be polite?',
    'feedback.explicacion': 'That is the right way to be polite in this situation. Great!',
    
    // Completion
    'fin_ronda': 'Round finished. Very good.',
    'siguiente_nivel': 'You are ready for the next level.',
  "contexto": "You are in a situation with another person. You have to choose what to say or do so they feel good.",
  "pista": "🤔 Think how you would like people to talk to you. What would you say?",
  "explicacion": "✅ That is polite. People feel comfortable when you treat them this way.",
  "transferencia": "This will help you get along with family, friends and at school: kind words always help.",
  }, 'en');
})();
