(function () {
  'use strict';
  App.i18n.register({
    title: 'Buenos Modales',
    instruction: 'Escucha la situación. Elige la frase de cortesía correcta.',
    
    // Levels
    'nivel.nivel1': 'Fácil: palabras simples',
    'nivel.nivel2': 'Medio: en contexto',
    'nivel.nivel3': 'Difícil: situaciones complejas',
    
    // Contexts (scenarios)
    'situacion.dentista': 'En el dentista',
    'situacion.comida': 'En la comida',
    'situacion.regalo': 'Recibiendo un regalo',
    'situacion.tienda': 'En una tienda',
    'situacion.puerta': 'En la puerta',
    'situacion.parada_bus': 'En la parada del autobús',
    'situacion.manana_casa': 'Por la mañana en casa',
    'situacion.colegio_llegada': 'Llegada al colegio',
    'situacion.tarde_jugando': 'Tarde jugando',
    'situacion.noche_dormir': 'Hora de dormir',
    'situacion.visita': 'Una visita llega',
    'situacion.despedida_viaje': 'Despedida de viaje',
    'situacion.cafe_ayuda': 'En una cafetería',
    'situacion.ayuda_escaleras': 'Ayudando en escaleras',
    'situacion.biblioteca': 'En la biblioteca',
    'situacion.juego_grupo': 'Jugando en grupo',
    'situacion.comida_familia': 'Comida en familia',
    'situacion.parque_banco': 'En el parque',
    'situacion.hospital': 'En el hospital',
    'situacion.supermercado': 'En el supermercado',
    'situacion.teléfono': 'Llamada por teléfono',
    'situacion.ropa_tienda': 'Tienda de ropa',
    'situacion.paseo_perro': 'Paseando un perro',
    'situacion.ascensor': 'En el ascensor',
    'situacion.fiesta': 'En una fiesta',
    'situacion.escuela_despedida': 'Salida de la escuela',
    'situacion.calle_parada': 'Cruzando la calle',
    'situacion.piscina': 'En la piscina',
    
    // Messages/dialogue
    'mensaje.medicamento': 'Aquí está tu medicina.',
    'mensaje.comida': 'Toma tu comida.',
    'mensaje.regalo': 'Esto es para ti. ¡Un regalo!',
    'mensaje.ayuda_tienda': '¿Te puedo ayudar a buscar algo?',
    'mensaje.paso': 'Necesito pasar.',
    'mensaje.acerca': 'Disculpa, ¿puedo pasar?',
    'mensaje.manana': 'Buenos días. Hora de levantarse.',
    'mensaje.saludar': '¡Buenos días, clase!',
    'mensaje.despedida_tarde': 'Tengo que irme a casa.',
    'mensaje.dormir': 'Hora de dormir.',
    'mensaje.llegada_visita': '¡He venido a visitarte!',
    'mensaje.viaje': '¡Me voy de viaje! ¡Adiós!',
    'mensaje.pedido': '¿Qué quieres pedir?',
    'mensaje.escaleras': 'Las escaleras me cuesta subirlas.',
    'mensaje.libro': 'Te ayudo a buscar un libro.',
    'mensaje.juego': 'Estamos jugando juntos.',
    'mensaje.pass': '¿Me pasas el pan?',
    'mensaje.banco': '¿Puedo sentarme aquí?',
    'mensaje.medicina': 'Aquí está tu medicamento.',
    'mensaje.producto': 'Estoy reponiendo cosas.',
    'mensaje.llamada': '¡Te estoy llamando!',
    'mensaje.talla': '¿Qué talla necesitas?',
    'mensaje.perro': '¿Puedo tocar tu perro?',
    'mensaje.piso': '¿A qué piso vas?',
    'mensaje.pastel': '¡Aquí hay pastel para todos!',
    'mensaje.hasta_manana': '¡Hasta mañana!',
    'mensaje.paso_calle': 'Disculpa, necesito pasar.',
    'mensaje.turno': 'Espera tu turno.',
    
    // Options/answers
    'opcion.gracias': 'Gracias.',
    'opcion.por_favor': 'Por favor.',
    'opcion.buenos_dias': 'Buenos días.',
    'opcion.buenas_noches': 'Buenas noches.',
    'opcion.adios': 'Adiós.',
    'opcion.hasta_luego': 'Hasta luego.',
    'opcion.hola': 'Hola.',
    'opcion.ceder_paso': 'Claro. Pasa, por favor.',
    'opcion.ayuda': 'Te ayudo.',
    'opcion.puedo_jugar': '¿Puedo jugar con vosotros?',
    'opcion.disculpa': 'Disculpa.',
    'opcion.entendido': 'Vale. Entendido.',
    'opcion.no_gracias': 'No, gracias.',
    'opcion.silencio': '(Sin responder)',
    'opcion.no': 'No.',
    
    // Feedback messages
    'feedback.correct': '¡Muy bien! Esa es la respuesta correcta.',
    'feedback.pista': 'Piensa: ¿qué frase usa la gente cuando quiere ser amable?',
    'feedback.explicacion': 'Esa es la forma correcta de ser amable en esta situación. Bravo.',
    
    // Completion
    'fin_ronda': 'Ronda terminada. Muy bien.',
    'siguiente_nivel': 'Ya estás listo para el siguiente nivel.',
  "contexto": "Estás en una situación con otra persona. Tienes que elegir qué decir o hacer para que la otra se sienta bien.",
  "pista": "🤔 Piensa cómo te gustaría que te hablaran a ti. ¿Qué le dirías?",
  "explicacion": "✅ Así se dice con educación. Las personas se sienten a gusto cuando se las trata así.",
  "transferencia": "Esto te servirá para llevarte bien con la familia, los amigos y en el cole: las palabras amables siempre ayudan.",
  }, 'es');
})();
