/* ============================================================
   Routime — Project presentation text (EN)
   Language-specific file. Loaded conditionally from index.html
   based on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "pageTitle": 'Project presentation',
    "routeNotice": 'This page is not linked from the app. The only way here is typing the address.',
    "tagline": 'An app for autonomy.',
    "lead1": 'Routime is an ',
    "leadStrong": 'occupational therapy web app',
    "lead2": ' built so people with intellectual disabilities can practice daily-living skills on their own, without pressure and with respect for their privacy.',
    "navOrigin": 'The origin',
    "navPrinciples": 'The principles',
    "navTech": 'How it is built',
    "navAreas": 'The areas of work',
    "navSiblings": 'Sibling projects',
    "navAuthorship": 'Who makes it',
    "navCollaborate": 'How to help',
    "originTitle": 'The origin',
    "originP1a": 'Routime comes from a question that comes up at the end of every occupational therapy session: ',
    "originP1em": 'what happens between one session and the next?',
    "originP2": 'A person with an intellectual disability practices with their therapist in a clinic, but afterwards they are on their own at home, at school, or in their free time. We wanted a tool that respected that autonomy, gave families peace of mind, and served the therapist as a complement between sessions, not a replacement.',
    "originP3": 'This app is the result: 66 self-guided activities, all in Plain Language, all accessible, all designed so the person using them can go at their own pace.',
    "principlesTitle": 'The principles we won’t compromise on',
    "principlesIntro": 'These ideas are written into the code first and the text second. If a decision breaks them, that decision is wrong.',
    "principleAutonomyTitle": '🤲 Real autonomy',
    "principleAutonomyText": 'The person using the app can use it without a professional beside them. If it needs constant help, something has not been solved well.',
    "principleNoPressureTitle": '🚫 No pressure',
    "principleNoPressureText": 'No timers, no "game over", no negative scores. Mistakes get encouragement, and retrying is unlimited.',
    "principlePrivacyTitle": '🔒 Privacy by default',
    "principlePrivacyText": 'No sign-up, no cookies, no analytics, no accounts. All progress is saved only on the person’s own device.',
    "principleEasyReadTitle": '📖 Plain Language',
    "principleEasyReadText": 'Short sentences, one idea per sentence, everyday vocabulary. Zero jargon in the interface the person using the app sees.',
    "principleAccessibilityTitle": '♿ Accessibility for everyone',
    "principleAccessibilityText": 'Large buttons, high contrast, audio only when gamification or the activity design requires it (e.g. hearing what is typed on the keyboard, listening to a sequence), full keyboard navigation, and respect for the system’s reduced-motion setting.',
    "principleSoberTechTitle": '🧱 Sober technology',
    "principleSoberTechText": 'HTML, CSS and JavaScript, no frameworks. Works offline and can be installed as an app. Open source, in a public repository.',
    "techTitle": 'How it is built',
    "techIntro1": 'Routime is an installable web app (PWA) made up of more than ',
    "techIntroStrong": '70 static HTML pages',
    "techIntro2": ': a landing page, 66 activities, and hidden routes for families, therapists and maintenance.',
    "techItem1Label": 'No server of its own',
    "techItem1Text": 'it is a set of files served by static hosting. No backend, no databases, no API of its own.',
    "techItem2Label": 'Works offline',
    "techItem2Text": 'once installed, it opens even without an internet connection thanks to the service worker and local cache.',
    "techItem3Label": 'Persistence only in',
    "techItem3Text": 'progress (stars, completed levels, mood log) lives in the device’s browser. It is never sent anywhere.',
    "techItem4Label": 'No frameworks, no build step',
    "techItem4Text1": 'classic JavaScript compatible with older browsers and with the',
    "techItem4Text2": ' protocol. Built so a junior developer can read and modify an activity without surprises.',
    "techItem5Label": 'Open source (MIT license)',
    "techItem5Text": 'anyone can read it, audit it and suggest improvements. Product decisions are written down in this repository, not in closed-door presentations.',
    "techItem6Label": 'Internationalized from day one',
    "techItem6Text": 'every piece of text lives in a file per language. Today Routime is available in Spanish (Spain) and English.',
    "techItem7Label": 'External dependencies: none',
    "techItem7Text": ', except for downloading the Atkinson Hyperlegible and Nunito typefaces (chosen for their high legibility).',
    "areasTitle": 'The areas of work',
    "areasIntro1": 'The 66 activities are grouped into ',
    "areasIntroStrong": 'six therapeutic modules',
    "areasIntro2": ', each with its own color. An activity can work on more than one area (for example, training coordination as well as writing), but it always appears once in the menu, under its main module.',
    "areaAimingTitle": '🎯 Aiming and hands',
    "areaAimingText": 'Eye-hand coordination, fine motor skills, handwriting and copying.',
    "areaAimingCount": '6 activities',
    "areaDailyTitle": '📋 My day to day',
    "areaDailyText": 'Independent-living skills, home tasks and everyday situations.',
    "areaDailyCount": '20 activities',
    "areaMemoryTitle": '🧠 Memory and attention',
    "areaMemoryText": 'Visual and auditory memory, sustained attention and perception of detail.',
    "areaMemoryCount": '10 activities',
    "areaReasoningTitle": '🎲 Board games',
    "areaReasoningText": 'Classic board games, with levels and an opponent that plays gently.',
    "areaReasoningCount": '6 activities',
    "areaLanguageTitle": '💬 Language and comprehension',
    "areaLanguageText": 'Vocabulary, comprehension, spoken and written expression, humor.',
    "areaLanguageCount": '9 activities',
    "areaEmotionsTitle": '💜 Emotions',
    "areaEmotionsText": 'Emotional recognition, self-regulation, empathy and relationships.',
    "areaEmotionsCount": '4 activities',
    "areasNote1": 'Total: ',
    "areasNoteStrong": '66 activities',
    "areasNote2": ', organized so the person chooses by interest, not by obligation. The menu order is not an itinerary: everyone takes their own path.',
    "siblingsTitle": 'Sibling projects',
    "siblingsIntro": 'Routime is the main project of a small group of sibling projects: same team, same accessibility-first philosophy, and no server of their own. Each one is an independent service, with its own domain, reachable from here.',
    "siblingCalculiaName": 'Calculia',
    "siblingCalculiaText": 'Math and logical reasoning.',
    "siblingOkeymoneyName": 'Okeymoney',
    "siblingOkeymoneyText": 'Personal finance and everyday autonomy.',
    "siblingSinonimiaName": 'Sinonimia',
    "siblingSinonimiaText": 'Plain-language dictionary.',
    "siblingTeclatlonName": 'Teclatlon',
    "siblingTeclatlonText": 'Touch-typing with a physical keyboard.',
    "siblingLinkHint": 'Opens in a new tab.',
    "authorshipTitle": 'Who makes it',
    "authorshipP1a": 'Routime is an initiative by ',
    "authorshipP1b": ', an independent studio working on open projects with social and educational impact.',
    "authorshipP2": 'The app is built with the involvement of people with intellectual disabilities, families, occupational therapists and teachers, who test every change and review the content before it reaches production.',
    "authorshipP3": 'The code, the text and the decisions are published openly so anyone or any team can audit them, learn from them, and adapt them to other contexts.',
    "collaborateTitle": 'How to help',
    "collaborateIntro": 'Routime is an open project. There are ways to help that do not require coding:',
    "collaborateItem1Label": 'Try it and share feedback',
    "collaborateItem1Text": 'families, therapists and the people who use the app and report what works and what does not are the key piece of the project. Plain Language mistakes, unfriendly tone and activities that are hard to follow only surface through actual use.',
    "collaborateItem2Label": 'Suggest activities',
    "collaborateItem2Text": 'if a daily-living skill is not covered, or is covered in a way that could be improved, a new activity can be proposed. A professional validates the therapeutic description before it becomes code.',
    "collaborateItem3Label": 'Review content',
    "collaborateItem3Text": 'translations, culturally appropriate examples, accessible explanations. The interface the person using the app sees is in Plain Language, and outside eyes help a lot.',
    "collaborateItem4Label": 'Contribute code',
    "collaborateItem4Text": 'the repository is public. Both small changes (an icon, a translation, a style fix) and large ones (new activities, accessibility, support for more languages) are welcome as long as they respect the project’s principles.',
    "collaborateItem5Label": 'Spread the word',
    "collaborateItem5Text": 'tell people it exists. Many families, professionals and centers do not know tools like this exist until someone shows it to them.',
    "collaborateOutro1": 'All the documentation needed to get started is in the',
    "collaborateOutroLink": 'guide for the support team',
    "collaborateOutro2": 'and in the',
    "collaborateOutro3": 'and',
    "collaborateOutro4": 'files of the repository.',
    "footerActivities": 'Go to the activities',
    "footerTeamGuide": 'Guide for the support team'
  }, 'en');
})();
