/* ============================================================
   Routime — Textos de Ajustes (ES)
   Archivo específico del idioma. Se carga condicionalmente
   desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    title: '⚙️ Routime — Ajustes',
    routeNotice: 'Página de ajustes. No aparece en el menú de la aplicación: solo se llega escribiendo esta dirección.',
    intro: 'Aquí se puede borrar lo guardado en este navegador. Pensada para quien gestiona el dispositivo (familia, profesorado), no para la persona usuaria.',

    stateTitle: 'Estado actual de este navegador',
    currentLanguage: 'Idioma actual: {lang}',
    languageNameEs: 'Español',
    languageNameEn: 'English',
    activitiesWithProgress: 'Actividades con progreso guardado: {n}',
    totalStars: 'Estrellas totales: {n}',

    progressTitle: 'Progreso por actividad',
    progressIntro: 'Estrellas ⭐ guardadas en este navegador, actividad por actividad. "Sin empezar" quiere decir que la persona todavía no ha jugado a esa actividad en este dispositivo.',
    notStarted: 'Sin empezar',
    colActivity: 'Actividad',
    colProgress: 'Progreso',

    module1: '📋 Mi día a día',
    module2: '💜 Emociones',
    module3: '💗 Cuerpo y relaciones',
    module4: '💬 Lenguaje y comprensión',
    module5: '🧠 Memoria y atención',
    module6: '🎯 Puntería y manos',
    module7: '💗 Cuerpo y relaciones',

    activity: {
      'catch': 'Atrapa', 'connect-dots': 'Une los Puntos', 'piano-keys': 'Piano',
      'tracing': 'Trazos', 'coloring': 'Colorear', 'builders': 'Constructores',
      'routines': 'Mis Rutinas', 'house': 'La Casa', 'situations': 'Situaciones',
      'safe-chat': 'Chat Seguro', 'bullying-chat': 'Chat Acoso', 'post-or-not': '¿Lo publico?',
      'social-safety': 'Redes, intimidad y ley', 'signs': 'Señales', 'times-of-day': 'Partes del Día', 'clock': 'El Reloj',
      'what-first': '¿Qué hago primero?', 'what-do-i-need': '¿Qué necesito?', 'where-to-store': '¿Dónde lo guardo?',
      'task-list': 'Lista de Tareas', 'my-agenda': 'Mi agenda', 'what-to-wear': '¿Qué me pongo?',
      'street': 'La Calle', 'emergencies': 'Emergencias', 'phone-numbers': 'Teléfonos Importantes',
      'doctor-visit': 'Se lo Cuento al Médico',
      'first-aid-kit': 'Mi Botiquín',
      'my-details': 'Mis Datos',
      'shopping': 'La Compra', 'shop': 'La Tienda', 'healthy-food': 'Comida Sana',
      'pairs': 'Parejas', 'differences': 'Diferencias', 'whats-missing': '¿Qué falta?',
      'ecos': 'Ecos', 'turns-mirrors': 'Giros y Espejos', 'colored-spelling': 'Ortografía en Colores', 'vocabulary': 'Vocabulario por tema', 'blocks': 'Los Bloques',
      'where-is': '¿Dónde está?', 'path': 'El Camino', 'fit': 'Encaja la Pieza', 'theatre': 'El Teatro',
      'comedy-club': 'Chistes', 'idioms': 'Dichos', 'double-meaning': 'Doble Sentido', 'categories': 'Categorías',
      'sentence': 'La Frase', 'dictionary': 'Diccionario', 'spelling': 'Completa la Palabra',
      'word-search': 'Sopa de Letras',
      'emotions': '¿Cómo me siento?', 'calm': 'Calma', 'friends': 'Entre Amigos', 'my-body': 'Mi Cuerpo Me Avisa', 'good-manners': 'Buenos Modales', 'education-norms': 'Normas de Educación',
      'self-esteem': 'Así Soy Yo',
      'resilience': 'Cuando Algo Me Cuesta',
      'trust-circle': 'Círculo de Confianza',
      'sexual-health': 'Mi Cuerpo, Mis Decisiones'
    },

    backupTitle: 'Copia de mi progreso',
    backupIntro: 'El progreso solo se guarda en este navegador. Si se borra por error (limpieza del navegador, cambio de dispositivo…) se pierde para siempre. Aquí se puede guardar una copia en un archivo y recuperarla más tarde.',
    btnExport: '💾 Guardar copia',
    feedbackExportDone: 'Hecho. Revisa la carpeta de descargas del navegador.',
    retrieveLabel: 'Recuperar copia desde un archivo:',
    btnImport: '📂 Recuperar copia',
    confirmImport: '¿Seguro? Toca otra vez para sustituir el progreso actual.',
    importWarning1: 'Recuperar una copia ',
    importWarningStrong: 'sustituye',
    importWarning2: ' el progreso actual de las actividades que aparezcan en el archivo.',
    feedbackReadError: 'No se ha podido leer el archivo. Inténtalo otra vez.',
    feedbackInvalidFile: 'Ese archivo no es una copia válida (no se puede leer). No se ha tocado nada.',
    feedbackInvalidBackup: 'Ese archivo no es una copia de Routime válida. No se ha tocado nada.',
    feedbackImportDone: 'Hecho. Se ha recuperado el progreso guardado en el archivo.',

    myDetailsTitle: 'Mis Datos: dirección y teléfonos',
    myDetailsIntro: 'Esto alimenta la actividad "Mis Datos". Se guarda solo en este navegador y nunca se envía a internet; se puede borrar en cualquier momento con "Restablecer los datos de la persona" más abajo.',
    ownAddressLabel: 'Dirección de la persona',
    familyAddressLabel: 'Dirección de la familia (solo si es diferente)',
    ownPhoneLabel: 'Teléfono de la persona',
    familyContactsLabel: 'Teléfonos de la familia (hasta 4, opcionales)',
    contactLabelPlaceholder: 'Nombre (p. ej. Mamá)',
    contactPhonePlaceholder: 'Teléfono',
    btnSaveMyDetails: '💾 Guardar datos',
    feedbackMyDetailsSaved: 'Hecho. Datos guardados en este navegador.',

    prefsTitle: 'Preferencias de la persona usuaria',
    prefsIntro: 'Estos ajustes se aplican en todas las actividades. Los cambia quien gestiona el dispositivo; la persona usuaria no necesita venir a esta página.',
    fontSizeLabel: 'Tamaño de letra',
    fontNormal: 'Normal',
    fontLarge: 'Grande',
    fontExtraLarge: 'Muy grande',
    soundsLabel: 'Sonidos de acierto y ánimo',
    soundsOn: '🔊 Activados',
    soundsOff: '🔇 Desactivados',
    soundsNote: 'Esto no afecta a la voz que lee los textos (🔊 de cada pantalla), solo a los pitidos cortos de acierto y ánimo.',

    resetPersonTitle: 'Restablecer los datos de la persona',
    resetPersonIntro1: 'Borra el ',
    resetPersonIntroStrong1: 'idioma elegido',
    resetPersonIntro2: ' (la próxima vez se detecta de nuevo o se vuelve a español) y el ',
    resetPersonIntroStrong2: 'nombre',
    resetPersonIntro3: ' escrito en Teclado y en Piano, y ',
    resetPersonIntroStrong3: 'la dirección y los teléfonos',
    resetPersonIntro4: ' de Mis Datos.',
    resetPersonNote1: 'El progreso (estrellas, niveles y canciones guardadas) de todas las actividades ',
    resetPersonNoteStrong: 'NO se borra',
    resetPersonNote2: '.',
    btnResetPerson: '🧑 Restablecer datos de la persona',
    confirmResetPerson: '¿Seguro? Toca otra vez para borrar idioma y nombres.',
    feedbackResetPersonDone: 'Hecho. Idioma y nombres borrados. El progreso se ha conservado.',

    resetAppTitle: 'Restablecer toda la aplicación',
    resetAppIntro1: 'Borra ',
    resetAppIntroStrong: 'todo',
    resetAppIntro2: ' lo guardado en este navegador: idioma, nombres, estrellas, niveles completados y canciones guardadas de todas las actividades.',
    resetAppNoteStrong: 'No se puede deshacer.',
    resetAppNote2: ' Es como si la aplicación se abriera por primera vez.',
    btnResetApp: '🗑️ Restablecer toda la aplicación',
    confirmResetApp: '¿Seguro? Toca otra vez para borrar TODO. No se puede deshacer.',
    feedbackResetAppDone: 'Hecho. Se ha borrado todo. La aplicación queda como recién instalada.',

    footerActivities: 'Ir a las actividades',
    footerTeamGuide: 'Guía para el equipo de apoyo'
  }, 'es');
})();
