/* ============================================================
   Routime — Textos de ajedrez (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "♟️ Chess",
    "instruccion": "Here you practise two things: first learn how each piece moves, then play a mini match.",
    "volverMenu": "← Menu",
    "elegirNivel": "Choose the level",
    "veces": "wins",
    "rondas": "rounds",
    "menuPiezas": "The pieces",
    "menuPiezasDetalle": "Learn how each piece moves.",
    "menuPartida": "Mini match",
    "menuPartidaDetalle": "Play against the rival. Capture their king.",
    "ariaTableroPiezas": "Puzzle board",
    "puzzleEstado": "Touch a highlighted square. Reach the stars.",
    "movimientoTorre": "The rook ♖ moves straight: forwards, backwards and sideways.",
    "movimientoAlfil": "The bishop ♗ moves diagonally.",
    "movimientoDama": "The queen ♕ moves straight and diagonally.",
    "movimientoCaballo": "The knight ♘ jumps in an L shape.",
    "estrellaRecogida": "⭐ Well done! Star collected.",
    "puzzleCompletado": "🎉 Puzzle complete!",
    "resumenPiezas": "Puzzles completed: {n}.",
    "ayudaPuzzle1": "Look where there is a star ⭐. Which highlighted square takes you closer to it?",
    "ayudaPuzzle2": "Touch the marked square: it takes you closer to the star.",
    "ariaTableroPartida": "Chess board",
    "instruccionPartida": "You play the white pieces. Capture your rival's king ♚ and protect yours ♔.",
    "teToca": "Your turn. Touch one of your pieces.",
    "eligeDestino": "Now touch a highlighted square.",
    "piensaRival": "Your rival is thinking…",
    "hasCapturado": "Well done! You captured one of your rival's pieces.",
    "rivalMueve": "Your rival moves.",
    "rivalCome": "Your rival captured one of your pieces. It is okay. Keep playing.",
    "rivalBloqueado": "Your rival cannot move any piece.",
    "hasGanado": "🎉 You captured the king! You won.",
    "haGanadoRival": "Your rival captured your king. So close! Protect your king with your other pieces.",
    "cerradoGanas": "🎉 You cannot move, but you have more pieces. You won!",
    "cerradoEmpate": "🤝 You cannot move. You both have the same pieces. A draw! Very well played.",
    "cerradoRival": "You cannot move and your rival has more pieces. So close! One more game and you will get it.",
    "jugarOtraVez": "Play again",
    "btnOtroNivel": "Choose another level",
    "btnAyuda": "💡 Help",
    "ariaEscucharAyuda": "Listen to the help",
    "ayudaReyRival1": "Look at your rival's king ♚. Can any of your pieces reach it?",
    "ayudaReyRival2": "Touch the marked piece and capture the king on the marked square: you win!",
    "ayudaSalva1": "Careful: a rival piece can reach your king ♔. How do you keep it safe?",
    "ayudaSalva2": "Touch the marked piece and move it to the marked square: your king stays safe.",
    "ayudaCome1": "Look at your rival's pieces. Can you capture one without danger?",
    "ayudaCome2": "Touch the marked piece and capture on the marked square.",
    "ayudaSegura1": "Before you move, think: can your rival capture your piece on that square?",
    "ayudaSegura2": "Touch the marked piece and move it to the marked square: it is safe there.",
    "ayudaLibre1": "Look at your white pieces. Which one can move?",
    "ayudaLibre2": "Touch the marked piece and move it to the marked square.",
    "piezaTorre": "rook",
    "piezaAlfil": "bishop",
    "piezaDama": "queen",
    "piezaCaballo": "knight",
    "piezaRey": "king",
    "tuPieza": "Your {p}",
    "piezaDelRival": "Rival's {p}",
    "casillaVacia": "Empty square",
    "casillaEstrella": "Star",
    "casillaDestino": "You can move here",
    "fila": "row {f}, column {c}"
  ,
  "transferencia": "This trains your strategy and patience to think before acting."
}, 'en');
})();
