/* ============================================================
   Routime — Textos de ajedrez (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "♟️ El Ajedrez",
    "instruccion": "Aquí practicas dos cosas: primero aprende cómo mueve cada pieza, y después juega una mini partida.",
    "volverMenu": "← Menú",
    "elegirNivel": "Elige el nivel",
    "veces": "victorias",
    "rondas": "rondas",
    "menuPiezas": "Las piezas",
    "menuPiezasDetalle": "Aprende cómo mueve cada pieza.",
    "menuPartida": "Mini partida",
    "menuPartidaDetalle": "Juega contra el rival. Captura su rey.",
    "ariaTableroPiezas": "Tablero de puzzles",
    "puzzleEstado": "Toca una casilla iluminada. Llega a las estrellas.",
    "movimientoTorre": "La torre ♖ va recto: adelante, atrás y a los lados.",
    "movimientoAlfil": "El alfil ♗ va en diagonal.",
    "movimientoDama": "La dama ♕ va recto y en diagonal.",
    "movimientoCaballo": "El caballo ♘ salta en forma de L.",
    "estrellaRecogida": "⭐ ¡Muy bien! Estrella recogida.",
    "puzzleCompletado": "🎉 ¡Puzzle completado!",
    "resumenPiezas": "Puzzles completados: {n}.",
    "ayudaPuzzle1": "Mira dónde hay una estrella ⭐. ¿Qué casilla iluminada te acerca a ella?",
    "ayudaPuzzle2": "Toca la casilla marcada: te acerca a la estrella.",
    "ariaTableroPartida": "Tablero de ajedrez",
    "instruccionPartida": "Tú llevas las piezas blancas. Captura el rey del rival ♚ y protege el tuyo ♔.",
    "teToca": "Te toca. Toca una de tus piezas.",
    "eligeDestino": "Ahora toca una casilla iluminada.",
    "piensaRival": "El rival piensa…",
    "hasCapturado": "¡Bien! Has capturado una pieza del rival.",
    "rivalMueve": "El rival mueve.",
    "rivalCome": "El rival ha capturado una pieza tuya. Tranquilo. Sigue jugando.",
    "rivalBloqueado": "El rival no puede mover ninguna pieza.",
    "hasGanado": "🎉 ¡Has capturado el rey! Has ganado.",
    "haGanadoRival": "El rival ha capturado tu rey. ¡Casi! Protege a tu rey con las otras piezas.",
    "cerradoGanas": "🎉 No puedes mover, pero tienes más piezas. ¡Has ganado!",
    "cerradoEmpate": "🤝 No puedes mover. Tenéis las mismas piezas. ¡Empate! Muy bien jugado.",
    "cerradoRival": "No puedes mover y el rival tiene más piezas. ¡Casi! Otra partida y lo consigues.",
    "jugarOtraVez": "Jugar otra vez",
    "btnOtroNivel": "Elegir otro nivel",
    "btnAyuda": "💡 Ayuda",
    "ariaEscucharAyuda": "Escuchar la ayuda",
    "ayudaReyRival1": "Mira el rey del rival ♚. ¿Alguna de tus piezas puede llegar hasta él?",
    "ayudaReyRival2": "Toca la pieza marcada y captura el rey en la casilla marcada: ¡ganas!",
    "ayudaSalva1": "Cuidado: una pieza del rival puede llegar a tu rey ♔. ¿Cómo lo pones a salvo?",
    "ayudaSalva2": "Toca la pieza marcada y muévela a la casilla marcada: así tu rey queda a salvo.",
    "ayudaCome1": "Mira las piezas del rival. ¿Puedes capturar alguna sin peligro?",
    "ayudaCome2": "Toca la pieza marcada y captura en la casilla marcada.",
    "ayudaSegura1": "Antes de mover, piensa: ¿puede el rival capturar tu pieza en esa casilla?",
    "ayudaSegura2": "Toca la pieza marcada y muévela a la casilla marcada: ahí está a salvo.",
    "ayudaLibre1": "Mira tus piezas blancas. ¿Cuál puede moverse?",
    "ayudaLibre2": "Toca la pieza marcada y muévela a la casilla marcada.",
    "piezaTorre": "torre",
    "piezaAlfil": "alfil",
    "piezaDama": "dama",
    "piezaCaballo": "caballo",
    "piezaRey": "rey",
    "tuPieza": "Tu {p}",
    "piezaDelRival": "{p} del rival",
    "casillaVacia": "Casilla vacía",
    "casillaEstrella": "Estrella",
    "casillaDestino": "Puedes mover aquí",
    "fila": "fila {f}, columna {c}"
  ,
  "transferencia": "Esto entrena tu estrategia y tu paciencia para pensar antes de actuar."
}, 'es');
})();
