#!/usr/bin/env python3
"""Mass-replace Spanish code identifiers with English equivalents.

Targets: all tools/*/app.js, tools/*/index.html, tools/*/styles.css
Safe: does NOT touch string CONTENT values, only identifiers.
Preserves: game logic, i18n string values, data content.
"""

import os
import re

TOOLS_DIR = r"D:\apps\onedrive\jrodriguezgar\OneDrive\dev\git\Miralante\routime\tools"

# Mapping: Spanish → English identifiers
# Format: (pattern, replacement) where pattern is a word boundary match
REPLACEMENTS = [
    # ---- State / progress ----
    (r'\bhechos\b', 'done'),
    (r'\boriginal\b', 'original'),
    (r'\bguardar\b', 'save'),
    (r'\bcargarProgreso\b', 'loadProgress'),
    (r'\bguardarProgreso\b', 'saveProgress'),
    (r'\bcontarHechos\b', 'countDone'),
    (r'\bhechosDe\b', 'doneOf'),
    (r'\brondarCompletas\b', 'completedRounds'),
    (r'\bestrellasAcumuladas\b', 'accumulatedStars'),
    (r'\bmostrandoFeedback\b', 'showingFeedback'),
    (r'\bsiguienteEsperado\b', 'nextExpected'),
    (r'\bnivelActual\b', 'currentLevel'),
    (r'\bmostrarSelectorNiveles\b', 'showLevelSelector'),
    (r'\bprogresoTotal\b', 'totalProgress'),
    (r'\bnivelCompletado\b', 'levelCompleted'),
    (r'\bintentosSocraticos\b', 'socraticAttempts'),
    (r'\bopcionSeleccionada\b', 'selectedOption'),
    (r'\bvalorCorrecto\b', 'correctValue'),
    (r'\btipoActual\b', 'currentType'),
    (r'\bshowingHint\b', 'showingHint'),
    (r'\bmostrarPista\b', 'showHint'),
    (r'\bmostrarExplicacion\b', 'showExplanation'),

    # ---- Screens / DOM IDs ----
    (r'\bpantallaMenu\b', 'menuScreen'),
    (r'\bpantallaRutina\b', 'routineScreen'),
    (r'\bpantallaOrdenar\b', 'orderScreen'),
    (r'\bpantallaListaLibre\b', 'freeListScreen'),
    (r'\bpantallaFinal\b', 'endScreen'),
    (r'\blistaRutinas\b', 'routinesList'),
    (r'\blistaPasos\b', 'stepsList'),
    (r'\blistaOrdenar\b', 'orderList'),
    (r'\btituloRutina\b', 'routineTitle'),
    (r'\btituloOrdenar\b', 'orderTitle'),
    (r'\bfeedbackOrdenar\b', 'orderFeedback'),
    (r'\btabPredefinidas\b', 'predefinedTab'),
    (r'\btabPropias\b', 'ownTab'),
    (r'\bbtnVolver\b', 'btnBack'),
    (r'\bbtnAnadir\b', 'btnAdd'),
    (r'\bbtnGuardar\b', 'btnSave'),
    (r'\bbtnCancelar\b', 'btnCancel'),
    (r'\bbtnVaciar\b', 'btnClear'),
    (r'\bbtnConfirmar\b', 'btnConfirm'),
    (r'\bbtnPracticar\b', 'btnPractice'),
    (r'\bbtnEditar\b', 'btnEdit'),
    (r'\bbtnEscuchar\b', 'btnListen'),
    (r'\bbtnBorrar\b', 'btnErase'),
    (r'\bbtnSubir\b', 'btnMoveUp'),
    (r'\bbtnBajar\b', 'btnMoveDown'),
    (r'\bbtnComprobar\b', 'btnCheck'),
    (r'\bbtnResolver\b', 'btnResolve'),
    (r'\bbtnOtraRutina\b', 'btnAnotherRoutine'),
    (r'\bbtnCheck\b', 'btnCheck'),
    (r'\bbtnPista\b', 'btnHint'),
    (r'\bbtnPistaOrdenar\b', 'btnHintOrder'),
    (r'\bbtnResolverOrdenar\b', 'btnResolveOrder'),
    (r'\bbtnSubirPaso\b', 'btnMoveStepUp'),
    (r'\bbtnBajarPaso\b', 'btnMoveStepDown'),
    (r'\bbtnAnadirItem\b', 'btnAddItem'),
    (r'\bbtnVaciarLista\b', 'btnClearList'),
    (r'\bbtnCancelarEdicion\b', 'btnCancelEdit'),
    (r'\bbtnGuardarLista\b', 'btnSaveList'),
    (r'\bbtnConfirmarGuardarLista\b', 'btnConfirmSaveList'),
    (r'\binputNuevoItem\b', 'inputNewItem'),
    (r'\binputNombreLista\b', 'inputListName'),
    (r'\blistaSlots\b', 'slotsList'),
    (r'\blistaPasosDisponibles\b', 'availableStepsList'),
    (r'\blistasGuardadas\b', 'savedLists'),
    (r'\bitemsListaActual\b', 'currentListItems'),
    (r'\bnombrarLista\b', 'nameList'),
    (r'\bfeedbackListaLibre\b', 'freeListFeedback'),
    (r'\bavisoEditando\b', 'editingNotice'),
    (r'\bbtnRepeat\b', 'btnRepeat'),
    (r'\bbtnNext\b', 'btnNext'),
    (r'\bbtnBackToList\b', 'btnBackToList'),
    (r'\bbtnBackToMenu\b', 'btnBackToMenu'),

    # ---- Routine / task data ----
    (r'\btareasCatalogo\b', 'catalogTasks'),
    (r'\btareasUsuario\b', 'userTasks'),
    (r'\btareasRonda\b', 'roundTasks'),
    (r'\brutinaActual\b', 'currentRoutine'),
    (r'\bordenActual\b', 'currentOrder'),
    (r'\barrastreOrden\b', 'orderDrag'),
    (r'\bsuprimirClickArrastre\b', 'suppressDragClick'),
    (r'\blistaLibre\b', 'freeList'),
    (r'\bnombreOriginal\b', 'originalName'),
    (r'\blistaItems\b', 'listItems'),
    (r'\barrayPasos\b', 'stepsArray'),
    (r'\bcantidad\b', 'count'),
    (r'\beditandoAviso\b', 'editingNotice'),
    (r'\beditandoAvisoTexto\b', 'editingNoticeText'),
    (r'\bPASOS_PLANTILLA\b', 'TEMPLATE_STEPS'),
    (r'\bICONO_POR_DEFECTO\b', 'DEFAULT_ICON'),
    (r'\bpasosPlantilla\b', 'templateSteps'),
    (r'\bpasosAnadir\b', 'addSteps'),
    (r'\bfeedbackAnadir\b', 'addFeedback'),
    (r'\bbtnAnadirGuardar\b', 'btnAddSave'),
    (r'\bbtnAnadirCancelar\b', 'btnAddCancel'),
    (r'\bbtnAnadirGuardar\b', 'btnAddSave'),
    (r'\bpasosAnadir\b', 'addSteps'),
    (r'\biconosGrid\b', 'iconsGrid'),
    (r'\bbtnVolverLista\b', 'btnBackToList'),
    (r'\bbtnRepeat\b', 'btnRepeat'),
    (r'\bbtnVolverMenu\b', 'btnBackToMenu'),

    # ---- Array / collection names ----
    (r'\bSECCIONES\b', 'SECTIONS'),
    (r'\btodasTareas\b', 'allTasks'),
    (r'\brutinasDe\b', 'routinesOf'),
    (r'\bordenRutina\b', 'routineOrder'),
    (r'\bmisListas\b', 'myLists'),
    (r'\blistaOrden\b', 'orderList'),
    (r'\btusListas\b', 'yourLists'),

    # ---- Sections ----
    (r'\bseccionManana\b', 'sectionMorning'),
    (r'\bseccionComida\b', 'sectionLunch'),
    (r'\bseccionLimpieza\b', 'sectionCleaning'),
    (r'\bseccionPersonal\b', 'sectionPersonal'),
    (r'\bseccionMascotas\b', 'sectionPets'),
    (r'\bseccionTarde\b', 'sectionAfternoon'),
    (r'\bseccionSalida\b', 'sectionOuting'),
    (r'\bseccionNoche\b', 'sectionNight'),
    (r'\bseccionRutinas\b', 'routinesSection'),
    (r'\bsubseccionRutinas\b', 'routinesSubsection'),
    (r'\bsubseccionRutinasTitulo\b', 'routinesSubsectionTitle'),
    (r'\bgridTarjetas\b', 'cardsGrid'),
    (r'\btarjetaRutina\b', 'routineCard'),
    (r'\btarjetaRutinaMedia\b', 'routineCardMedia'),
    (r'\btarjetaRutinaCuerpo\b', 'routineCardBody'),
    (r'\btarjetaRutinaAcciones\b', 'routineCardActions'),
    (r'\btarjetaRutinaProgress\b', 'routineCardProgress'),
    (r'\btarjetaRutinaBarra\b', 'routineCardBar'),
    (r'\btarjetaRutinaBarraFill\b', 'routineCardBarFill'),
    (r'\btarjetaCompletada\b', 'cardCompleted'),
    (r'\btarjetaRutinaOrdenar\b', 'routineCardOrder'),
    (r'\bbtnOrdenarRutina\b', 'btnOrderRoutine'),
    (r'\bpasoHecho\b', 'stepDone'),
    (r'\bbtnHecho\b', 'btnDone'),
    (r'\bbtnOrdenar\b', 'btnOrder'),
    (r'\bbtnHecho\b', 'btnDone'),

    # ---- Ordering screen ----
    (r'\bslotOrden\b', 'orderSlot'),
    (r'\bslotLleno\b', 'slotFilled'),
    (r'\bslotSeleccionado\b', 'slotSelected'),
    (r'\bslotPosicion\b', 'slotPosition'),
    (r'\bslotPicto\b', 'slotPicto'),
    (r'\bslotTexto\b', 'slotText'),
    (r'\bslotVacioHint\b', 'slotEmptyHint'),
    (r'\bpasoDisponible\b', 'availableStep'),
    (r'\bpasoDisponiblePicto\b', 'availableStepPicto'),
    (r'\bpasoDisponibleTexto\b', 'availableStepText'),
    (r'\bbtnFlechaSlot\b', 'btnArrowSlot'),
    (r'\bbtnSubirSlot\b', 'btnMoveSlotUp'),
    (r'\bbtnBajarSlot\b', 'btnMoveSlotDown'),
    (r'\bbtnFlechaItem\b', 'btnArrowItem'),
    (r'\bbarraMoverSlot\b', 'moveSlotBar'),
    (r'\bcolocarEnSlot\b', 'placeInSlot'),
    (r'\btocarSlot\b', 'tapSlot'),
    (r'\bcolocarDesdeDisponible\b', 'placeFromAvailable'),
    (r'\bsoltarPasoEnSlot\b', 'dropStepInSlot'),
    (r'\bactualizarBarraMover\b', 'updateMoveBar'),
    (r'\bactualizarBotonesSocraticos\b', 'updateSocraticButtons'),
    (r'\bcontarBienColocados\b', 'countCorrectlyPlaced'),
    (r'\bcomprobarOrden\b', 'checkOrder'),
    (r'\bpistaOrdenar\b', 'hintOrder'),
    (r'\bresolverOrdenar\b', 'resolveOrder'),
    (r'\bactualizarBarraMover\b', 'updateMoveBar'),
    (r'\bpistaSlot\b', 'hintSlot'),
    (r'\bpistaUsada\b', 'hintUsed'),
    (r'\bslotAMarcar\b', 'slotToMark'),
    (r'\bvaciarListaActual\b', 'clearCurrentList'),
    (r'\bquitarItem\b', 'removeItem'),
    (r'\banadirItem\b', 'addItem'),
    (r'\bmoverItem\b', 'moveItem'),
    (r'\beditarLista\b', 'editList'),
    (r'\bcancelarEdicion\b', 'cancelEdit'),
    (r'\bactualizarAvisoEdicion\b', 'updateEditNotice'),
    (r'\bmostrarNombrarLista\b', 'showNameList'),
    (r'\bconfirmarGuardarLista\b', 'confirmSaveList'),
    (r'\bpintarMenu\b', 'renderMenu'),
    (r'\bpintarPasos\b', 'renderSteps'),
    (r'\bpintarOrdenar\b', 'renderOrder'),
    (r'\bpintarListaActual\b', 'renderCurrentList'),
    (r'\bpintarListasGuardadas\b', 'renderSavedLists'),
    (r'\bmostrarTab\b', 'showTab'),
    (r'\babrirRutina\b', 'openRoutine'),
    (r'\babrirOrdenar\b', 'openOrder'),
    (r'\babrirListaLibre\b', 'openFreeList'),
    (r'\bterminarRutina\b', 'endRoutine'),
    (r'\bmarcarHecho\b', 'markDone'),
    (r'\babrirPasos\b', 'openSteps'),
    (r'\bvolverALista\b', 'backToList'),
    (r'\brelacionActual\b', 'currentRelation'),
    (r'\bmomento\b', 'timeOfDay'),
    (r'\bmomentoId\b', 'timeOfDayId'),
    (r'\bestado\b', 'status'),
    (r'\bbotonCorrecto\b', 'correctButton'),
    (r'\bnivelElegido\b', 'chosenLevel'),
    (r'\bestadoJuego\b', 'gameState'),
    (r'\bmostrarNivel\b', 'showLevel'),
    (r'\brondaActual\b', 'currentRound'),
    (r'\bnivelElegido\b', 'chosenLevel'),
    (r'\bcomprobarRespuesta\b', 'checkAnswer'),
    (r'\bmostrarResultado\b', 'showResult'),
    (r'\binciarRonda\b', 'startRound'),
    (r'\binciarJuego\b', 'startGame'),
    (r'\bterminarRonda\b', 'endRound'),
    (r'\bsiguienteRonda\b', 'nextRound'),
    (r'\belegirAleatorio\b', 'chooseRandom'),
    (r'\bbotonElegido\b', 'chosenButton'),
    (r'\bnivelCompletado\b', 'levelCompleted'),
    (r'\bcantidadItems\b', 'itemCount'),
    (r'\bitemsElegidos\b', 'chosenItems'),
    (r'\bestadoActivo\b', 'activeState'),
    (r'\bmomentoActual\b', 'currentTime'),
    (r'\bcontadorErrores\b', 'errorCount'),
    (r'\bcontadorAciertos\b', 'hitCount'),
    (r'\bnivelActual\b', 'currentLevel'),
    (r'\bfechaActual\b', 'currentDate'),
    (r'\bfechaHoy\b', 'todayDate'),
    (r'\bfechaRutina\b', 'routineDate'),
    (r'\bmomentoRutina\b', 'routineTime'),
    (r'\bestadoRutina\b', 'routineState'),
    (r'\bresultadoAnterior\b', 'previousResult'),
    (r'\bnivelMostrado\b', 'shownLevel'),
    (r'\bestadoAnterior\b', 'previousState'),
    (r'\bnivelAnterior\b', 'previousLevel'),
    (r'\bintentoActual\b', 'currentAttempt'),
    (r'\bnivelIntentos\b', 'levelAttempts'),
    (r'\bcorrecto\b', 'correct'),
    (r'\bincorrecto\b', 'incorrect'),
    (r'\bseleccionado\b', 'selected'),
    (r'\bcompleto\b', 'complete'),
    (r'\btotalItems\b', 'totalItems'),
    (r'\bitemActual\b', 'currentItem'),
    (r'\bmostrarSiguiente\b', 'showNext'),
    (r'\bocultarPantalla\b', 'hideScreen'),
    (r'\bmostrarPantalla\b', 'showScreen'),
    (r'\bpantallaActual\b', 'currentScreen'),
    (r'\binstruccionActiva\b', 'activeInstruction'),
    (r'\btextoFeedback\b', 'feedbackText'),
    (r'\bmensajeFeedback\b', 'feedbackMessage'),
    (r'\bfeedbackActual\b', 'currentFeedback'),
    (r'\bestadoActual\b', 'currentState'),
    (r'\bresultadoActual\b', 'currentResult'),
    (r'\btiempoRestante\b', 'remainingTime'),
    (r'\bcontadorTiempo\b', 'timeCounter'),
    (r'\biniciarTemporizador\b', 'startTimer'),
    (r'\bpararTemporizador\b', 'stopTimer'),
    (r'\bactualizarTemporizador\b', 'updateTimer'),
    (r'\bpistaMostrada\b', 'hintShown'),
    (r'\bsolucionMostrada\b', 'solutionShown'),
    (r'\bexplicacionMostrada\b', 'explanationShown'),
    (r'\bmostrarPista\b', 'showHint'),
    (r'\bmostrarSolucion\b', 'showSolution'),
    (r'\bmostrarExplicacion\b', 'showExplanation'),
    (r'\bhayPista\b', 'hasHint'),
    (r'\bhintShown\b', 'hintShown'),
    (r'\bexplanationShown\b', 'explanationShown'),

    # ---- Education-norms specific ----
    (r'\brondasCompletas\b', 'completedRounds'),
    (r'\bestrellasAcumuladas\b', 'accumulatedStars'),
    (r'\bsituacionActual\b', 'currentSituation'),
    (r'\bmostrarSelectorNiveles\b', 'showLevelSelector'),
    (r'\bcontainerNiveles\b', 'levelsContainer'),
    (r'\bestrellasDiv\b', 'starsDiv'),
    (r'\bpresentarSituacion\b', 'presentSituation'),
    (r'\bcrearOpciones\b', 'createOptions'),
    (r'\bevaluarRespuesta\b', 'evaluateAnswer'),
    (r'\bmanejarError\b', 'handleError'),
    (r'\bsiguienteSituacion\b', 'nextSituation'),
    (r'\bcompletarNivel\b', 'completeLevel'),
    (r'\bnivelIntentos\b', 'levelAttempts'),

    # ---- Spelling / vocabulary specific ----
    (r'\bpalabraActual\b', 'currentWord'),
    (r'\bpalabras\b', 'words'),
    (r'\bpalabraElegida\b', 'chosenWord'),
    (r'\bletras\b', 'letters'),
    (r'\bletraActual\b', 'currentLetter'),
    (r'\bletraCorrecta\b', 'correctLetter'),
    (r'\bposicionLetra\b', 'letterPosition'),
    (r'\bletraSeleccionada\b', 'selectedLetter'),
    (r'\bteclaVirtual\b', 'virtualKey'),
    (r'\bteclaIncorrecta\b', 'wrongKey'),
    (r'\bteclaCorrecta\b', 'correctKey'),
    (r'\bteclasActivas\b', 'activeKeys'),
    (r'\bopcionLetra\b', 'letterOption'),
    (r'\bpalabraLetras\b', 'wordLetters'),
    (r'\bpalabraOpciones\b', 'wordOptions'),
    (r'\bpalabraCorrecta\b', 'correctWord'),
    (r'\bopcionCorrecta\b', 'correctOption'),
    (r'\bopcionIncorrecta\b', 'incorrectOption'),
    (r'\bnivelPalabras\b', 'wordLevel'),
    (r'\bpalabrasNivel\b', 'wordsAtLevel'),
    (r'\bestadoVerificacion\b', 'verificationState'),
    (r'\bopcionVerificacion\b', 'verificationOption'),
    (r'\bresultadoVerificacion\b', 'verificationResult'),
    (r'\bbotonLetra\b', 'letterButton'),
    (r'\bpalabraEnunciado\b', 'wordPrompt'),
    (r'\bpalabraCorrecta\b', 'correctWord'),
    (r'\bdefinicionCorrecta\b', 'correctDefinition'),
    (r'\bdefinicionIncorrecta\b', 'incorrectDefinition'),
    (r'\bdefinicionSeleccionada\b', 'selectedDefinition'),
    (r'\bdefiniciones\b', 'definitions'),
    (r'\bpalabrasCorrectas\b', 'correctWords'),
    (r'\bnivelPalabras\b', 'wordLevel'),
    (r'\bpalabrasCompletadas\b', 'completedWords'),
    (r'\bpalabrasTotales\b', 'totalWords'),
    (r'\bcompletarPalabra\b', 'completeWord'),
    (r'\bverificarPalabra\b', 'verifyWord'),
    (r'\bnivelCompletado\b', 'levelCompleted'),
    (r'\binciarNivel\b', 'startLevel'),
    (r'\bsiguienteNivel\b', 'nextLevel'),
    (r'\bnivelPalabra\b', 'wordLevel'),
    (r'\bpalabrasNivelActual\b', 'currentLevelWords'),
    (r'\bpalabraActualIndex\b', 'currentWordIndex'),

    # ---- Dictionary / double-meaning specific ----
    (r'\bopciones\b', 'options'),
    (r'\bopcionCorrecta\b', 'correctOption'),
    (r'\bopcionSeleccionada\b', 'selectedOption'),
    (r'\bvalorCorrecto\b', 'correctValue'),
    (r'\bvalorIncorrecto\b', 'incorrectValue'),
    (r'\btipoActual\b', 'currentType'),
    (r'\bpreguntaActual\b', 'currentQuestion'),
    (r'\bopcionesPregunta\b', 'questionOptions'),
    (r'\brespuestaCorrecta\b', 'correctAnswer'),
    (r'\brespuestaIncorrecta\b', 'incorrectAnswer'),
    (r'\brespuestaSeleccionada\b', 'selectedAnswer'),
    (r'\bestadoPregunta\b', 'questionState'),
    (r'\bcontadorPreguntas\b', 'questionCounter'),
    (r'\bcomprobacionRespuesta\b', 'checkAnswer'),
    (r'\bmotrarRetroalimentacion\b', 'showFeedback'),
    (r'\bcontinuarPregunta\b', 'nextQuestion'),
    (r'\bfinalizarCuestionario\b', 'finishQuiz'),

    # ---- Generic UI identifiers ----
    (r'\bpantallaBienvenida\b', 'welcomeScreen'),
    (r'\bpantallaJuego\b', 'gameScreen'),
    (r'\bpantallaResultado\b', 'resultScreen'),
    (r'\bmensajePantalla\b', 'screenMessage'),
    (r'\binstruccionPantalla\b', 'screenInstruction'),
    (r'\btextoInformativo\b', 'infoText'),
    (r'\betiquetaTexto\b', 'labelText'),
    (r'\btituloSeccion\b', 'sectionTitle'),
    (r'\bdescripcionSeccion\b', 'sectionDescription'),
    (r'\btextoBoton\b', 'buttonText'),
    (r'\bvalorInput\b', 'inputValue'),
    (r'\btextoInput\b', 'inputText'),
    (r'\bnombreInput\b', 'inputName'),
    (r'\bmensajeError\b', 'errorMessage'),
    (r'\bmensajeExito\b', 'successMessage'),
    (r'\bmensajeAlerta\b', 'alertMessage'),
    (r'\bmensajeInfo\b', 'infoMessage'),
    (r'\btextoAyuda\b', 'helpText'),
    (r'\btooltipTexto\b', 'tooltipText'),
    (r'\batributoAlt\b', 'altAttribute'),
    (r'\batributoTitle\b', 'titleAttribute'),
    (r'\batributoAriaLabel\b', 'ariaLabelAttribute'),

    # ---- Generic data identifiers ----
    (r'\btextoIncorrecto\b', 'incorrectText'),
    (r'\btextoCorrecto\b', 'correctText'),
    (r'\btextoSeleccionado\b', 'selectedText'),
    (r'\btextoRespuesta\b', 'answerText'),
    (r'\bvalorRespuesta\b', 'answerValue'),
    (r'\bresultadoVerificacion\b', 'verificationResult'),
    (r'\bresultadoPregunta\b', 'questionResult'),
    (r'\bresultadoItem\b', 'itemResult'),
    (r'\bestadoItem\b', 'itemState'),
    (r'\bitemSeleccionado\b', 'selectedItem'),
    (r'\bitemCorrecto\b', 'correctItem'),
    (r'\bitemIncorrecto\b', 'incorrectItem'),
    (r'\bgrupoItems\b', 'itemsGroup'),
    (r'\bopcionesGrupo\b', 'groupOptions'),
    (r'\belementosGrupo\b', 'groupElements'),
    (r'\bcontenedorGrupo\b', 'groupContainer'),
    (r'\bestadoGlobal\b', 'globalState'),
    (r'\bconfigGlobal\b', 'globalConfig'),
    (r'\bopcionesConfig\b', 'configOptions'),
    (r'\bparametrosConfig\b', 'configParams'),
    (r'\bvaloresConfig\b', 'configValues'),

    # ---- CSS classes ----
    (r'\btarjeta-rutina\b', 'routine-card'),
    (r'\btarjeta-completada\b', 'card-completed'),
    (r'\btarjeta-rutina-ordenar\b', 'routine-card-order'),
    (r'\bpestanas-rutinas\b', 'routine-tabs'),
    (r'\bpestana-rutinas\b', 'routine-tab'),
    (r'\bactualla\b', 'active'),
    (r'\bitem-lista-actual\b', 'current-list-item'),
    (r'\bitem-lista-flechas\b', 'list-item-arrows'),
    (r'\bbtn-flecha-item\b', 'btn-arrow-item'),
    (r'\bbtn-quitar-item\b', 'btn-remove-item'),
    (r'\blista-guardada\b', 'saved-list'),
    (r'\blista-guardada-editando\b', 'saved-list-editing'),
    (r'\blista-guardada-fila\b', 'saved-list-row'),
    (r'\blista-guardada-info\b', 'saved-list-info'),
    (r'\blista-guardada-acciones\b', 'saved-list-actions'),
    (r'\blista-guardada-items\b', 'saved-list-items'),
    (r'\bnombrar-lista\b', 'name-list'),
    (r'\bfila-anadir-item\b', 'add-item-row'),
    (r'\binput-lista\b', 'input-list'),
    (r'\binput-nombre-lista\b', 'input-list-name'),
    (r'\bplaceholder\b', 'placeholder-text'),
    (r'\baviso-editando\b', 'editing-notice'),
    (r'\bbtn-cancelar-edicion\b', 'btn-cancel-edit'),
    (r'\border-dos-columnas\b', 'order-two-columns'),
    (r'\border-col\b', 'order-col'),
    (r'\border-col-tu\b', 'order-col-yours'),
    (r'\border-col-pasos\b', 'order-col-steps'),
    (r'\bpila-slots\b', 'slots-stack'),
    (r'\bbarra-mover-slot\b', 'move-slot-bar'),
    (r'\bbtn-flecha-slot\b', 'btn-arrow-slot'),
    (r'\bbtn-subir-slot\b', 'btn-move-slot-up'),
    (r'\bbtn-bajar-slot\b', 'btn-move-slot-down'),
    (r'\bfila\b', 'row'),
    (r'\btexto\b', 'text'),
    (r'\bestado\b', 'state'),
    (r'\bnombre\b', 'name'),
    (r'\bpicto\b', 'picto'),
    (r'\bpasos\b', 'steps'),
    (r'\bhecho\b', 'done'),
    (r'\bactual\b', 'current'),
    (r'\blleno\b', 'filled'),
    (r'\bseleccionado\b', 'selected'),
    (r'\bdisponible\b', 'available'),
    (r'\barrastrando\b', 'dragging'),
    (r'\boculto\b', 'hidden'),
    (r'\bcentrado\b', 'centered'),
    (r'\bcolumna\b', 'column'),
    (r'\bcolumna-origen\b', 'column-source'),
    (r'\bcolumna-destino\b', 'column-destination'),
    (r'\blista-tareas\b', 'tasks-list'),
    (r'\blista-ordenada\b', 'ordered-list'),
    (r'\blista-dos-columnas\b', 'two-columns'),
    (r'\bfila-tarea\b', 'task-row'),
    (r'\bfila-ordenada\b', 'ordered-row'),
    (r'\bfila-picto\b', 'row-picto'),
    (r'\bfila-numero\b', 'row-number'),
    (r'\bfila-nombre\b', 'row-name'),
    (r'\bfila-controles\b', 'row-controls'),
    (r'\bbtn-fila\b', 'row-btn'),
    (r'\bmover-derecha\b', 'move-right'),
    (r'\bmover-izquierda\b', 'move-left'),
    (r'\bmensaje-vacio\b', 'empty-message'),
    (r'\bpasos-lista\b', 'steps-list'),
    (r'\bpaso-anadir\b', 'add-step'),
    (r'\bpaso-numero\b', 'step-number'),
    (r'\btarea-cabecera\b', 'task-header'),
    (r'\btarea-picto\b', 'task-picto'),
    (r'\btarea-titulo\b', 'task-title'),
    (r'\bpila-secuencia\b', 'sequence-stack'),
    (r'\bpila-disponibles\b', 'available-stack'),
    (r'\bemojis-grande\b', 'big-emoji'),
    (r'\bseccion-rutinas\b', 'routines-section'),
    (r'\bgrid-tarjetas\b', 'cards-grid'),
    (r'\bsubseccion-rutinas\b', 'routines-subsection'),
    (r'\bsubseccion-rutinas-titulo\b', 'routines-subsection-title'),
    (r'\blista-rutinas\b', 'routines-list'),
    (r'\blista-items-actual\b', 'current-items-list'),
    (r'\blistas-guardadas\b', 'saved-lists'),
    (r'\bcompletada-hoy\b', 'completed-today'),

    # ---- Additional i18n key names in strings ----
    (r'\bcompletadaHoy\b', 'completedToday'),
    (r'\blistaActualVacia\b', 'currentListEmpty'),
    (r'\blistaGuardadaFeedback\b', 'listSavedFeedback'),
    (r'\blistaActualizadaFeedback\b', 'listUpdatedFeedback'),
    (r'\blistaBorradaFeedback\b', 'listDeletedFeedback'),
    (r'\bariaSubirItem\b', 'ariaMoveUpItem'),
    (r'\bariaBajarItem\b', 'ariaMoveDownItem'),
    (r'\bariaQuitarItem\b', 'ariaRemoveItem'),
    (r'\bariaVerLista\b', 'ariaViewList'),
    (r'\bariaEditarLista\b', 'ariaEditList'),
    (r'\bariaEscucharLista\b', 'ariaListenList'),
    (r'\bariaBorrarLista\b', 'ariaDeleteList'),
    (r'\bariaPasoHecho\b', 'ariaStepDone'),
    (r'\bariaSlotLleno\b', 'ariaSlotFilled'),
    (r'\bariaSlotVacio\b', 'ariaSlotEmpty'),
    (r'\bariaPasoDisponible\b', 'ariaStepAvailable'),
    (r'\bariaInputItem\b', 'ariaInputItem'),
    (r'\bplaceholderInputItem\b', 'placeholderInputItem'),
    (r'\btarjetaListasLibresNombre\b', 'freeListCardName'),
    (r'\btarjetaListasLibresDescripcion\b', 'freeListCardDescription'),
    (r'\blistasLibresDescripcion\b', 'freeListsDescription'),
    (r'\bseccionListasLibres\b', 'freeListsSection'),
    (r'\bpromptNombreLista\b', 'promptListName'),
    (r'\bpromptNombreListaDefault\b', 'promptListNameDefault'),
    (r'\bsubseccionPasos\b', 'subsectionSteps'),
    (r'\bsubseccionOrdenar\b', 'subsectionOrder'),
    (r'\binstruccionOrdenar\b', 'orderInstruction'),
    (r'\betiquetaTuOrden\b', 'labelYourOrder'),
    (r'\betiquetaPasosDisponibles\b', 'labelAvailableSteps'),
    (r'\borderIncompleto\b', 'orderIncomplete'),
    (r'\borderCorrecto\b', 'orderCorrect'),
    (r'\borderIncorrecto\b', 'orderIncorrect'),
    (r'\bresolverOrdenar\b', 'resolveOrder'),
    (r'\blistaLibreTitulo\b', 'freeListTitle'),
    (r'\blistaLibreInstruccion\b', 'freeListInstruction'),
    (r'\blistaLibreTransferencia\b', 'freeListTransfer'),
    (r'\brutinaCompletadaTitulo\b', 'routineCompletedTitle'),
    (r'\bbtnOtraRutina\b', 'btnAnotherRoutine'),
    (r'\blistOrden\b', 'orderList'),
    (r'\bcantidad\b', 'count'),

    # ---- Time-of-day / sections ----
    (r'\bseccionManana\b', 'sectionMorning'),
    (r'\bseccionComida\b', 'sectionLunch'),
    (r'\bseccionNoche\b', 'sectionNight'),
    (r'\bseccionSalida\b', 'sectionOuting'),
    (r'\bmomentoId\b', 'timeOfDayId'),

    # ---- Generic function names ----
    (r'\binciarJuego\b', 'startGame'),
    (r'\bterminarJuego\b', 'endGame'),
    (r'\binciarRonda\b', 'startRound'),
    (r'\bterminarRonda\b', 'endRound'),
    (r'\binciarNivel\b', 'startLevel'),
    (r'\bterminarNivel\b', 'endLevel'),
    (r'\breiniciarJuego\b', 'restartGame'),
    (r'\bactualizarPantalla\b', 'updateScreen'),
    (r'\bmostrarPantalla\b', 'showScreen'),
    (r'\bocultarPantalla\b', 'hideScreen'),
    (r'\bmostrarMensaje\b', 'showMessage'),
    (r'\bocultarMensaje\b', 'hideMessage'),
    (r'\bmostrarFeedback\b', 'showFeedback'),
    (r'\bmostrarExito\b', 'showSuccess'),
    (r'\bmostrarError\b', 'showError'),
    (r'\bmostrarPista\b', 'showHint'),
    (r'\bmostrarSolucion\b', 'showSolution'),
    (r'\bmostrarExplicacion\b', 'showExplanation'),
    (r'\bcomprobarRespuesta\b', 'checkAnswer'),
    (r'\bevaluarRespuesta\b', 'evaluateAnswer'),
    (r'\bprocesarRespuesta\b', 'processAnswer'),
    (r'\bseleccionarOpcion\b', 'selectOption'),
    (r'\bseleccionarNivel\b', 'selectLevel'),
    (r'\bseleccionarDificultad\b', 'selectDifficulty'),
    (r'\brenderizarOpciones\b', 'renderOptions'),
    (r'\brenderizarPregunta\b', 'renderQuestion'),
    (r'\brenderizarFeedback\b', 'renderFeedback'),
    (r'\brenderizarProgreso\b', 'renderProgress'),
    (r'\brenderizarEstado\b', 'renderState'),
    (r'\brenderizarPantalla\b', 'renderScreen'),
    (r'\brenderizarJuego\b', 'renderGame'),
    (r'\brenderizarMenu\b', 'renderMenu'),
    (r'\brenderizarResultado\b', 'renderResult'),
    (r'\brenderizarFinal\b', 'renderFinal'),
    (r'\brenderizarNivel\b', 'renderLevel'),
    (r'\brenderizarRonda\b', 'renderRound'),
    (r'\brenderizarPasos\b', 'renderSteps'),
    (r'\brenderizarItems\b', 'renderItems'),
    (r'\brenderizarOpciones\b', 'renderOptions'),
    (r'\brenderizarTeclado\b', 'renderKeyboard'),
    (r'\brenderizarPalabra\b', 'renderWord'),
    (r'\brenderizarLetras\b', 'renderLetters'),
    (r'\brenderizarDefiniciones\b', 'renderDefinitions'),
    (r'\brenderizarSituaciones\b', 'renderSituations'),
    (r'\brenderizarRespuestas\b', 'renderAnswers'),
    (r'\brenderizarRetroalimentacion\b', 'renderFeedback'),
    (r'\bconfigurarTeclado\b', 'setupKeyboard'),
    (r'\bconfigurarJuego\b', 'setupGame'),
    (r'\bconfigurarNivel\b', 'setupLevel'),
    (r'\bconfigurarRonda\b', 'setupRound'),
    (r'\bmanejarTecla\b', 'handleKey'),
    (r'\bmanejarClick\b', 'handleClick'),
    (r'\bmanejarTouch\b', 'handleTouch'),
    (r'\bmanejarEvento\b', 'handleEvent'),
    (r'\bmanejarRespuesta\b', 'handleAnswer'),
    (r'\bmanejarError\b', 'handleError'),
    (r'\bmanejarTiempo\b', 'handleTime'),
    (r'\bmanejarFin\b', 'handleEnd'),
    (r'\bmanejarInicio\b', 'handleStart'),
    (r'\bmanejarReinicio\b', 'handleRestart'),
    (r'\bmanejarPausa\b', 'handlePause'),
    (r'\bmanejarContinuar\b', 'handleResume'),
    (r'\bgenerarPregunta\b', 'generateQuestion'),
    (r'\bgenerarOpcion\b', 'generateOption'),
    (r'\bgenerarNivel\b', 'generateLevel'),
    (r'\bgenerarRonda\b', 'generateRound'),
    (r'\bgenerarJuego\b', 'generateGame'),
    (r'\bsiguientePregunta\b', 'nextQuestion'),
    (r'\bsiguienteNivel\b', 'nextLevel'),
    (r'\bsiguienteRonda\b', 'nextRound'),
    (r'\bsiguienteItem\b', 'nextItem'),
    (r'\bsiguientePaso\b', 'nextStep'),
    (r'\bterminarJuego\b', 'endGame'),
    (r'\bterminarNivel\b', 'endLevel'),
    (r'\bterminarRonda\b', 'endRound'),
    (r'\bterminarItem\b', 'endItem'),
    (r'\bcompletarJuego\b', 'completeGame'),
    (r'\bcompletarNivel\b', 'completeLevel'),
    (r'\bcompletarRonda\b', 'completeRound'),
    (r'\bcompletarItem\b', 'completeItem'),
    (r'\bfinalizarJuego\b', 'finishGame'),
    (r'\bfinalizarNivel\b', 'finishLevel'),
    (r'\bfinalizarRonda\b', 'finishRound'),
    (r'\biniciarTemporizador\b', 'startTimer'),
    (r'\bpararTemporizador\b', 'stopTimer'),
    (r'\bpausarTemporizador\b', 'pauseTimer'),
    (r'\bcontinuarTemporizador\b', 'resumeTimer'),
    (r'\bactualizarTemporizador\b', 'updateTimer'),
    (r'\bmanejarTiempoRestante\b', 'handleRemainingTime'),
    (r'\bmanejarTiempoExpirado\b', 'handleTimeExpired'),
    (r'\bcrearElemento\b', 'createElement'),
    (r'\bcrearBoton\b', 'createButton'),
    (r'\bcrearTarjeta\b', 'createCard'),
    (r'\bcrearFila\b', 'createRow'),
    (r'\bcrearColumna\b', 'createColumn'),
    (r'\bcrearSlot\b', 'createSlot'),
    (r'\bcrearOpcion\b', 'createOption'),
    (r'\bcrearPaso\b', 'createStep'),
    (r'\bcrearItem\b', 'createItem'),
    (r'\beliminarElemento\b', 'removeElement'),
    (r'\beliminarBoton\b', 'removeButton'),
    (r'\beliminarTarjeta\b', 'removeCard'),
    (r'\beliminarFila\b', 'removeRow'),
    (r'\beliminarColumna\b', 'removeColumn'),
    (r'\beliminarSlot\b', 'removeSlot'),
    (r'\beliminarOpcion\b', 'removeOption'),
    (r'\beliminarItem\b', 'removeItem'),
    (r'\bactualizarElemento\b', 'updateElement'),
    (r'\bactualizarBoton\b', 'updateButton'),
    (r'\bactualizarTarjeta\b', 'updateCard'),
    (r'\bactualizarFila\b', 'updateRow'),
    (r'\bactualizarSlot\b', 'updateSlot'),
    (r'\bactualizarOpcion\b', 'updateOption'),
    (r'\bactualizarItem\b', 'updateItem'),
    (r'\bactualizarProgreso\b', 'updateProgress'),
    (r'\bactualizarEstado\b', 'updateState'),
    (r'\bactualizarPuntuacion\b', 'updateScore'),
    (r'\bactualizarEstrellas\b', 'updateStars'),
    (r'\bactualizarFeedback\b', 'updateFeedback'),
    (r'\bactualizarMensaje\b', 'updateMessage'),
    (r'\bactualizarPantalla\b', 'updateScreen'),
    (r'\bactualizarVista\b', 'updateView'),
    (r'\bvalidarRespuesta\b', 'validateAnswer'),
    (r'\bvalidarInput\b', 'validateInput'),
    (r'\bvalidarNivel\b', 'validateLevel'),
    (r'\bvalidarDificultad\b', 'validateDifficulty'),
    (r'\bvalidarConfig\b', 'validateConfig'),
    (r'\baplicarEstilo\b', 'applyStyle'),
    (r'\baplicarClase\b', 'applyClass'),
    (r'\baplicarAnimacion\b', 'applyAnimation'),
    (r'\bremoverEstilo\b', 'removeStyle'),
    (r'\bremoverClase\b', 'removeClass'),
    (r'\bremoverAnimacion\b', 'removeAnimation'),
    (r'\b toggleClase\b', 'toggleClass'),
    (r'\bhayError\b', 'hasError'),
    (r'\bhayExito\b', 'hasSuccess'),
    (r'\bhintShown\b', 'hintShown'),
    (r'\bshowingHint\b', 'showingHint'),
    (r'\bexplanationShown\b', 'explanationShown'),
    (r'\bshowingExplanation\b', 'showingExplanation'),
]


def process_file(filepath):
    """Process a single file, replacing Spanish identifiers with English."""
    if not filepath.endswith(('.js', '.html', '.css')):
        return False
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (IOError, UnicodeDecodeError):
        return False
    
    original = content
    changes = 0
    
    for pattern, replacement in REPLACEMENTS:
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            content = new_content
            changes += n
    
    if content != original:
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            return changes
        except IOError:
            return False
    return 0


def main():
    total_changes = 0
    files_processed = 0
    files_changed = 0
    
    for root, dirs, files in os.walk(TOOLS_DIR):
        for fname in files:
            if not fname.endswith(('.js', '.html', '.css')):
                continue
            fpath = os.path.join(root, fname)
            n = process_file(fpath)
            files_processed += 1
            if n:
                files_changed += 1
                total_changes += n
                print(f"[{n:3d}x] {fpath}")
    
    print(f"\nDone: {files_processed} files processed, {files_changed} changed, {total_changes} total replacements.")


if __name__ == '__main__':
    main()
