/* ============================================================
   Datos: Círculo de Confianza.
   Formato: DATA.es / DATA.en, cada uno con:
   { porRonda, niveles: [{ id, nombre, descripcion, estrellas,
     items: [{ picto, situacion, opciones: string[3], correcta,
     pista, explicacion }] }] }
   A diferencia de "Entre Amigos", aquí pista/explicacion son por
   caso (como en social-safety), porque cada situación necesita su
   propia pista, no una genérica reutilizada.
   Progresión (regla 13, un solo cambio por nivel): nivel 1→2 se
   mantiene en "clasificar la relación" (amigo/compañero/conocido)
   y solo introduce casos más sutiles. Nivel 2→3 cambia de tarea
   (clasificar → elegir la respuesta sana ante manipulación
   general). Nivel 3→4 se mantiene en "reconocer manipulación" y
   solo concreta el tema en la petición de dinero.
   Para ampliar: añadir items al array del nivel correspondiente,
   en los dos idiomas. app.js usa DATA[App.i18n.locale()] || DATA.es.
   ============================================================ */
const DATA = {
  es: {
    porRonda: 8,
    niveles: [
      {
        id: 1,
        nombre: 'Nivel 1',
        descripcion: '¿Amigo, compañero o conocido?',
        estrellas: 1,
        items: [
          { picto: '🚌', situacion: 'Ves a esta persona cada día en el autobús, pero no sabéis vuestros nombres.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Sabéis vuestros nombres? ¿Habéis hablado alguna vez?', explicacion: '✅ Es un conocido: lo ves a menudo, pero no tenéis confianza ni conversación.' },
          { picto: '🎉', situacion: 'Quedáis todos los fines de semana, os contáis secretos y os ayudáis siempre.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Cuánto tiempo pasáis juntos? ¿Os contáis cosas importantes?', explicacion: '✅ Es un amigo: hay confianza, tiempo compartido y apoyo mutuo.' },
          { picto: '🏭', situacion: 'Trabajáis juntos en el taller, pero no quedáis fuera del trabajo.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Compartís solo el trabajo, o también vuestro tiempo libre?', explicacion: '✅ Es un compañero: compartís una actividad, pero no una amistad cercana.' },
          { picto: '🏫', situacion: 'Vais a la misma clase de manualidades, os saludáis pero no habéis quedado nunca fuera.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Le contarías un problema personal a esta persona?', explicacion: '✅ Es un compañero: compartís una actividad, pero aún no hay amistad cercana.' },
          { picto: '🎂', situacion: 'Esta persona se acuerda de tu cumpleaños, te escucha y confías en ella desde hace años.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Cuánto tiempo llevas conociendo a esta persona? ¿Confías en ella?', explicacion: '✅ Es un amigo: hay confianza y cariño construidos con el tiempo.' },
          { picto: '🛒', situacion: 'El dependiente de la tienda te saluda siempre, pero solo habláis del pedido.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Habláis de algo más que del motivo por el que os veis?', explicacion: '✅ Es un conocido: hay trato amable, pero no una relación cercana.' },
          { picto: '🏋️', situacion: 'Vais al mismo gimnasio, os animáis en los ejercicios, pero no os habéis visto fuera.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Es una relación solo dentro de esta actividad, o también fuera?', explicacion: '✅ Es un compañero: compartís una actividad y buen trato, pero no es amistad todavía.' },
          { picto: '📱', situacion: 'Hace un año que sois amigos, os escribís cada día y os ayudáis en los problemas.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Cuánto os conocéis y cuánto os apoyáis?', explicacion: '✅ Es un amigo: tiempo, confianza y apoyo mutuo lo confirman.' },
          { picto: '🚏', situacion: 'Una persona te saluda cada mañana en la parada del bus, pero no sabes nada más de ella.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Qué sabes realmente de esta persona?', explicacion: '✅ Es un conocido: solo un saludo, sin conversación ni confianza.' },
          { picto: '🎨', situacion: 'En el taller de pintura os ayudáis con los materiales, pero cada uno se va a su casa.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿La relación termina cuando acaba la actividad?', explicacion: '✅ Es un compañero: compartís la actividad, no vuestro tiempo libre.' },
          { picto: '🤗', situacion: 'Esta persona te defiende, te escucha y tú harías lo mismo por ella.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Confías en ella y ella en ti?', explicacion: '✅ Es un amigo: hay confianza y apoyo en los dos sentidos.' },
          { picto: '🧑‍🍳', situacion: 'El cocinero del comedor te conoce de vista y te saluda, pero no habláis de nada más.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Es una relación cercana o solo un saludo del día a día?', explicacion: '✅ Es un conocido: trato cordial sin confianza real.' },
          { picto: '🧑‍🌾', situacion: 'Ayudáis juntos en el huerto comunitario cada semana, pero no os habéis visto nunca fuera de allí.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Vuestra relación existe fuera del huerto?', explicacion: '✅ Es un compañero: compartís una actividad, no vuestro tiempo libre.' },
          { picto: '🎈', situacion: 'Esta persona te ha ayudado en un mal momento sin pedir nada a cambio y confías en ella de verdad.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Te ha ayudado sin esperar nada a cambio?', explicacion: '✅ Es un amigo: ayuda desinteresada y confianza real.' },
          { picto: '🚉', situacion: 'Coincides con esta persona cada mañana en el tren y os saludáis, pero no sabéis nada más el uno del otro.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Sabéis algo más el uno del otro además de veros?', explicacion: '✅ Es un conocido: un saludo diario, sin conversación de verdad.' },
          { picto: '🎻', situacion: 'Ensayáis juntos en la orquesta cada semana, pero cada uno se va a su casa al terminar.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Termina la relación cuando acaba el ensayo?', explicacion: '✅ Es un compañero: compartís la actividad, no el tiempo libre.' }
        ]
      },
      {
        id: 2,
        nombre: 'Nivel 2',
        descripcion: 'Casos más difíciles de distinguir',
        estrellas: 2,
        items: [
          { picto: '📚', situacion: 'Lleváis dos cursos en la misma clase y os prestáis apuntes, pero nunca habláis de vuestra vida fuera de clase.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Habláis solo de clase, o también de vuestra vida?', explicacion: '✅ Es un compañero: mucho tiempo compartido, pero sin confianza personal.' },
          { picto: '🎊', situacion: 'Os conocisteis ayer en una fiesta y esa persona ya dice que sois mejores amigos.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Cuánto tiempo hace que os conocéis de verdad?', explicacion: '✅ Todavía es un conocido: la amistad de verdad se construye con tiempo, no se declara en un día.' },
          { picto: '🏠', situacion: 'Compartís piso, os repartís las tareas, pero cada uno tiene su vida y apenas habláis de sentimientos.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Compartir casa significa siempre ser amigos?', explicacion: '✅ Es un compañero de piso: convivir no es lo mismo que tener una amistad cercana.' },
          { picto: '👵', situacion: 'Es la vecina de toda la vida, te ayuda si lo necesitas y confías en ella, aunque no quedáis para salir.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Hay confianza y ayuda real, aunque no salgáis juntos?', explicacion: '✅ Es una amiga: la confianza y el cuidado importan más que salir juntos.' },
          { picto: '💬', situacion: 'Habláis por el chat del trabajo cada día de cosas graciosas, pero nunca de temas personales.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿De qué habláis normalmente: solo del trabajo o también de vuestra vida?', explicacion: '✅ Es un compañero: buena relación de trabajo, todavía no amistad cercana.' },
          { picto: '🧳', situacion: 'Esta persona solo te escribe cuando necesita un favor, y luego desaparece semanas.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿La relación es igual de constante en los dos sentidos?', explicacion: '✅ Es un conocido: la amistad de verdad no aparece solo cuando conviene.' },
          { picto: '🏥', situacion: 'Fue tu compañera de habitación en el hospital una semana, os contasteis vuestras preocupaciones y seguís escribiéndoos.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Compartisteis algo importante, aunque el tiempo fuera corto?', explicacion: '✅ Es una amiga: la confianza importa más que el tiempo que hayáis pasado juntos.' },
          { picto: '🎮', situacion: 'Jugáis online cada semana, os ayudáis en el juego, pero no sabéis casi nada de la vida del otro.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Os conocéis de verdad, o solo dentro del juego?', explicacion: '✅ Es un compañero de juego: compartís una afición, no necesariamente confianza personal.' },
          { picto: '🚕', situacion: 'El taxista que te lleva cada semana al centro te pregunta por tu familia y se acuerda de tu nombre.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Le contarías un problema personal a esta persona?', explicacion: '✅ Es un conocido amable: buen trato, pero no confianza cercana.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'Discutisteis hace tiempo, pero seguís hablando con confianza y os ayudáis cuando hace falta.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Una discusión borra la confianza y el cariño que ya existían?', explicacion: '✅ Sigue siendo tu amigo: discutir alguna vez no borra una amistad real.' },
          { picto: '🎓', situacion: 'Es tu tutor o tutora en el centro, te apoya, pero la relación es siempre profesional.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Es una relación de igual a igual, o de apoyo profesional?', explicacion: '✅ Es una relación de apoyo profesional, más parecida a un conocido cercano que a una amistad.' },
          { picto: '👥', situacion: 'Sois compañeros de equipo en el deporte, os animáis en los partidos, pero no quedáis fuera de los entrenamientos.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Vuestra relación existe también fuera del equipo?', explicacion: '✅ Es un compañero de equipo: buen ambiente dentro del deporte, sin amistad fuera de él.' },
          { picto: '📦', situacion: 'Un vecino te ayuda a subir la compra cuando te ve, pero nunca habláis de otra cosa.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Habláis de algo más que de favores puntuales?', explicacion: '✅ Es un conocido: buena vecindad, sin una relación cercana.' },
          { picto: '🎬', situacion: 'Vais juntos al cine cada semana desde hace años y os contáis vuestros problemas.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 0, pista: '🤔 ¿Os contáis cosas importantes desde hace tiempo?', explicacion: '✅ Es un amigo: tiempo compartido y confianza real.' },
          { picto: '🧑‍🔧', situacion: 'El técnico que arregla tu ordenador es simpático y te pregunta qué tal estás, pero solo os veis quince minutos al año.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 2, pista: '🤔 ¿Os veis lo suficiente para tener confianza real?', explicacion: '✅ Es un conocido: trato amable, pero muy poco tiempo compartido.' },
          { picto: '🏊', situacion: 'Entrenáis juntos en el equipo de natación, os animáis mucho, pero nunca quedáis fuera de la piscina.', opciones: ['Amigo', 'Compañero', 'Conocido'], correcta: 1, pista: '🤔 ¿Existe la relación fuera del entrenamiento?', explicacion: '✅ Es un compañero de equipo: buen ambiente dentro del deporte, no fuera.' }
        ]
      },
      {
        id: 3,
        nombre: 'Nivel 3',
        descripcion: 'Reconoce la manipulación',
        estrellas: 3,
        items: [
          { picto: '🤫', situacion: 'Un compañero nuevo te pide que no cuentes a tu familia que quedáis, “para que sea nuestro secreto”.', opciones: ['Se lo cuento a mi familia igualmente', 'Guardo el secreto para no perderlo como amigo', 'Le pido que no me lo vuelva a pedir pero no digo nada'], correcta: 0, pista: '🤔 ¿Una amistad de verdad te pide que escondas cosas a tu familia?', explicacion: '✅ Pedir secretos a tu familia es una señal de manipulación. Una amistad real no necesita esconderse.' },
          { picto: '😢', situacion: 'Una persona te dice: “Si de verdad fueras mi amigo, dejarías de quedar con tus otros amigos para estar solo conmigo”.', opciones: ['Le digo que puedo tener varios amigos a la vez', 'Dejo de quedar con los demás para no hacerle sentir mal', 'Quedo con los demás a escondidas'], correcta: 0, pista: '🤔 ¿Un amigo de verdad te pide que dejes a las demás personas que quieres?', explicacion: '✅ Aislarte de otras personas es una señal de manipulación. Un amigo de verdad no te obliga a elegir.' },
          { picto: '🎁', situacion: 'Un conocido te hace muchos regalos y después te pide que hagas algo que no quieres hacer “porque se lo debes”.', opciones: ['Le digo que un regalo no me obliga a nada', 'Hago lo que pide porque me hizo regalos', 'Le devuelvo los regalos sin decir nada'], correcta: 0, pista: '🤔 ¿Un regalo te obliga a hacer algo que no quieres?', explicacion: '✅ Nadie te compra con regalos. Un regalo nunca obliga a devolver un favor que no quieres hacer.' },
          { picto: '😠', situacion: 'Cuando no haces lo que un “amigo” quiere, se enfada mucho y deja de hablarte varios días para castigarte.', opciones: ['Hablo con calma de cómo me hace sentir esa actitud', 'Hago siempre lo que quiere para que no se enfade', 'Le ignoro también, sin decir nada'], correcta: 0, pista: '🤔 ¿Es sano que alguien te castigue con silencio cuando no haces lo que quiere?', explicacion: '✅ Castigar con el silencio para conseguir algo es manipulación. Hablar con calma es la respuesta sana.' },
          { picto: '🙅', situacion: 'Un compañero se burla de ti delante de otras personas y luego dice “era solo una broma, no te enfades”.', opciones: ['Le digo que eso me ha dolido de verdad', 'Me río también para que no note que me ha molestado', 'Me alejo de todo el grupo para siempre'], correcta: 0, pista: '🤔 ¿Decir “era broma” borra que algo te haya dolido de verdad?', explicacion: '✅ Puedes decir que algo te dolió aunque la otra persona diga que era broma. Tus sentimientos importan.' },
          { picto: '👀', situacion: 'Una persona que dice ser tu amiga habla mal de ti a tus espaldas, pero delante de ti es muy simpática.', opciones: ['Hablo con ella sobre lo que he oído', 'No digo nada para no tener un conflicto', 'Hablo mal de ella también a sus espaldas'], correcta: 0, pista: '🤔 ¿Un amigo de verdad habla mal de ti cuando no estás?', explicacion: '✅ Hablar con la persona directamente es lo sano. Una amistad de verdad no tiene dobles caras.' },
          { picto: '🏆', situacion: 'Un conocido te dice que “todo el mundo” ya ha hecho algo peligroso y que tú deberías hacerlo también para encajar.', opciones: ['Decido por mí mismo/a, sin dejarme llevar por lo que hagan otros', 'Lo hago para que no piensen que soy diferente', 'Digo que sí, pero luego no lo hago'], correcta: 0, pista: '🤔 ¿Que otras personas hagan algo significa que tú también debes hacerlo?', explicacion: '✅ Decidir por ti mismo/a, sin presión de grupo, es la respuesta sana. Tú eliges lo que haces.' },
          { picto: '💔', situacion: 'Un “amigo” solo te busca cuando necesita algo de ti, y desaparece el resto del tiempo.', opciones: ['Me doy cuenta de que no es una amistad igualada y hablo de ello', 'Sigo ayudando siempre, aunque él no esté cuando lo necesito yo', 'Dejo de ayudarle sin explicarle por qué'], correcta: 0, pista: '🤔 ¿Una amistad de verdad va en los dos sentidos?', explicacion: '✅ La amistad sana se ayuda en los dos sentidos. Darte cuenta y hablarlo es lo correcto.' },
          { picto: '🚪', situacion: 'Una persona insiste mucho en saber dónde vives y con quién, aunque hace poco que os conocéis.', opciones: ['No doy esos datos todavía, la confianza se construye con tiempo', 'Se lo cuento todo para que confíe en mí', 'Le doy datos falsos sin decir nada'], correcta: 0, pista: '🤔 ¿Hace falta compartir todo enseguida para que alguien confíe en ti?', explicacion: '✅ La confianza se construye poco a poco. No hay que compartir datos personales solo porque alguien insista.' },
          { picto: '😔', situacion: 'Cuando dices que no quieres hacer algo, un compañero te dice “pues entonces ya no somos amigos”.', opciones: ['Mantengo mi decisión: un no también es válido entre amigos', 'Cambio de opinión para no perder la amistad', 'Digo que sí, pero luego no lo hago'], correcta: 0, pista: '🤔 ¿Una amistad de verdad se rompe porque digas que no una vez?', explicacion: '✅ Un amigo de verdad respeta un no. Amenazar con romper la amistad es una forma de presión.' },
          { picto: '🕵️', situacion: 'Una persona que casi no conoces te pide usar tu nombre para pedir cosas o hacer gestiones “solo por esta vez”.', opciones: ['Digo que no: no presto mis datos a alguien que apenas conozco', 'Lo hago porque insiste mucho', 'Lo hago solo si me promete que es la última vez'], correcta: 0, pista: '🤔 ¿Conocer a alguien desde hace poco es motivo suficiente para prestarle tus datos?', explicacion: '✅ No prestes tu nombre ni tus datos a alguien que apenas conoces, aunque insista.' },
          { picto: '🤝', situacion: 'No sabes si una persona es un amigo de verdad o solo se está aprovechando de ti.', opciones: ['Hablo con una persona de confianza para verlo con más claridad', 'Sigo como si no pasara nada, para no equivocarme', 'Corto el contacto sin hablarlo con nadie'], correcta: 0, pista: '🤔 ¿Tienes que decidir esto completamente solo/a?', explicacion: '✅ Hablarlo con una persona de confianza (familia, un profesional) siempre ayuda a ver la situación con más claridad.' },
          { picto: '🎭', situacion: 'Un compañero finge estar de acuerdo contigo delante de otros, pero luego hace lo contrario a tus espaldas.', opciones: ['Le digo cómo me hace sentir esa doble cara', 'Finjo que no me he dado cuenta', 'Hago lo mismo con él a escondidas'], correcta: 0, pista: '🤔 ¿Una amistad de verdad actúa igual delante y detrás?', explicacion: '✅ Actuar distinto delante y detrás es una señal de manipulación. Hablarlo con calma es lo sano.' },
          { picto: '📵', situacion: 'Un conocido se enfada si tardas en responder a sus mensajes y te exige contestar al momento.', opciones: ['Le digo que necesito mi tiempo para responder', 'Contesto al instante siempre para que no se enfade', 'Dejo de mirar el móvil para evitarlo'], correcta: 0, pista: '🤔 ¿Una amistad sana exige respuesta inmediata siempre?', explicacion: '✅ Exigir respuesta inmediata es una forma de control. Tienes derecho a tu propio tiempo.' },
          { picto: '🎯', situacion: 'Un compañero te dice que solo serás su amigo de verdad si dejas de juntarte con cierta persona.', opciones: ['Le digo que decido yo con quién me junto', 'Dejo de juntarme con esa persona para tenerlo contento', 'Me junto a escondidas para que no lo sepa'], correcta: 0, pista: '🤔 ¿Una amistad de verdad decide con quién más te juntas?', explicacion: '✅ Decidir tus amistades es cosa tuya. Pedirte que dejes a alguien es una señal de manipulación.' },
          { picto: '💸', situacion: 'Un conocido te dice que le debes un favor por algo que hizo hace tiempo sin que tú se lo pidieras.', opciones: ['Le digo que un favor no pedido no genera una deuda', 'Hago lo que pide para saldar la deuda', 'Le devuelvo el favor sin pensarlo'], correcta: 0, pista: '🤔 ¿Un favor que no pediste te obliga a algo?', explicacion: '✅ Nadie te puede cobrar un favor que no pediste. Eso es manipulación.' }
        ]
      },
      {
        id: 4,
        nombre: 'Nivel 4',
        descripcion: 'Te pide dinero',
        estrellas: 4,
        items: [
          { picto: '💶', situacion: 'Un compañero que conoces desde hace poco te pide que le prestes dinero “solo por esta semana”.', opciones: ['Le digo que no y que lo hable con su familia', 'Le presto el dinero porque parece buena persona', 'Le presto la mitad para quedar bien'], correcta: 0, pista: '🤔 ¿Cuánto tiempo hace que conoces a esta persona de verdad?', explicacion: '✅ No prestes dinero a alguien que conoces desde hace poco. Pide ayuda a tu familia si insiste.' },
          { picto: '🎁', situacion: 'Una persona te hace regalos y después te pide dinero “para devolverte el favor en otra cosa”.', opciones: ['Le digo que no acepto ese trato', 'Le doy el dinero porque me hizo regalos', 'Le pido que primero me diga cuánto necesita'], correcta: 0, pista: '🤔 ¿Un regalo de verdad pide algo a cambio?', explicacion: '✅ Un regalo de verdad no pide nada a cambio. Pedir dinero después es una señal de manipulación.' },
          { picto: '😢', situacion: 'Un “amigo” te cuenta una emergencia triste y te pide dinero rápido, “sin contárselo a nadie”.', opciones: ['Hablo primero con mi familia antes de dar nada', 'Le doy el dinero rápido porque suena urgente', 'Le doy solo un poco para que no se enfade'], correcta: 0, pista: '🤔 ¿Por qué pide que no se lo cuentes a nadie?', explicacion: '✅ Pedir dinero con prisa y en secreto es una señal de alarma. Habla siempre con tu familia antes de dar dinero.' },
          { picto: '📱', situacion: 'Una persona que conociste hace unos días por internet te pide dinero para “poder venir a conocerte en persona”.', opciones: ['No mando dinero a alguien que apenas conozco', 'Mando el dinero porque quiero conocerle', 'Mando solo una parte pequeña'], correcta: 0, pista: '🤔 ¿Conocer a alguien hace pocos días es suficiente para confiar en él con tu dinero?', explicacion: '✅ No mandes dinero a alguien que apenas conoces, aunque prometa venir a verte.' },
          { picto: '💳', situacion: 'Un conocido te pide que le dejes usar tu tarjeta “solo un momento” para comprar algo online.', opciones: ['Le digo que mi tarjeta es solo mía y no la presto', 'Se la dejo porque insiste mucho', 'Le doy el número pero no la tarjeta física'], correcta: 0, pista: '🤔 ¿Tu tarjeta es algo que se puede prestar como un boli?', explicacion: '✅ La tarjeta y el dinero son tuyos. No se prestan ni se dan los datos a otra persona, aunque insista.' },
          { picto: '🏦', situacion: 'Alguien te dice: “Si fueras mi amigo de verdad, me ayudarías con dinero cuando lo necesito”.', opciones: ['Le digo que la amistad no se mide con dinero', 'Le doy dinero para demostrar que soy su amigo', 'Le presto dinero solo esta vez, para probar'], correcta: 0, pista: '🤔 ¿La amistad de verdad se demuestra dando dinero?', explicacion: '✅ Quien te quiere de verdad no te pide dinero para demostrar la amistad: te ayuda sin pedir nada a cambio.' },
          { picto: '🎰', situacion: 'Un compañero te pide dinero varias veces seguidas para “un negocio genial” que promete devolverte el doble.', opciones: ['Le digo que no y hablo con mi familia sobre lo que ha pasado', 'Le doy el dinero porque promete devolverlo con más', 'Le doy dinero cada vez que me lo pide para no discutir'], correcta: 0, pista: '🤔 ¿Es normal que alguien pida dinero una y otra vez con la misma excusa?', explicacion: '✅ Pedir dinero repetidamente con promesas grandes es una señal de alarma. Habla con tu familia y no sigas dando dinero.' },
          { picto: '🐾', situacion: 'Alguien te enseña fotos tristes de animales y te pide dinero directamente a su cuenta personal “para ayudarlos”.', opciones: ['Si quiero ayudar, lo hago a través de una protectora de verdad, con mi familia', 'Le doy el dinero directamente porque me da pena', 'Le pido más fotos antes de decidir'], correcta: 0, pista: '🤔 ¿El dinero va a una organización de verdad o a una persona directamente?', explicacion: '✅ Para ayudar de verdad, hazlo a través de una organización conocida y con tu familia, no dando dinero directamente a una persona.' },
          { picto: '👤', situacion: 'Una persona que acabas de conocer te dice que tenéis “una conexión especial” y te pide dinero prestado.', opciones: ['Le digo que no: la confianza con el dinero se gana con tiempo', 'Le presto el dinero porque siento esa conexión', 'Le presto una pequeña cantidad para ver qué pasa'], correcta: 0, pista: '🤔 ¿Sentir una conexión rápida significa que puedes confiarle tu dinero?', explicacion: '✅ Una conexión rápida no es motivo para prestar dinero. La confianza real necesita tiempo.' },
          { picto: '⏰', situacion: 'Un “amigo” te dice que necesita el dinero “ahora mismo o será demasiado tarde” y que no hay tiempo para preguntar a nadie.', opciones: ['Justo por eso hablo primero con una persona de confianza', 'Le doy el dinero rápido porque no hay tiempo', 'Le pido que espere solo cinco minutos'], correcta: 0, pista: '🤔 ¿Por qué no quiere que preguntes a nadie antes de decidir?', explicacion: '✅ La prisa y no dejar que preguntes a nadie es una señal clara de manipulación. Habla siempre con una persona de confianza antes de dar dinero.' },
          { picto: '🎓', situacion: 'Un conocido del centro te pide dinero para “una cuota especial” y te enseña un papel que no sabes explicar bien.', opciones: ['Pregunto a una persona de confianza antes de dar nada', 'Pago porque el papel parece oficial', 'Pago solo la mitad por si acaso'], correcta: 0, pista: '🤔 ¿Entiendes bien para qué es exactamente ese dinero?', explicacion: '✅ Si no entiendes bien para qué es el dinero, pregunta antes a una persona de confianza. No pagues solo porque algo parezca oficial.' },
          { picto: '💚', situacion: 'Tienes un problema de verdad y una amiga de toda la vida te ayuda sin pedirte nada a cambio.', opciones: ['Acepto su ayuda y se lo agradezco: así es una amistad de verdad', 'Le digo que no necesito ayuda de nadie', 'Le pido que me preste dinero también, aprovechando'], correcta: 0, pista: '🤔 ¿Cómo actúa alguien que te quiere de verdad cuando tienes un problema?', explicacion: '✅ Quien te quiere de verdad te ayuda sin pedir nada a cambio. Aceptar esa ayuda con agradecimiento está bien.' },
          { picto: '📲', situacion: 'Un conocido de una app de citas te pide dinero para "un billete de avión" para venir a verte.', opciones: ['No mando dinero a alguien que apenas conozco', 'Mando el dinero porque promete venir', 'Mando solo una parte pequeña'], correcta: 0, pista: '🤔 ¿Conocer a alguien por una app es motivo para prestarle dinero?', explicacion: '✅ No mandes dinero a alguien que apenas conoces, venga de donde venga el contacto.' },
          { picto: '🎓', situacion: 'Un compañero de clase te pide dinero prestado cada semana y nunca te lo devuelve.', opciones: ['Le digo que no puedo seguir prestándole dinero', 'Se lo sigo prestando para no quedar mal', 'Se lo presto pero me enfado por dentro'], correcta: 0, pista: '🤔 ¿Es sano prestar dinero que nunca se devuelve?', explicacion: '✅ Puedes decir que no. Prestar dinero que nunca vuelve no es sano ni justo.' },
          { picto: '🏠', situacion: 'Alguien te pide que le dejes vivir en tu casa "solo unos días" y a cambio te promete dinero que nunca llega.', opciones: ['Hablo primero con mi familia antes de decidir algo así', 'Le dejo quedarse porque promete pagar', 'Le dejo quedarse sin decírselo a nadie'], correcta: 0, pista: '🤔 ¿Una decisión así se toma sin hablarlo con nadie?', explicacion: '✅ Decisiones grandes como esta se hablan primero con la familia o una persona de confianza.' },
          { picto: '🃏', situacion: 'Un conocido te invita a apostar dinero prometiendo que siempre se gana.', opciones: ['Le digo que no y hablo con mi familia si insiste', 'Apuesto un poco para probar', 'Le presto dinero para que apueste él'], correcta: 0, pista: '🤔 ¿Existe alguna apuesta en la que siempre se gana?', explicacion: '✅ Nadie gana siempre apostando. Es mejor decir que no y hablarlo con tu familia.' }
        ]
      }
    ]
  },
  en: {
    porRonda: 8,
    niveles: [
      {
        id: 1,
        nombre: 'Level 1',
        descripcion: 'Friend, companion or acquaintance?',
        estrellas: 1,
        items: [
          { picto: '🚌', situacion: "You see this person every day on the bus, but you do not know each other's names.", opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: "Do you know each other's names? Have you ever talked?", explicacion: 'This is an acquaintance: you see them often, but there is no trust or conversation.' },
          { picto: '🎉', situacion: 'You hang out every weekend, share secrets, and always help each other.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'How much time do you spend together? Do you share important things?', explicacion: 'This is a friend: there is trust, shared time and mutual support.' },
          { picto: '🏭', situacion: 'You work together at the workshop, but you do not meet up outside work.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Do you only share work, or also your free time?', explicacion: 'This is a companion: you share an activity, but not a close friendship.' },
          { picto: '🏫', situacion: 'You go to the same craft class, you say hello but have never met up outside it.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Would you tell this person a personal problem?', explicacion: 'This is a companion: you share an activity, but there is no close friendship yet.' },
          { picto: '🎂', situacion: 'This person remembers your birthday, listens to you, and you have trusted them for years.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'How long have you known this person? Do you trust them?', explicacion: 'This is a friend: trust and care built up over time.' },
          { picto: '🛒', situacion: 'The shop assistant always greets you, but you only talk about your order.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Do you talk about anything besides the reason you see each other?', explicacion: 'This is an acquaintance: friendly treatment, but not a close relationship.' },
          { picto: '🏋️', situacion: 'You go to the same gym and cheer each other on, but have not seen each other outside it.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does this relationship exist only inside this activity, or outside it too?', explicacion: 'This is a companion: you share an activity and get along well, but it is not friendship yet.' },
          { picto: '📱', situacion: "You have been friends for a year, you message every day and help each other with problems.", opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'How well do you know each other, and how much do you support each other?', explicacion: 'This is a friend: time, trust and mutual support confirm it.' },
          { picto: '🚏', situacion: 'Someone greets you every morning at the bus stop, but you do not know anything else about them.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'What do you actually know about this person?', explicacion: 'This is an acquaintance: just a greeting, no conversation or trust.' },
          { picto: '🎨', situacion: 'At the painting class you help each other with materials, but each of you goes home separately.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does the relationship end when the activity ends?', explicacion: 'This is a companion: you share the activity, not your free time.' },
          { picto: '🤗', situacion: 'This person stands up for you, listens to you, and you would do the same for them.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Do you trust each other?', explicacion: 'This is a friend: trust and support go both ways.' },
          { picto: '🧑‍🍳', situacion: "The canteen cook recognizes you and says hello, but you do not talk about anything else.", opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Is this a close relationship, or just a daily greeting?', explicacion: 'This is an acquaintance: friendly treatment without real trust.' },
          { picto: '🧑‍🌾', situacion: 'You help together in the community garden every week, but you have never met outside it.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does your relationship exist outside the garden?', explicacion: 'This is a companion: you share an activity, not your free time.' },
          { picto: '🎈', situacion: 'This person helped you through a hard time without asking for anything back, and you truly trust them.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Did they help you without expecting anything back?', explicacion: 'This is a friend: selfless help and real trust.' },
          { picto: '🚉', situacion: 'You see this person every morning on the train and say hello, but you know nothing else about each other.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Do you know anything else about each other besides seeing each other?', explicacion: 'This is an acquaintance: a daily greeting, no real conversation.' },
          { picto: '🎻', situacion: 'You rehearse together in the orchestra every week, but each of you goes home afterward.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does the relationship end when rehearsal ends?', explicacion: 'This is a companion: you share the activity, not your free time.' }
        ]
      },
      {
        id: 2,
        nombre: 'Level 2',
        descripcion: 'Harder cases to tell apart',
        estrellas: 2,
        items: [
          { picto: '📚', situacion: 'You have shared a class for two years and lend each other notes, but never talk about life outside school.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Do you only talk about class, or also about your lives?', explicacion: 'This is a companion: lots of shared time, but no personal trust.' },
          { picto: '🎊', situacion: 'You met yesterday at a party and this person already says you are best friends.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'How long have you actually known each other?', explicacion: 'This is still an acquaintance: real friendship is built over time, not declared in a day.' },
          { picto: '🏠', situacion: 'You share a flat and split the chores, but each has their own life and you rarely talk about feelings.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does sharing a home always mean being friends?', explicacion: 'This is a flatmate: living together is not the same as a close friendship.' },
          { picto: '👵', situacion: 'She is your lifelong neighbor, she helps you if you need it and you trust her, even though you do not go out together.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Is there real trust and help, even without going out together?', explicacion: 'She is a friend: trust and care matter more than going out together.' },
          { picto: '💬', situacion: 'You chat on the work group every day about funny things, but never about personal topics.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'What do you usually talk about: only work, or also your life?', explicacion: 'This is a companion: a good work relationship, not yet a close friendship.' },
          { picto: '🧳', situacion: 'This person only messages you when they need a favor, then disappears for weeks.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Is the relationship just as constant on both sides?', explicacion: 'This is an acquaintance: real friendship does not only show up when convenient.' },
          { picto: '🏥', situacion: 'She was your hospital roommate for a week, you shared your worries and still keep in touch.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Did you share something important, even if the time was short?', explicacion: 'She is a friend: trust matters more than how much time you have spent together.' },
          { picto: '🎮', situacion: "You play online together every week and help each other in the game, but barely know anything about each other's lives.", opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Do you really know each other, or only inside the game?', explicacion: 'This is a gaming companion: you share a hobby, not necessarily personal trust.' },
          { picto: '🚕', situacion: 'The taxi driver who takes you downtown every week asks about your family and remembers your name.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Would you tell this person a personal problem?', explicacion: 'This is a friendly acquaintance: good treatment, but not close trust.' },
          { picto: '🧑‍🤝‍🧑', situacion: 'You argued a while ago, but you still talk with trust and help each other when needed.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Does one argument erase trust and care that already existed?', explicacion: 'They are still your friend: arguing once does not erase a real friendship.' },
          { picto: '🎓', situacion: 'They are your tutor at the center, they support you, but the relationship is always professional.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Is this an equal relationship, or professional support?', explicacion: 'This is a professional support relationship, closer to a familiar acquaintance than a friendship.' },
          { picto: '👥', situacion: 'You are teammates in sports, you cheer each other on during games, but do not meet up outside training.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does your relationship exist outside the team too?', explicacion: 'This is a teammate: good atmosphere within the sport, no friendship outside it yet.' },
          { picto: '📦', situacion: 'A neighbour helps you carry your shopping when they see you, but you never talk about anything else.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Do you talk about anything besides occasional favours?', explicacion: 'This is an acquaintance: good neighbourliness, without a close relationship.' },
          { picto: '🎬', situacion: 'You have gone to the cinema together every week for years and share your problems.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 0, pista: 'Have you shared important things for a long time?', explicacion: 'This is a friend: shared time and real trust.' },
          { picto: '🧑‍🔧', situacion: 'The technician who fixes your computer is friendly and asks how you are, but you only see each other fifteen minutes a year.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 2, pista: 'Do you see each other enough to build real trust?', explicacion: 'This is an acquaintance: friendly treatment, but very little shared time.' },
          { picto: '🏊', situacion: 'You train together on the swim team and cheer each other on, but never meet outside the pool.', opciones: ['Friend', 'Companion', 'Acquaintance'], correcta: 1, pista: 'Does the relationship exist outside training?', explicacion: 'This is a teammate: good atmosphere within the sport, not outside it.' }
        ]
      },
      {
        id: 3,
        nombre: 'Level 3',
        descripcion: 'Recognize manipulation',
        estrellas: 3,
        items: [
          { picto: '🤫', situacion: 'A new companion asks you not to tell your family that you meet up, "so it can be our secret."', opciones: ['I tell my family anyway', "I keep the secret so I don't lose them as a friend", 'I ask them not to ask again but say nothing else'], correcta: 0, pista: 'Does a real friendship ask you to hide things from your family?', explicacion: "Asking for secrets from your family is a sign of manipulation. A real friendship doesn't need to hide." },
          { picto: '😢', situacion: 'Someone tells you: "If you were really my friend, you would stop hanging out with your other friends to be only with me."', opciones: ['I tell them I can have several friends at once', "I stop seeing the others so I don't upset them", 'I keep seeing the others in secret'], correcta: 0, pista: 'Does a real friend ask you to give up the other people you care about?', explicacion: "Isolating you from other people is a sign of manipulation. A real friend doesn't make you choose." },
          { picto: '🎁', situacion: 'An acquaintance gives you lots of gifts and then asks you to do something you do not want to do "because you owe them."', opciones: ["I tell them a gift doesn't obligate me to anything", 'I do it because they gave me gifts', 'I return the gifts without saying anything'], correcta: 0, pista: 'Does a gift obligate you to do something you do not want to?', explicacion: "Nobody buys you with gifts. A gift never obligates you to return a favor you don't want to do." },
          { picto: '😠', situacion: 'When you do not do what a "friend" wants, they get very angry and stop talking to you for days to punish you.', opciones: ['I calmly talk about how that attitude makes me feel', "I always do what they want so they don't get angry", 'I ignore them too, without saying anything'], correcta: 0, pista: 'Is it healthy for someone to punish you with silence when you do not do what they want?', explicacion: 'Punishing with silence to get something is manipulation. Talking calmly is the healthy answer.' },
          { picto: '🙅', situacion: 'A companion makes fun of you in front of others and then says, "it was just a joke, don\'t get upset."', opciones: ['I tell them it really hurt me', "I laugh along so they don't notice it bothered me", 'I move away from the whole group forever'], correcta: 0, pista: 'Does saying "it was a joke" erase that something really hurt you?', explicacion: 'You can say something hurt you even if the other person calls it a joke. Your feelings matter.' },
          { picto: '👀', situacion: "Someone who says they're your friend talks badly about you behind your back, but is very friendly to your face.", opciones: ["I talk to them about what I've heard", 'I say nothing to avoid a conflict', 'I talk badly about them behind their back too'], correcta: 0, pista: "Does a real friend talk badly about you when you're not there?", explicacion: 'Talking to the person directly is the healthy choice. A real friendship has no double face.' },
          { picto: '🏆', situacion: 'An acquaintance tells you "everyone" has already done something dangerous and that you should do it too, to fit in.', opciones: ['I decide for myself, without being swayed by what others do', "I do it so they don't think I'm different", "I say yes, but then don't do it"], correcta: 0, pista: 'Does other people doing something mean you have to do it too?', explicacion: 'Deciding for yourself, without group pressure, is the healthy answer. You choose what you do.' },
          { picto: '💔', situacion: 'A "friend" only comes to you when they need something, and disappears the rest of the time.', opciones: ["I notice the friendship isn't equal and talk about it", "I keep helping always, even when they're not there when I need them", 'I stop helping them without explaining why'], correcta: 0, pista: 'Does a real friendship go both ways?', explicacion: 'A healthy friendship helps in both directions. Noticing it and talking about it is the right thing to do.' },
          { picto: '🚪', situacion: "Someone insists a lot on knowing where you live and who with, even though you've only just met.", opciones: ["I don't share that yet — trust is built over time", 'I tell them everything so they trust me', 'I give them false details without saying anything'], correcta: 0, pista: 'Do you need to share everything right away for someone to trust you?', explicacion: "Trust is built little by little. You don't have to share personal details just because someone insists." },
          { picto: '😔', situacion: 'When you say you do not want to do something, a companion says, "then we\'re not friends anymore."', opciones: ['I stick to my decision: a no is valid between friends too', "I change my mind so I don't lose the friendship", "I say yes, but then don't do it"], correcta: 0, pista: 'Does a real friendship break because you said no once?', explicacion: 'A real friend respects a no. Threatening to end the friendship is a form of pressure.' },
          { picto: '🕵️', situacion: 'Someone you barely know asks to use your name to request things or run errands "just this once."', opciones: ["I say no — I don't lend my details to someone I barely know", 'I do it because they insist a lot', "I only do it if they promise it's the last time"], correcta: 0, pista: 'Is knowing someone for a short time enough reason to lend them your details?', explicacion: "Don't lend your name or your details to someone you barely know, even if they insist." },
          { picto: '🤝', situacion: "You're not sure if someone is a real friend or just taking advantage of you.", opciones: ['I talk to someone I trust to see it more clearly', "I carry on as if nothing's wrong, so I don't get it wrong", 'I cut contact without talking to anyone about it'], correcta: 0, pista: 'Do you have to decide this completely on your own?', explicacion: 'Talking to someone you trust (family, a professional) always helps you see the situation more clearly.' },
          { picto: '🎭', situacion: 'A companion pretends to agree with you in front of others, but then does the opposite behind your back.', opciones: ['I tell them how that double behaviour makes me feel', 'I pretend I have not noticed', 'I do the same to them in secret'], correcta: 0, pista: 'Does a real friendship act the same in front and behind?', explicacion: 'Acting differently in front and behind is a sign of manipulation. Talking about it calmly is the healthy choice.' },
          { picto: '📵', situacion: 'An acquaintance gets angry if you take time to reply to their messages and demands an instant answer.', opciones: ['I tell them I need my own time to reply', 'I always answer instantly so they do not get angry', 'I stop checking my phone to avoid it'], correcta: 0, pista: 'Does a healthy friendship demand an instant reply always?', explicacion: 'Demanding an instant reply is a form of control. You have a right to your own time.' },
          { picto: '🎯', situacion: 'A companion tells you that you will only be a real friend if you stop hanging out with a certain person.', opciones: ['I tell them I decide who I hang out with', 'I stop seeing that person to keep them happy', 'I keep seeing them in secret so they do not know'], correcta: 0, pista: 'Does a real friendship decide who else you hang out with?', explicacion: 'Choosing your friendships is up to you. Asking you to drop someone is a sign of manipulation.' },
          { picto: '💸', situacion: 'An acquaintance tells you that you owe them a favour for something they did a while ago that you never asked for.', opciones: ['I tell them an unasked favour does not create a debt', 'I do what they ask to settle the debt', 'I return the favour without thinking it over'], correcta: 0, pista: 'Does a favour you did not ask for obligate you to something?', explicacion: 'Nobody can charge you for a favour you did not ask for. That is manipulation.' }
        ]
      },
      {
        id: 4,
        nombre: 'Level 4',
        descripcion: 'They ask you for money',
        estrellas: 4,
        items: [
          { picto: '💶', situacion: 'A companion you have known for a short time asks you to lend them money "just for this week."', opciones: ['I say no and tell them to talk to their family', 'I lend the money because they seem like a good person', 'I lend half to keep things friendly'], correcta: 0, pista: 'How long have you really known this person?', explicacion: "Don't lend money to someone you've known for a short time. Ask your family for help if they insist." },
          { picto: '🎁', situacion: 'Someone gives you gifts and then asks for money "to pay them back another way."', opciones: ["I tell them I don't accept that deal", 'I give them the money because they gave me gifts', 'I ask how much they need first'], correcta: 0, pista: 'Does a real gift ask for something in return?', explicacion: "A real gift doesn't ask for anything in return. Asking for money afterward is a sign of manipulation." },
          { picto: '😢', situacion: 'A "friend" tells you about a sad emergency and asks for money fast, "without telling anyone."', opciones: ['I talk to my family first before giving anything', 'I give the money quickly because it sounds urgent', "I give just a little so they don't get upset"], correcta: 0, pista: 'Why do they ask you not to tell anyone?', explicacion: 'Asking for money urgently and in secret is a warning sign. Always talk to your family before giving money.' },
          { picto: '📱', situacion: 'Someone you met a few days ago online asks for money so they can "come meet you in person."', opciones: ["I don't send money to someone I barely know", 'I send the money because I want to meet them', 'I send just a small part'], correcta: 0, pista: 'Is knowing someone for a few days enough to trust them with your money?', explicacion: "Don't send money to someone you barely know, even if they promise to come see you." },
          { picto: '💳', situacion: 'An acquaintance asks to use your card "just for a moment" to buy something online.', opciones: ["I tell them my card is mine alone and I don't lend it", 'I lend it because they insist a lot', 'I give the number but not the physical card'], correcta: 0, pista: 'Is your card something you can lend like a pen?', explicacion: "Your card and money are yours. They aren't lent or shared with anyone else, no matter how much they insist." },
          { picto: '🏦', situacion: 'Someone tells you: "If you were really my friend, you would help me out with money when I need it."', opciones: ["I tell them friendship isn't measured in money", "I give them money to prove I'm their friend", 'I lend money just this once, to test it out'], correcta: 0, pista: 'Is real friendship proven by giving money?', explicacion: "Someone who truly cares about you doesn't ask for money to prove the friendship: they help without expecting anything back." },
          { picto: '🎰', situacion: 'A companion asks you for money several times in a row for "a great deal" that promises to pay back double.', opciones: ['I say no and talk to my family about what happened', 'I give the money because they promise to pay back more', 'I give money every time they ask, to avoid arguing'], correcta: 0, pista: 'Is it normal for someone to ask for money again and again with the same excuse?', explicacion: 'Asking for money repeatedly with big promises is a warning sign. Talk to your family and stop giving money.' },
          { picto: '🐾', situacion: 'Someone shows you sad photos of animals and asks for money straight to their personal account "to help them."', opciones: ['If I want to help, I do it through a real shelter, with my family', 'I give the money directly because I feel sorry for them', 'I ask for more photos before deciding'], correcta: 0, pista: 'Is the money going to a real organization or straight to a person?', explicacion: 'To really help, do it through a known organization and with your family, not by giving money directly to a person.' },
          { picto: '👤', situacion: 'Someone you just met says you have "a special connection" and asks to borrow money.', opciones: ['I say no: trust with money is earned over time', 'I lend the money because I feel that connection', 'I lend a small amount to see what happens'], correcta: 0, pista: 'Does feeling a quick connection mean you can trust them with your money?', explicacion: 'A quick connection is not a reason to lend money. Real trust needs time.' },
          { picto: '⏰', situacion: 'A "friend" tells you they need the money "right now or it will be too late" and there is no time to ask anyone.', opciones: ["That's exactly why I talk to someone I trust first", "I give the money quickly because there's no time", 'I ask them to wait just five minutes'], correcta: 0, pista: "Why don't they want you to ask anyone before deciding?", explicacion: 'Rushing you and not letting you ask anyone is a clear sign of manipulation. Always talk to someone you trust before giving money.' },
          { picto: '🎓', situacion: 'An acquaintance from the center asks for money for a "special fee" and shows you a paper you can\'t quite explain.', opciones: ['I ask someone I trust before giving anything', 'I pay because the paper looks official', 'I pay just half, just in case'], correcta: 0, pista: 'Do you understand exactly what this money is for?', explicacion: "If you don't understand what the money is for, ask someone you trust first. Don't pay just because something looks official." },
          { picto: '💚', situacion: 'You have a real problem and a lifelong friend helps you without asking for anything in return.', opciones: ["I accept their help and thank them: that's what real friendship looks like", "I tell them I don't need anyone's help", 'I ask them to lend me money too, while I am at it'], correcta: 0, pista: 'How does someone who really cares about you act when you have a problem?', explicacion: 'Someone who truly cares about you helps without asking for anything back. Accepting that help with gratitude is fine.' },
          { picto: '📲', situacion: 'Someone from a dating app asks you for money for "a plane ticket" to come see you.', opciones: ['I do not send money to someone I barely know', 'I send the money because they promise to come', 'I send just a small part'], correcta: 0, pista: 'Is meeting someone through an app a reason to lend them money?', explicacion: 'Do not send money to someone you barely know, wherever the contact came from.' },
          { picto: '🎓', situacion: 'A classmate asks to borrow money from you every week and never pays it back.', opciones: ['I tell them I cannot keep lending them money', 'I keep lending it so I do not look bad', 'I lend it but feel angry inside'], correcta: 0, pista: 'Is it healthy to lend money that is never paid back?', explicacion: 'You can say no. Lending money that never comes back is neither healthy nor fair.' },
          { picto: '🏠', situacion: 'Someone asks to stay at your home "just a few days" in exchange for money that never arrives.', opciones: ['I talk to my family first before deciding something like that', 'I let them stay because they promise to pay', 'I let them stay without telling anyone'], correcta: 0, pista: 'Is a decision like this made without talking to anyone?', explicacion: 'Big decisions like this should be discussed with family or someone you trust first.' },
          { picto: '🃏', situacion: 'An acquaintance invites you to bet money, promising you always win.', opciones: ['I say no and talk to my family if they insist', 'I bet a little to try it out', 'I lend them money to bet instead'], correcta: 0, pista: 'Is there any bet where you always win?', explicacion: 'Nobody always wins at betting. It is better to say no and talk to your family.' }
        ]
      }
    ]
  }
};
