(function () {
  'use strict';
  App.i18n.register({
    title: 'Normas de Educación',
    instruction: 'Escucha la situación. Elige la respuesta que demuestra buena educación.',

    // Daily-life simulation contract (SPEC §3.6 + guia-crear-elementos §2.3)
    context: 'Estás en un sitio donde hay otras personas. Hay una norma de buena educación que ayuda a que todos estemos bien. Elige qué harías tú.',
    hint: '🤔 Piensa: ¿qué hace que las personas se sientan a gusto y en confianza aquí?',
    explanation: '✅ Así se cuida a las personas y el sitio. Las normas de buena educación existen para que todos estemos tranquilos y a gusto.',
    transfer: 'Estas normas te sirven en el cole, en la calle, en el autobús, en el cine y en cualquier sitio con más gente: la buena educación hace que todos convivamos mejor.',

    // Levels
    'level.level1': 'Fácil: situaciones cotidianas',
    'level.level2': 'Medio: en sitios con otras personas',
    'level.level3': 'Difícil: decisiones con más responsabilidad',

    // Speaker labels (character.*)
    'character.teacher': 'Profesor o profesora',
    'character.classmate': 'Un compañero',
    'character.monitor': 'La persona del comedor',
    'character.librarian': 'La bibliotecaria',
    'character.driver': 'El conductor',
    'character.other_child': 'Otro niño',
    'character.person': 'Una persona',
    'character.elder': 'Una persona mayor',
    'character.friend': 'Un amigo',
    'character.viewer': 'Un espectador',

    // Contexts (scenarios)
    'situation.class_talk': 'En clase',
    'situation.ask_permission': 'En clase, levantando la mano',
    'situation.canteen_queue': 'En el comedor',
    'situation.paper_floor': 'En un pasillo',
    'situation.lending_material': 'En el aula',
    'situation.bathroom_wait': 'En el baño',
    'situation.library_silence': 'En la biblioteca',
    'situation.bus_get_on': 'En la parada del autobús',
    'situation.park_play': 'En el parque',
    'situation.recycling_container': 'En el aula o el patio',
    'situation.recycling_paper': 'En el aula o el patio',
    'situation.crossing_light': 'En un paso de peatones',
    'situation.sidewalk_walk': 'En la acera',
    'situation.cinema_phone': 'En el cine',
    'situation.playground_exclude': 'En el recreo',
    'situation.lost_object': 'En clase',
    'situation.own_mistake': 'En clase',
    'situation.argument_couple': 'En el patio',
    'situation.vandalism_wall': 'En el baño o el patio',
    'situation.pet_rescue': 'En la calle',
    'situation.internet_hoax': 'En tu móvil',
    'situation.car_pedestrian': 'Cruzando la calle',
    'situation.table_clean': 'En el comedor',
    'situation.bathroom_paper': 'En el baño',
    'situation.water_tap': 'En el baño',
    'situation.light_class': 'En clase, al salir',
    'situation.speech_listen': 'En clase, un compañero expone',
    'situation.cinema_queue': 'En la cola del cine',
    'situation.phone_class': 'En clase',
    'situation.birthday_invite': 'En el patio',

    // Messages
    'message.teacher_speaking': 'Estoy explicando algo a la clase.',
    'message.question_class': '¿Quién sabe la respuesta?',
    'message.canteen_wait': 'Hay que esperar el turno para entrar.',
    'message.paper_dropped': 'Se ha caído un papel al suelo.',
    'message.lend_pencil': '¿Me dejas el lápiz?',
    'message.bathroom_busy': 'Está ocupado un momento.',
    'message.library_rules': 'Aquí se habla en voz baja.',
    'message.bus_get_on': 'Suban en orden, por favor.',
    'message.park_wait_turn': '¡Es mi turno en el tobogán!',
    'message.recycling_container': 'Tira el envase de plástico, por favor.',
    'message.recycling_paper': 'Tira los folios usados aquí.',
    'message.light_red': 'El semáforo está en rojo.',
    'message.sidewalk_blocked': 'Vas por el medio de la acera.',
    'message.cinema_quiet': 'La película ya ha empezado.',
    'message.playground_exclude': 'No jugamos contigo.',
    'message.object_lost': 'He encontrado una cartera en el suelo.',
    'message.mistake_recognise': 'Te has equivocado en el ejercicio.',
    'message.classmate_fight': '¡Es mío! ¡Me lo ha quitado!',
    'message.wall_graffiti': 'Mira, estoy pintando en la pared.',
    'message.dog_scared': 'El perro está asustado y se ha escapado.',
    'message.news_internet': 'Mira esta noticia que me ha llegado.',
    'message.car_waiting': 'El coche te está esperando para pasar.',
    'message.collect_table': 'Hay que dejar la mesa limpia.',
    'message.bathroom_paper_floor': 'Hay papel de baño en el suelo.',
    'message.tap_left_open': 'El grifo se ha quedado abierto.',
    'message.light_on': 'Vamos a salir del aula.',
    'message.classmate_presents': 'Le toca exponer a un compañero.',
    'message.cinema_queue': 'Hay cola para las entradas.',
    'message.phone_class': 'Suena tu móvil en clase.',
    'message.party_not_invited': 'Hoy es su cumpleaños y no le han invitado.',

    // Options
    'option.quiet_and_listen': 'Me callo y escucho.',
    'option.keep_shouting': 'Sigo gritando.',
    'option.run_out': 'Salgo corriendo.',
    'option.raise_hand': 'Levanto la mano para pedir la palabra.',
    'option.shout_answer': 'Respondo gritando.',
    'option.leave_class': 'Salgo del aula.',
    'option.queue': 'Hago cola y espero mi turno.',
    'option.cut_in': 'Me cuelo delante.',
    'option.sit_floor': 'Me siento en el suelo.',
    'option.pick_up': 'Lo recojo y lo tiro a la papelera.',
    'option.step_on': 'Lo piso y sigo andando.',
    'option.ignore': 'Paso de largo.',
    'option.lend_and_thank': 'Se lo doy y le doy las gracias.',
    'option.refuse': 'No, es mío.',
    'option.break_it': 'Lo rompo.',
    'option.wait_outside': 'Espero fuera con calma.',
    'option.knock_loud': 'Toco la puerta muy fuerte.',
    'option.force_door': 'Intento abrir igualmente.',
    'option.speak_low': 'Hablo en voz baja.',
    'option.speak_loud': 'Hablo fuerte.',
    'option.sing': 'Me pongo a cantar.',
    'option.step_aside': 'Me aparto y dejo pasar.',
    'option.push': 'Empujo para pasar antes.',
    'option.skip_queue': 'Me salto la cola.',
    'option.wait_turn': 'Espero mi turno con paciencia.',
    'option.take_toy': 'Le quito el juguete.',
    'option.shout_child': 'Grito al otro niño.',
    'option.yellow_bin': 'Lo tiro al contenedor amarillo.',
    'option.grey_bin': 'Lo tiro al contenedor gris.',
    'option.blue_bin': 'Lo tiro al contenedor azul.',
    'option.throw_street': 'Lo tiro a la calle.',
    'option.throw_floor': 'Lo tiro al suelo.',
    'option.wait_green': 'Espero a que se ponga verde.',
    'option.cross_red': 'Cruzo en rojo.',
    'option.run_street': 'Echo a correr por la calle.',
    'option.move_aside': 'Me aparto a un lado.',
    'option.stop_middle': 'Me paro en medio sin moverme.',
    'option.silence_phone': 'Lo pongo en silencio y lo guardo.',
    'option.call_friend': 'Llamo a un amigo.',
    'option.play_games': 'Me pongo a jugar.',
    'option.invite_play': 'Le digo: "Ven, jugamos juntos".',
    'option.laugh_with': 'Me río con los demás.',
    'option.do_nothing': 'No digo nada.',
    'option.give_teacher': 'Lo entrego al profesor.',
    'option.keep_it': 'Me lo quedo.',
    'option.hide': 'Lo escondo.',
    'option.say_sorry': 'Reconozco el error y pido perdón.',
    'option.blame_other': 'Echo la culpa a otro.',
    'option.say_nothing': 'Me callo y no digo nada.',
    'option.mediate_calm': 'Les ayudo a hablar y calmarse.',
    'option.take_side': 'Me pongo de un lado.',
    'option.shout_too': 'Grito yo también.',
    'option.tell_teacher': 'Le digo al profesor lo que pasa.',
    'option.join_in': 'Me sumo y pinto con él.',
    'option.help_calm': 'Me acerco despacio y ayudo.',
    'option.shout': 'Grito.',
    'option.run_after': 'Echo a correr detrás.',
    'option.check_before_share': 'La compruebo antes de compartirla.',
    'option.share_fast': 'La comparto ahora mismo.',
    'option.laugh_news': 'Me río de la noticia.',
    'option.wave_thanks': 'Le doy las gracias con la mano.',
    'option.keep_walking': 'Sigo andando sin más.',
    'option.collect_tray': 'Recojo mi bandeja y la dejo en su sitio.',
    'option.leave_tray': 'Dejo la bandeja en la mesa.',
    'option.push_tray': 'La empujo hacia otro sitio.',
    'option.tell_cleaner': 'Aviso a la persona de limpieza.',
    'option.leave_floor': 'Lo dejo en el suelo.',
    'option.step_on_it': 'Lo piso y paso.',
    'option.close_tap': 'Cierro el grifo.',
    'option.leave_open': 'Lo dejo abierto.',
    'option.play_water': 'Juego con el agua.',
    'option.turn_off_light': 'Apago la luz al salir.',
    'option.leave_on': 'La dejo encendida.',
    'option.turn_up_brightness': 'Subo el brillo.',
    'option.listen_carefully': 'Le escucho con atención.',
    'option.talk_same_time': 'Sigo hablando a la vez.',
    'option.play_phone': 'Juego con el móvil.',
    'option.wait_queue': 'Espero mi sitio en la cola.',
    'option.leave_cinema': 'Me voy del cine.',
    'option.put_away': 'Lo guardo en la mochila.',
    'option.use_hidden': 'Lo uso en silencio bajo la mesa.',
    'option.talk_to_them': 'Le pregunto qué le pasa y le animo.',
    'option.bully_them': 'Me burlo de él.',
    'option.ignore_all': 'Paso totalmente de él.',

    // Socratic hints (shown on first mistake)
    'hint.respect_turn': '¿Crees que hablar todos a la vez ayuda a que alguien pueda explicar algo bien?',
    'hint.turn_class': '¿Cómo se pide la palabra para que todos puedan escuchar?',
    'hint.fair_queue': 'Si todos nos colamos, ¿cómo se sentirá la persona que llegó antes?',
    'hint.clean_place': '¿Quién querría pisar papeles al llegar a un sitio? ¿Qué harías tú si vieras uno?',
    'hint.sharing_helps': 'Si compartes tus cosas con alguien, ¿cómo se sentirá? ¿Y tú si te las pidiera?',
    'hint.privacy_respect': 'El baño es un lugar privado. ¿Qué harías para respetar a quien está dentro?',
    'hint.quiet_space': 'En la biblioteca, ¿qué necesita la gente que está leyendo o estudiando?',
    'hint.others_first': 'En el autobús, ¿a quién le toca entrar primero? Piensa en la persona mayor o con movilidad reducida.',
    'hint.turn_park': 'En el parque, ¿cómo se disfruta más del juego: turnándose o peleándose?',
    'hint.recycling_colour': '¿Sabes qué va en cada contenedor? Fíjate en el color y el dibujo.',
    'hint.light_safety': '¿Qué pasa si cruzas cuando está en rojo? ¿Quién te está cuidando?',
    'hint.let_pass': 'En la acera, ¿cómo puede moverse mejor la gente con carritos, sillas o bastón?',
    'hint.respect_others': 'En el cine, ¿qué quiere la gente que ha pagado por la película?',
    'hint.inclusion_friendship': 'Si nadie te dejara jugar, ¿cómo te sentirías? ¿Qué te gustaría que alguien hiciera?',
    'hint.honesty_trust': 'Si has encontrado algo que no es tuyo, ¿qué es lo correcto?',
    'hint.responsibility': 'Cuando te equivocas, ¿qué te hace sentir mejor a ti y a los demás?',
    'hint.dialogue_peace': 'Cuando dos personas discuten, ¿qué puede ayudar más: gritar o escuchar?',
    'hint.common_care': 'Si alguien rompe algo en un sitio público, ¿qué se debe hacer?',
    'hint.animal_wellbeing': 'Si un animal está asustado, ¿qué le ayuda más: gritar o estar tranquilo?',
    'hint.verify_information': 'En internet, ¿cómo sabes si una noticia es verdad antes de compartirla?',
    'hint.thank_drivers': 'Cuando alguien te deja pasar, ¿qué le gustaría que hicieras?',
    'hint.save_water': 'Si el grifo se queda abierto, ¿qué se está perdiendo?',
    'hint.save_energy': 'Al salir de una habitación, ¿qué se queda encendido si nadie apaga la luz?',
    'hint.class_attention': '¿Qué ayuda más a aprender: el móvil o prestar atención?',

    // Generic feedback
    'feedback.correct': '¡Muy bien! Has elegido lo que cuida a las personas y al sitio.',
    'feedback.explanation': 'Esa es la buena educación: cuida de los demás y del lugar para que todos estemos bien.',

    // Completion
    'roundEnd': 'Ronda terminada. Muy bien.',
    'nextLevel': 'Ya estás listo para el siguiente nivel.'
  }, 'es');
})();
