(function () {
  'use strict';
  App.i18n.register({
    title: 'Normas de Educación',
    instruction: 'Escucha la situación. Elige la respuesta que demuestra buena educación.',

    // Daily-life simulation contract (SPEC §3.6 + guia-crear-elementos §2.3)
    contexto: 'Estás en un sitio donde hay otras personas. Hay una norma de buena educación que ayuda a que todos estemos bien. Elige qué harías tú.',
    pista: '🤔 Piensa: ¿qué hace que las personas se sientan a gusto y en confianza aquí?',
    explicacion: '✅ Así se cuida a las personas y el sitio. Las normas de buena educación existen para que todos estemos tranquilos y a gusto.',
    transferencia: 'Estas normas te sirven en el cole, en la calle, en el autobús, en el cine y en cualquier sitio con más gente: la buena educación hace que todos convivamos mejor.',

    // Levels
    'nivel.nivel1': 'Fácil: situaciones cotidianas',
    'nivel.nivel2': 'Medio: en sitios con otras personas',
    'nivel.nivel3': 'Difícil: decisiones con más responsabilidad',

    // Speaker labels (personaje.*)
    'personaje.profesor': 'Profesor o profesora',
    'personaje.companero': 'Un compañero',
    'personaje.monitor': 'La persona del comedor',
    'personaje.bibliotecaria': 'La bibliotecaria',
    'personaje.conductor': 'El conductor',
    'personaje.nino_otro': 'Otro niño',
    'personaje.persona': 'Una persona',
    'personaje.mayor': 'Una persona mayor',
    'personaje.amigo': 'Un amigo',
    'personaje.espectador': 'Un espectador',

    // Contexts (scenarios)
    'situacion.aula_hablar': 'En clase',
    'situacion.pedir_palabra': 'En clase, levantando la mano',
    'situacion.comedor_cola': 'En el comedor',
    'situacion.papel_suelo': 'En un pasillo',
    'situacion.material_prestado': 'En el aula',
    'situacion.bano_espera': 'En el baño',
    'situacion.biblioteca_silencio': 'En la biblioteca',
    'situacion.autobus_sube': 'En la parada del autobús',
    'situacion.parque_juego': 'En el parque',
    'situacion.reciclar_envase': 'En el aula o el patio',
    'situacion.reciclar_papel': 'En el aula o el patio',
    'situacion.cruce_semaforo': 'En un paso de peatones',
    'situacion.acera_andar': 'En la acera',
    'situacion.cine_celular': 'En el cine',
    'situacion.recreo_excluir': 'En el recreo',
    'situacion.perdido_objeto': 'En clase',
    'situacion.error_propio': 'En clase',
    'situacion.discusion_pareja': 'En el patio',
    'situacion.vandalismo_pared': 'En el baño o el patio',
    'situacion.mascota_rescate': 'En la calle',
    'situacion.internet_bulo': 'En tu móvil',
    'situacion.coche_peaton': 'Cruzando la calle',
    'situacion.mesa_limpia': 'En el comedor',
    'situacion.bano_papel': 'En el baño',
    'situacion.agua_grifo': 'En el baño',
    'situacion.luz_aula': 'En clase, al salir',
    'situacion.discurso_escucha': 'En clase, un compañero expone',
    'situacion.fila_cine': 'En la cola del cine',
    'situacion.celular_clase': 'En clase',
    'situacion.cumpleanos_invitar': 'En el patio',

    // Messages
    'mensaje.profesor_hablando': 'Estoy explicando algo a la clase.',
    'mensaje.pregunta_clase': '¿Quién sabe la respuesta?',
    'mensaje.comedor_espera': 'Hay que esperar el turno para entrar.',
    'mensaje.papel_caido': 'Se ha caído un papel al suelo.',
    'mensaje.prestar_material': '¿Me dejas el lápiz?',
    'mensaje.bano_ocupado': 'Está ocupado un momento.',
    'mensaje.biblioteca_normas': 'Aquí se habla en voz baja.',
    'mensaje.autobus_subir': 'Suban en orden, por favor.',
    'mensaje.parque_espera_turno': '¡Es mi turno en el tobogán!',
    'mensaje.envase_reciclar': 'Tira el envase de plástico, por favor.',
    'mensaje.papel_reciclar': 'Tira los folios usados aquí.',
    'mensaje.semaforo_rojo': 'El semáforo está en rojo.',
    'mensaje.acera_ocupada': 'Vas por el medio de la acera.',
    'mensaje.cine_silencio': 'La película ya ha empezado.',
    'mensaje.recreo_excluir': 'No jugamos contigo.',
    'mensaje.objeto_perdido': 'He encontrado una cartera en el suelo.',
    'mensaje.error_reconocer': 'Te has equivocado en el ejercicio.',
    'mensaje.companero_pelea': '¡Es mío! ¡Me lo ha quitado!',
    'mensaje.pintada_pared': 'Mira, estoy pintando en la pared.',
    'mensaje.perro_asustado': 'El perro está asustado y se ha escapado.',
    'mensaje.noticia_internet': 'Mira esta noticia que me ha llegado.',
    'mensaje.coche_esperando': 'El coche te está esperando para pasar.',
    'mensaje.recoger_mesa': 'Hay que dejar la mesa limpia.',
    'mensaje.bano_papel_suelo': 'Hay papel de baño en el suelo.',
    'mensaje.grifo_cerrado': 'El grifo se ha quedado abierto.',
    'mensaje.luz_encendida': 'Vamos a salir del aula.',
    'mensaje.companero_expone': 'Le toca exponer a un compañero.',
    'mensaje.cine_cola': 'Hay cola para las entradas.',
    'mensaje.telefono_clase': 'Suena tu móvil en clase.',
    'mensaje.fiesta_no_invita': 'Hoy es su cumpleaños y no le han invitado.',

    // Options
    'opcion.callar_y_escuchar': 'Me callo y escucho.',
    'opcion.gritar_mas': 'Sigo gritando.',
    'opcion.correr_salir': 'Salgo corriendo.',
    'opcion.levantar_mano': 'Levanto la mano para pedir la palabra.',
    'opcion.gritar_respuesta': 'Respondo gritando.',
    'opcion.salir_aula': 'Salgo del aula.',
    'opcion.hacer_cola': 'Hago cola y espero mi turno.',
    'opcion.colarse': 'Me cuelo delante.',
    'opcion.sentarse_suelo': 'Me siento en el suelo.',
    'opcion.recoger': 'Lo recojo y lo tiro a la papelera.',
    'opcion.pisar': 'Lo piso y sigo andando.',
    'opcion.ignorar': 'Paso de largo.',
    'opcion.prestar_y_gracias': 'Se lo doy y le doy las gracias.',
    'opcion.negarse': 'No, es mío.',
    'opcion.romperlo': 'Lo rompo.',
    'opcion.espaciar_fuera': 'Espero fuera con calma.',
    'opcion.tocar_puerta_fuerte': 'Toco la puerta muy fuerte.',
    'opcion.forzar_puerta': 'Intento abrir igualmente.',
    'opcion.hablar_bajo': 'Hablo en voz baja.',
    'opcion.hablar_alto': 'Hablo fuerte.',
    'opcion.cantar': 'Me pongo a cantar.',
    'opcion.dejar_pasar': 'Me aparto y dejo pasar.',
    'opcion.empujar': 'Empujo para pasar antes.',
    'opcion.saltarse_cola': 'Me salto la cola.',
    'opcion.esperar_turno': 'Espero mi turno con paciencia.',
    'opcion.quitar_juguete': 'Le quito el juguete.',
    'opcion.gritar_al_nino': 'Grito al otro niño.',
    'opcion.contenedor_amarillo': 'Lo tiro al contenedor amarillo.',
    'opcion.contenedor_gris': 'Lo tiro al contenedor gris.',
    'opcion.tirar_calle': 'Lo tiro a la calle.',
    'opcion.contenedor_azul': 'Lo tiro al contenedor azul.',
    'opcion.tirar_suelo': 'Lo tiro al suelo.',
    'opcion.esperar_verde': 'Espero a que se ponga verde.',
    'opcion.cruzar_rojo': 'Cruzo en rojo.',
    'opcion.correr_calle': 'Echo a correr por la calle.',
    'opcion.apartarse': 'Me aparto a un lado.',
    'opcion.pararse_medio': 'Me paro en medio sin moverme.',
    'opcion.silencio_celular': 'Lo pongo en silencio y lo guardo.',
    'opcion.llamar_amigo': 'Llamo a un amigo.',
    'opcion.jugar_videojuego': 'Me pongo a jugar.',
    'opcion.invitar_jugar': 'Le digo: "Ven, jugamos juntos".',
    'opcion.reirse_con_ellos': 'Me río con los demás.',
    'opcion.no_hacer_nada': 'No digo nada.',
    'opcion.entregar_profesor': 'Lo entrego al profesor.',
    'opcion.quedarse_objeto': 'Me lo quedo.',
    'opcion.esconder': 'Lo escondo.',
    'opcion.pedir_perdon': 'Reconozco el error y pido perdón.',
    'opcion.echar_laculpa': 'Echo la culpa a otro.',
    'opcion.no_decir_nada': 'Me callo y no digo nada.',
    'opcion.mediar_palabra': 'Les ayudo a hablar y calmarse.',
    'opcion.ponerse_de_un_lado': 'Me pongo de un lado.',
    'opcion.gritar_tambien': 'Grito yo también.',
    'opcion.avisar_profesor': 'Le digo al profesor lo que pasa.',
    'opcion.sumarme': 'Me sumo y pinto con él.',
    'opcion.ayudar_tranquilo': 'Me acerco despacio y ayudo.',
    'opcion.gritar': 'Grito.',
    'opcion.correr_detras': 'Echo a correr detrás.',
    'opcion.comprobar_antes_compartir': 'La compruebo antes de compartirla.',
    'opcion.compartir_rapido': 'La comparto ahora mismo.',
    'opcion.reirme': 'Me río de la noticia.',
    'opcion.gracias_mano': 'Le doy las gracias con la mano.',
    'opcion.seguir_andando': 'Sigo andando sin más.',
    'opcion.recoger_bandeja': 'Recojo mi bandeja y la dejo en su sitio.',
    'opcion.dejar_bandeja': 'Dejo la bandeja en la mesa.',
    'opcion.empujar_a_otro': 'La empujo hacia otro sitio.',
    'opcion.avisar_limpieza': 'Aviso a la persona de limpieza.',
    'opcion.dejarlo_suelo': 'Lo dejo en el suelo.',
    'opcion.pisarlo': 'Lo piso y paso.',
    'opcion.cerrar_grifo': 'Cierro el grifo.',
    'opcion.dejar_abierto': 'Lo dejo abierto.',
    'opcion.jugar_agua': 'Juego con el agua.',
    'opcion.apagar_luz': 'Apago la luz al salir.',
    'opcion.dejar_encendida': 'La dejo encendida.',
    'opcion.subir_brillo': 'Subo el brillo.',
    'opcion.escuchar_atento': 'Le escucho con atención.',
    'opcion.hablar_a_la_vez': 'Sigo hablando a la vez.',
    'opcion.jugar_telefono': 'Juego con el móvil.',
    'opcion.esperar_cola': 'Espero mi sitio en la cola.',
    'opcion.salir': 'Me voy del cine.',
    'opcion.guardar_mochila': 'Lo guardo en la mochila.',
    'opcion.usar_oculto': 'Lo uso en silencio bajo la mesa.',
    'opcion.hablar_con_el': 'Le pregunto qué le pasa y le animo.',
    'opcion.hacer_bullying': 'Me burlo de él.',
    'opcion.ignorar_todo': 'Paso totalmente de él.',

    // Socratic hints (shown on first mistake)
    'pista.respeto_turno': '¿Crees que hablar todos a la vez ayuda a que alguien pueda explicar algo bien?',
    'pista.turno_clase': '¿Cómo se pide la palabra para que todos puedan escuchar?',
    'pista.cola_justa': 'Si todos nos colamos, ¿cómo se sentirá la persona que llegó antes?',
    'pista.lugar_limpio': '¿Quién querría pisar papeles al llegar a un sitio? ¿Qué harías tú si vieras uno?',
    'pista.compartir_ayuda': 'Si compartes tus cosas con alguien, ¿cómo se sentirá? ¿Y tú si te las pidiera?',
    'pista.intimidad_respeto': 'El baño es un lugar privado. ¿Qué harías para respetar a quien está dentro?',
    'pista.silencio_espacio': 'En la biblioteca, ¿qué necesita la gente que está leyendo o estudiando?',
    'pista.primero_otros': 'En el autobús, ¿a quién le toca entrar primero? Piensa en la persona mayor o con movilidad reducida.',
    'pista.turno_parque': 'En el parque, ¿cómo se disfruta más del juego: turnándose o peleándose?',
    'pista.reciclar_color': '¿Sabes qué va en cada contenedor? Fíjate en el color y el dibujo.',
    'pista.semaforo_seguridad': '¿Qué pasa si cruzas cuando está en rojo? ¿Quién te está cuidando?',
    'pista.dejar_pasar': 'En la acera, ¿cómo puede moverse mejor la gente con carritos, sillas o bastón?',
    'pista.respeto_otros': 'En el cine, ¿qué quiere la gente que ha pagado por la película?',
    'pista.inclusion_amistad': 'Si nadie te dejara jugar, ¿cómo te sentirías? ¿Qué te gustaría que alguien hiciera?',
    'pista.honestidad_confianza': 'Si has encontrado algo que no es tuyo, ¿qué es lo correcto?',
    'pista.responsabilidad': 'Cuando te equivocas, ¿qué te hace sentir mejor a ti y a los demás?',
    'pista.dialogo_paz': 'Cuando dos personas discuten, ¿qué puede ayudar más: gritar o escuchar?',
    'pista.cuidado_comun': 'Si alguien rompe algo en un sitio público, ¿qué se debe hacer?',
    'pista.bienestar_animal': 'Si un animal está asustado, ¿qué le ayuda más: gritar o estar tranquilo?',
    'pista.verificar_informacion': 'En internet, ¿cómo sabes si una noticia es verdad antes de compartirla?',
    'pista.agradecer_conductores': 'Cuando alguien te deja pasar, ¿qué le gustaría que hicieras?',
    'pista.ahorro_agua': 'Si el grifo se queda abierto, ¿qué se está perdiendo?',
    'pista.ahorro_energia': 'Al salir de una habitación, ¿qué se queda encendido si nadie apaga la luz?',
    'pista.atencion_clase': '¿Qué ayuda más a aprender: el móvil o prestar atención?',

    // Generic feedback
    'feedback.correcto': '¡Muy bien! Has elegido lo que cuida a las personas y al sitio.',
    'feedback.explicacion': 'Esa es la buena educación: cuida de los demás y del lugar para que todos estemos bien.',

    // Completion
    'fin_ronda': 'Ronda terminada. Muy bien.',
    'siguiente_nivel': 'Ya estás listo para el siguiente nivel.'
  }, 'es');
})();