(function () {
  'use strict';
  App.i18n.register({
    title: 'Education and Good Manners',
    instruction: 'Listen to the situation. Choose the response that shows good manners.',

    // Daily-life simulation contract (SPEC §3.6 + creating-elements-guide §2.3)
    contexto: 'You are somewhere with other people. There is a rule of good manners that helps everyone feel good. Choose what you would do.',
    pista: '🤔 Think: what helps people feel comfortable and at ease here?',
    explicacion: '✅ That is how we care for people and the place. Good manners exist so everyone can feel at ease.',
    transferencia: 'These manners help you at school, on the street, on the bus, at the cinema and in any busy place: good manners help us all get along better.',

    // Levels
    'nivel.nivel1': 'Easy: everyday situations',
    'nivel.nivel2': 'Medium: in places with other people',
    'nivel.nivel3': 'Hard: decisions with more responsibility',

    // Speaker labels (personaje.*)
    'personaje.profesor': 'Teacher',
    'personaje.companero': 'A classmate',
    'personaje.monitor': 'Canteen staff',
    'personaje.bibliotecaria': 'The librarian',
    'personaje.conductor': 'The driver',
    'personaje.nino_otro': 'Another child',
    'personaje.persona': 'A person',
    'personaje.mayor': 'An older person',
    'personaje.amigo': 'A friend',
    'personaje.espectador': 'A viewer',

    // Contexts (scenarios)
    'situacion.aula_hablar': 'In class',
    'situacion.pedir_palabra': 'In class, raising your hand',
    'situacion.comedor_cola': 'In the canteen',
    'situacion.papel_suelo': 'In a corridor',
    'situacion.material_prestado': 'In class',
    'situacion.bano_espera': 'In the bathroom',
    'situacion.biblioteca_silencio': 'In the library',
    'situacion.autobus_sube': 'At the bus stop',
    'situacion.parque_juego': 'At the park',
    'situacion.reciclar_envase': 'In a room or yard',
    'situacion.reciclar_papel': 'In a room or yard',
    'situacion.cruce_semaforo': 'At a pedestrian crossing',
    'situacion.acera_andar': 'On the sidewalk',
    'situacion.cine_celular': 'At the cinema',
    'situacion.recreo_excluir': 'In the playground',
    'situacion.perdido_objeto': 'In class',
    'situacion.error_propio': 'In class',
    'situacion.discusion_pareja': 'In the playground',
    'situacion.vandalismo_pared': 'In the bathroom or playground',
    'situacion.mascota_rescate': 'On the street',
    'situacion.internet_bulo': 'On your phone',
    'situacion.coche_peaton': 'Crossing the street',
    'situacion.mesa_limpia': 'In the canteen',
    'situacion.bano_papel': 'In the bathroom',
    'situacion.agua_grifo': 'In the bathroom',
    'situacion.luz_aula': 'In class, leaving',
    'situacion.discurso_escucha': 'In class, a classmate presents',
    'situacion.fila_cine': 'In the cinema queue',
    'situacion.celular_clase': 'In class',
    'situacion.cumpleanos_invitar': 'In the playground',

    // Messages
    'mensaje.profesor_hablando': 'I am explaining something to the class.',
    'mensaje.pregunta_clase': 'Who knows the answer?',
    'mensaje.comedor_espera': 'Please wait your turn to go in.',
    'mensaje.papel_caido': 'A piece of paper fell on the floor.',
    'mensaje.prestar_material': 'Can I borrow your pencil?',
    'mensaje.bano_ocupado': 'It is busy for a moment.',
    'mensaje.biblioteca_normas': 'People speak quietly here.',
    'mensaje.autobus_subir': 'Please get on in order.',
    'mensaje.parque_espera_turno': 'It is my turn on the slide!',
    'mensaje.envase_reciclar': 'Please recycle this plastic container.',
    'mensaje.papel_reciclar': 'Put the used sheets here.',
    'mensaje.semaforo_rojo': 'The traffic light is red.',
    'mensaje.acera_ocupada': 'You are walking in the middle of the sidewalk.',
    'mensaje.cine_silencio': 'The movie has already started.',
    'mensaje.recreo_excluir': 'We do not want to play with you.',
    'mensaje.objeto_perdido': 'I found a wallet on the floor.',
    'mensaje.error_reconocer': 'You made a mistake on the exercise.',
    'mensaje.companero_pelea': 'It is mine! He took it from me!',
    'mensaje.pintada_pared': 'Look, I am drawing on the wall.',
    'mensaje.perro_asustado': 'The dog is scared and ran off.',
    'mensaje.noticia_internet': 'Look at this news I just got.',
    'mensaje.coche_esperando': 'The car is waiting for you to cross.',
    'mensaje.recoger_mesa': 'Please leave the table clean.',
    'mensaje.bano_papel_suelo': 'There is toilet paper on the floor.',
    'mensaje.grifo_cerrado': 'The tap was left running.',
    'mensaje.luz_encendida': 'We are leaving the classroom.',
    'mensaje.companero_expone': 'It is a classmate\'s turn to present.',
    'mensaje.cine_cola': 'There is a queue for tickets.',
    'mensaje.telefono_clase': 'Your phone rings in class.',
    'mensaje.fiesta_no_invita': 'Today is their birthday and they were not invited.',

    // Options
    'opcion.callar_y_escuchar': 'I stay quiet and listen.',
    'opcion.gritar_mas': 'I keep shouting.',
    'opcion.correr_salir': 'I run out.',
    'opcion.levantar_mano': 'I raise my hand to ask for a turn.',
    'opcion.gritar_respuesta': 'I shout the answer.',
    'opcion.salir_aula': 'I leave the classroom.',
    'opcion.hacer_cola': 'I queue and wait my turn.',
    'opcion.colarse': 'I push in at the front.',
    'opcion.sentarse_suelo': 'I sit on the floor.',
    'opcion.recoger': 'I pick it up and throw it in the bin.',
    'opcion.pisar': 'I step on it and keep walking.',
    'opcion.ignorar': 'I walk past it.',
    'opcion.prestar_y_gracias': 'I lend it and say thank you.',
    'opcion.negarse': 'No, it is mine.',
    'opcion.romperlo': 'I break it.',
    'opcion.espaciar_fuera': 'I wait outside calmly.',
    'opcion.tocar_puerta_fuerte': 'I knock on the door hard.',
    'opcion.forzar_puerta': 'I try to open it anyway.',
    'opcion.hablar_bajo': 'I speak in a low voice.',
    'opcion.hablar_alto': 'I speak loudly.',
    'opcion.cantar': 'I start singing.',
    'opcion.dejar_pasar': 'I step aside and let them pass.',
    'opcion.empujar': 'I push to go first.',
    'opcion.saltarse_cola': 'I skip the queue.',
    'opcion.esperar_turno': 'I wait my turn patiently.',
    'opcion.quitar_juguete': 'I take the toy away.',
    'opcion.gritar_al_nino': 'I shout at the other child.',
    'opcion.contenedor_amarillo': 'I put it in the yellow bin.',
    'opcion.contenedor_gris': 'I put it in the grey bin.',
    'opcion.contenedor_azul': 'I put it in the blue bin.',
    'opcion.tirar_calle': 'I throw it on the street.',
    'opcion.tirar_suelo': 'I throw it on the ground.',
    'opcion.esperar_verde': 'I wait for the green light.',
    'opcion.cruzar_rojo': 'I cross on red.',
    'opcion.correr_calle': 'I run across the road.',
    'opcion.apartarse': 'I move to one side.',
    'opcion.pararse_medio': 'I stop in the middle.',
    'opcion.silencio_celular': 'I silence it and put it away.',
    'opcion.llamar_amigo': 'I call a friend.',
    'opcion.jugar_videojuego': 'I start playing a game.',
    'opcion.invitar_jugar': 'I say: "Come, let\'s play together".',
    'opcion.reirse_con_ellos': 'I laugh with the others.',
    'opcion.no_hacer_nada': 'I do nothing.',
    'opcion.entregar_profesor': 'I give it to the teacher.',
    'opcion.quedarse_objeto': 'I keep it.',
    'opcion.esconder': 'I hide it.',
    'opcion.pedir_perdon': 'I admit the mistake and say sorry.',
    'opcion.echar_laculpa': 'I blame someone else.',
    'opcion.no_decir_nada': 'I stay quiet and say nothing.',
    'opcion.mediar_palabra': 'I help them talk and calm down.',
    'opcion.ponerse_de_un_lado': 'I take one side.',
    'opcion.gritar_tambien': 'I shout too.',
    'opcion.avisar_profesor': 'I tell the teacher what is happening.',
    'opcion.sumarme': 'I join in and paint with them.',
    'opcion.ayudar_tranquilo': 'I walk up calmly and help.',
    'opcion.gritar': 'I shout.',
    'opcion.correr_detras': 'I run after the dog.',
    'opcion.comprobar_antes_compartir': 'I check it before sharing.',
    'opcion.compartir_rapido': 'I share it right away.',
    'opcion.reirme': 'I laugh at the news.',
    'opcion.gracias_mano': 'I thank the driver with my hand.',
    'opcion.seguir_andando': 'I keep walking.',
    'opcion.recoger_bandeja': 'I clear my tray and put it away.',
    'opcion.dejar_bandeja': 'I leave my tray on the table.',
    'opcion.empujar_a_otro': 'I push it toward someone else.',
    'opcion.avisar_limpieza': 'I tell the cleaning staff.',
    'opcion.dejarlo_suelo': 'I leave it on the floor.',
    'opcion.pisarlo': 'I step on it.',
    'opcion.cerrar_grifo': 'I close the tap.',
    'opcion.dejar_abierto': 'I leave it open.',
    'opcion.jugar_agua': 'I play with the water.',
    'opcion.apagar_luz': 'I turn off the light when leaving.',
    'opcion.dejar_encendida': 'I leave it on.',
    'opcion.subir_brillo': 'I turn the brightness up.',
    'opcion.escuchar_atento': 'I listen carefully.',
    'opcion.hablar_a_la_vez': 'I keep talking at the same time.',
    'opcion.jugar_telefono': 'I play with my phone.',
    'opcion.esperar_cola': 'I wait my place in the queue.',
    'opcion.salir': 'I leave the cinema.',
    'opcion.guardar_mochila': 'I put it in my backpack.',
    'opcion.usar_oculto': 'I use it quietly under the desk.',
    'opcion.hablar_con_el': 'I ask them what is wrong and cheer them up.',
    'opcion.hacer_bullying': 'I make fun of them.',
    'opcion.ignorar_todo': 'I ignore them completely.',

    // Socratic hints (shown on first mistake)
    'pista.respeto_turno': 'Do you think everyone talking at once helps anyone explain something well?',
    'pista.turno_clase': 'How do you ask for a turn so everyone can hear?',
    'pista.cola_justa': 'If everyone pushes in, how would the person who arrived first feel?',
    'pista.lugar_limpio': 'Who would want to step on papers when they arrive somewhere? What would you do if you saw one?',
    'pista.compartir_ayuda': 'If you share your things with someone, how do they feel? And you, if they asked you?',
    'pista.intimidad_respeto': 'A bathroom is a private place. What would you do to respect the person inside?',
    'pista.silencio_espacio': 'In a library, what do people reading or studying need?',
    'pista.primero_otros': 'On a bus, who should go first? Think about older people or those with reduced mobility.',
    'pista.turno_parque': 'At the park, how do you enjoy play more: taking turns or fighting?',
    'pista.reciclar_color': 'Do you know what goes in each bin? Look at the colour and the picture.',
    'pista.semaforo_seguridad': 'What happens if you cross on red? Who is keeping you safe?',
    'pista.dejar_pasar': 'On a sidewalk, how can people with prams, wheelchairs or canes move best?',
    'pista.respeto_otros': 'At the cinema, what do people who paid for the movie want?',
    'pista.inclusion_amistad': 'If nobody let you play, how would you feel? What would you like someone to do?',
    'pista.honestidad_confianza': 'If you found something that is not yours, what is the right thing to do?',
    'pista.responsabilidad': 'When you make a mistake, what makes you and others feel better?',
    'pista.dialogo_paz': 'When two people argue, what helps more: shouting or listening?',
    'pista.cuidado_comun': 'If someone damages a public place, what should be done?',
    'pista.bienestar_animal': 'If an animal is scared, what helps it most: shouting or being calm?',
    'pista.verificar_informacion': 'On the internet, how do you know if a news story is true before sharing it?',
    'pista.agradecer_conductores': 'When someone lets you cross, what would they like you to do?',
    'pista.ahorro_agua': 'If the tap is left running, what is being wasted?',
    'pista.ahorro_energia': 'When leaving a room, what stays on if nobody turns off the light?',
    'pista.atencion_clase': 'What helps you learn more: the phone or paying attention?',

    // Generic feedback
    'feedback.correcto': 'Very good! You picked what cares for people and the place.',
    'feedback.explicacion': 'That is good manners: it cares for others and the place so everyone can be well.',

    // Completion
    'fin_ronda': 'Round finished. Very good.',
    'siguiente_nivel': 'You are ready for the next level.'
  }, 'en');
})();