(function () {
  'use strict';
  App.i18n.register({
    title: 'Education and Good Manners',
    instruction: 'Listen to the situation. Choose the response that shows good manners.',

    // Daily-life simulation contract (SPEC §3.6 + creating-elements-guide §2.3)
    context: 'You are somewhere with other people. There is a rule of good manners that helps everyone feel good. Choose what you would do.',
    hint: '🤔 Think: what helps people feel comfortable and at ease here?',
    explanation: '✅ That is how we care for people and the place. Good manners exist so everyone can feel at ease.',
    transfer: 'These manners help you at school, on the street, on the bus, at the cinema and in any busy place: good manners help us all get along better.',

    // Levels
    'level.level1': 'Easy: everyday situations',
    'level.level2': 'Medium: in places with other people',
    'level.level3': 'Hard: decisions with more responsibility',

    // Speaker labels (character.*)
    'character.teacher': 'Teacher',
    'character.classmate': 'A classmate',
    'character.monitor': 'Canteen staff',
    'character.librarian': 'The librarian',
    'character.driver': 'The driver',
    'character.other_child': 'Another child',
    'character.person': 'A person',
    'character.elder': 'An older person',
    'character.friend': 'A friend',
    'character.viewer': 'A viewer',

    // Contexts (scenarios)
    'situation.class_talk': 'In class',
    'situation.ask_permission': 'In class, raising your hand',
    'situation.canteen_queue': 'In the canteen',
    'situation.paper_floor': 'In a corridor',
    'situation.lending_material': 'In class',
    'situation.bathroom_wait': 'In the bathroom',
    'situation.library_silence': 'In the library',
    'situation.bus_get_on': 'At the bus stop',
    'situation.park_play': 'At the park',
    'situation.recycling_container': 'In a room or yard',
    'situation.recycling_paper': 'In a room or yard',
    'situation.crossing_light': 'At a pedestrian crossing',
    'situation.sidewalk_walk': 'On the sidewalk',
    'situation.cinema_phone': 'At the cinema',
    'situation.playground_exclude': 'In the playground',
    'situation.lost_object': 'In class',
    'situation.own_mistake': 'In class',
    'situation.argument_couple': 'In the playground',
    'situation.vandalism_wall': 'In the bathroom or playground',
    'situation.pet_rescue': 'On the street',
    'situation.internet_hoax': 'On your phone',
    'situation.car_pedestrian': 'Crossing the street',
    'situation.table_clean': 'In the canteen',
    'situation.bathroom_paper': 'In the bathroom',
    'situation.water_tap': 'In the bathroom',
    'situation.light_class': 'In class, leaving',
    'situation.speech_listen': 'In class, a classmate presents',
    'situation.cinema_queue': 'In the cinema queue',
    'situation.phone_class': 'In class',
    'situation.birthday_invite': 'In the playground',

    // Messages
    'message.teacher_speaking': 'I am explaining something to the class.',
    'message.question_class': 'Who knows the answer?',
    'message.canteen_wait': 'Please wait your turn to go in.',
    'message.paper_dropped': 'A piece of paper fell on the floor.',
    'message.lend_pencil': 'Can I borrow your pencil?',
    'message.bathroom_busy': 'It is busy for a moment.',
    'message.library_rules': 'People speak quietly here.',
    'message.bus_get_on': 'Please get on in order.',
    'message.park_wait_turn': 'It is my turn on the slide!',
    'message.recycling_container': 'Please recycle this plastic container.',
    'message.recycling_paper': 'Put the used sheets here.',
    'message.light_red': 'The traffic light is red.',
    'message.sidewalk_blocked': 'You are walking in the middle of the sidewalk.',
    'message.cinema_quiet': 'The movie has already started.',
    'message.playground_exclude': 'We do not want to play with you.',
    'message.object_lost': 'I found a wallet on the floor.',
    'message.mistake_recognise': 'You made a mistake on the exercise.',
    'message.classmate_fight': 'It is mine! He took it from me!',
    'message.wall_graffiti': 'Look, I am drawing on the wall.',
    'message.dog_scared': 'The dog is scared and ran off.',
    'message.news_internet': 'Look at this news I just got.',
    'message.car_waiting': 'The car is waiting for you to cross.',
    'message.collect_table': 'Please leave the table clean.',
    'message.bathroom_paper_floor': 'There is toilet paper on the floor.',
    'message.tap_left_open': 'The tap was left running.',
    'message.light_on': 'We are leaving the classroom.',
    'message.classmate_presents': 'It is a classmate\'s turn to present.',
    'message.cinema_queue': 'There is a queue for tickets.',
    'message.phone_class': 'Your phone rings in class.',
    'message.party_not_invited': 'Today is their birthday and they were not invited.',

    // Options
    'option.quiet_and_listen': 'I stay quiet and listen.',
    'option.keep_shouting': 'I keep shouting.',
    'option.run_out': 'I run out.',
    'option.raise_hand': 'I raise my hand to ask for a turn.',
    'option.shout_answer': 'I shout the answer.',
    'option.leave_class': 'I leave the classroom.',
    'option.queue': 'I queue and wait my turn.',
    'option.cut_in': 'I push in at the front.',
    'option.sit_floor': 'I sit on the floor.',
    'option.pick_up': 'I pick it up and throw it in the bin.',
    'option.step_on': 'I step on it and keep walking.',
    'option.ignore': 'I walk past it.',
    'option.lend_and_thank': 'I lend it and say thank you.',
    'option.refuse': 'No, it is mine.',
    'option.break_it': 'I break it.',
    'option.wait_outside': 'I wait outside calmly.',
    'option.knock_loud': 'I knock on the door hard.',
    'option.force_door': 'I try to open it anyway.',
    'option.speak_low': 'I speak in a low voice.',
    'option.speak_loud': 'I speak loudly.',
    'option.sing': 'I start singing.',
    'option.step_aside': 'I step aside and let them pass.',
    'option.push': 'I push to go first.',
    'option.skip_queue': 'I skip the queue.',
    'option.wait_turn': 'I wait my turn patiently.',
    'option.take_toy': 'I take the toy away.',
    'option.shout_child': 'I shout at the other child.',
    'option.yellow_bin': 'I put it in the yellow bin.',
    'option.grey_bin': 'I put it in the grey bin.',
    'option.blue_bin': 'I put it in the blue bin.',
    'option.throw_street': 'I throw it on the street.',
    'option.throw_floor': 'I throw it on the ground.',
    'option.wait_green': 'I wait for the green light.',
    'option.cross_red': 'I cross on red.',
    'option.run_street': 'I run across the road.',
    'option.move_aside': 'I move to one side.',
    'option.stop_middle': 'I stop in the middle.',
    'option.silence_phone': 'I silence it and put it away.',
    'option.call_friend': 'I call a friend.',
    'option.play_games': 'I start playing a game.',
    'option.invite_play': 'I say: "Come, let\'s play together".',
    'option.laugh_with': 'I laugh with the others.',
    'option.do_nothing': 'I do nothing.',
    'option.give_teacher': 'I give it to the teacher.',
    'option.keep_it': 'I keep it.',
    'option.hide': 'I hide it.',
    'option.say_sorry': 'I admit the mistake and say sorry.',
    'option.blame_other': 'I blame someone else.',
    'option.say_nothing': 'I stay quiet and say nothing.',
    'option.mediate_calm': 'I help them talk and calm down.',
    'option.take_side': 'I take one side.',
    'option.shout_too': 'I shout too.',
    'option.tell_teacher': 'I tell the teacher what is happening.',
    'option.join_in': 'I join in and paint with them.',
    'option.help_calm': 'I walk up calmly and help.',
    'option.shout': 'I shout.',
    'option.run_after': 'I run after the dog.',
    'option.check_before_share': 'I check it before sharing.',
    'option.share_fast': 'I share it right away.',
    'option.laugh_news': 'I laugh at the news.',
    'option.wave_thanks': 'I thank the driver with my hand.',
    'option.keep_walking': 'I keep walking.',
    'option.collect_tray': 'I clear my tray and put it away.',
    'option.leave_tray': 'I leave my tray on the table.',
    'option.push_tray': 'I push it toward someone else.',
    'option.tell_cleaner': 'I tell the cleaning staff.',
    'option.leave_floor': 'I leave it on the floor.',
    'option.step_on_it': 'I step on it.',
    'option.close_tap': 'I close the tap.',
    'option.leave_open': 'I leave it open.',
    'option.play_water': 'I play with the water.',
    'option.turn_off_light': 'I turn off the light when leaving.',
    'option.leave_on': 'I leave it on.',
    'option.turn_up_brightness': 'I turn the brightness up.',
    'option.listen_carefully': 'I listen carefully.',
    'option.talk_same_time': 'I keep talking at the same time.',
    'option.play_phone': 'I play with my phone.',
    'option.wait_queue': 'I wait my place in the queue.',
    'option.leave_cinema': 'I leave the cinema.',
    'option.put_away': 'I put it in my backpack.',
    'option.use_hidden': 'I use it quietly under the desk.',
    'option.talk_to_them': 'I ask them what is wrong and cheer them up.',
    'option.bully_them': 'I make fun of them.',
    'option.ignore_all': 'I ignore them completely.',

    // Socratic hints (shown on first mistake)
    'hint.respect_turn': 'Do you think everyone talking at once helps anyone explain something well?',
    'hint.turn_class': 'How do you ask for a turn so everyone can hear?',
    'hint.fair_queue': 'If everyone pushes in, how would the person who arrived first feel?',
    'hint.clean_place': 'Who would want to step on papers when they arrive somewhere? What would you do if you saw one?',
    'hint.sharing_helps': 'If you share your things with someone, how do they feel? And you, if they asked you?',
    'hint.privacy_respect': 'A bathroom is a private place. What would you do to respect the person inside?',
    'hint.quiet_space': 'In a library, what do people reading or studying need?',
    'hint.others_first': 'On a bus, who should go first? Think about older people or those with reduced mobility.',
    'hint.turn_park': 'At the park, how do you enjoy play more: taking turns or fighting?',
    'hint.recycling_colour': 'Do you know what goes in each bin? Look at the colour and the picture.',
    'hint.light_safety': 'What happens if you cross on red? Who is keeping you safe?',
    'hint.let_pass': 'On a sidewalk, how can people with prams, wheelchairs or canes move best?',
    'hint.respect_others': 'At the cinema, what do people who paid for the movie want?',
    'hint.inclusion_friendship': 'If nobody let you play, how would you feel? What would you like someone to do?',
    'hint.honesty_trust': 'If you found something that is not yours, what is the right thing to do?',
    'hint.responsibility': 'When you make a mistake, what makes you and others feel better?',
    'hint.dialogue_peace': 'When two people argue, what helps more: shouting or listening?',
    'hint.common_care': 'If someone damages a public place, what should be done?',
    'hint.animal_wellbeing': 'If an animal is scared, what helps it most: shouting or being calm?',
    'hint.verify_information': 'On the internet, how do you know if a news story is true before sharing it?',
    'hint.thank_drivers': 'When someone lets you cross, what would they like you to do?',
    'hint.save_water': 'If the tap is left running, what is being wasted?',
    'hint.save_energy': 'When leaving a room, what stays on if nobody turns off the light?',
    'hint.class_attention': 'What helps you learn more: the phone or paying attention?',

    // Generic feedback
    'feedback.correct': 'Very good! You picked what cares for people and the place.',
    'feedback.explanation': 'That is good manners: it cares for others and the place so everyone can be well.',

    // Completion
    'roundEnd': 'Round finished. Very good.',
    'nextLevel': 'You are ready for the next level.'
  }, 'en');
})();
