/* ============================================================
   Routime — Textos de piano-teclas (ES)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "🎹 Piano",
    "saludoInicial": "¡Hola, futuro músico! 🎵 ¿Cómo te llamas?",
    "escucharAria": "Escuchar",
    "tuNombreAria": "Tu nombre",
    "vamos": "✅ ¡Vamos!",
    "menu": "← Menú",
    "miNombre": "✏️ Mi nombre",
    "saludoMusico": "¡Hola, músico! 🎵",
    "saludoConNombre": "¡Hola, {nombre}! 🎵",
    "elegirModo": "Elige cómo quieres tocar 🎶",
    "elegirModoTTS": ". Elige cómo quieres tocar.",
    "modoLibreNombre": "Toca libre",
    "modoLibreDetalle": "Explora las notas y crea melodías.",
    "modoSeguirNombre": "Sigue la melodía",
    "modoSeguirDetalle": "Repite la canción que oyes.",
    "modoSimonNombre": "Simón dice",
    "modoSimonDetalle": "Memoriza y repite la secuencia.",
    "modoCancionesNombre": "Canciones",
    "modoCancionesDetalle": "Aprende canciones famosas.",
    "modoCompositorNombre": "Compositor",
    "modoCompositorDetalle": "Crea tu propia canción.",
    "explicacionAria": "Explicación",
    "instruccionLibre": "¡Toca las teclas de tu teclado como si fuera un piano! 🎹",
    "explicarLibreTTS": "Toca las teclas de tu teclado: A S D F G H J para las notas blancas, y W E T Y U para las negras. ¡Crea tu propia música!",
    "octavaMenosBtn": "◀️ Octava",
    "octavaMasBtn": "Octava ▶️",
    "octavaMasTTS": "Octava más alta",
    "octavaMenosTTS": "Octava más baja",
    "grabando": "🔴 Grabando",
    "parar": "⏹️ Parar",
    "grabandoAviso": "¡Grabando! Toca tus notas.",
    "grabadoAviso": "¡Grabado! {n} notas.",
    "noTocado": "No has tocado nada.",
    "reproducirGrabacionBtn": "▶️ Escuchar grabación",
    "octavaMaxima": "Ya estás en la octava más aguda.",
    "octavaMinima": "Ya estás en la octava más grave.",
    "seguirHeaderTitulo": "Sigue la melodía",
    "instruccionSeguirDefault": "Escucha la melodía y repítela.",
    "instruccionSeguirConNombre": "Escucha la melodía \"{nombre}\" y repítela.",
    "reproducirMelodiaBtn": "▶️ Reproducir melodía",
    "ahoraRepitela": "¡Ahora repítela!",
    "perfecto": "¡Perfecto! 🎉",
    "casiIntentalo": "¡Casi! Inténtalo de nuevo.",
    "simonHeaderTitulo": "🔮 Simón dice",
    "instruccionSimon": "Observa la secuencia y repítela.",
    "notaDo": "Nota Do",
    "notaMi": "Nota Mi",
    "notaSol": "Nota Sol",
    "notaSi": "Nota Si",
    "nivelLabel": "Nivel: {n}",
    "puntosLabel": "Puntos: {n}",
    "observaSecuencia": "Observa la secuencia...",
    "tuTurno": "¡Tu turno! Repite la secuencia.",
    "correcto": "¡Correcto! 🎉",
    "observaSiguiente": "Observa la siguiente...",
    "finJuego": "¡Ups! Fin del juego. Puntos: {n}",
    "cancionesHeaderTitulo": "Canciones",
    "elegirCancion": "Elige una canción para aprender 🎤",
    "dificultadFacil": "Fácil",
    "dificultadMedia": "Media",
    "cancionInstruccion": "Canción: {nombre}. Escucha primero, luego repite.",
    "escuchando": "Escuchando...",
    "ahoraTuRepite": "¡Ahora tú! Repite la canción.",
    "cancionCumpleanos": "🎂 Cumpleaños",
    "cancionEstrellita": "⭐ Estrellita",
    "cancionHimnoalegria": "✨ Himno de la alegría",
    "cancionVerde": "🌿 Verde",
    "compositorHeaderTitulo": "✍️ Compositor",
    "crearMelodia": "Crea tu propia melodía. ¡Sé creativo!",
    "placeholderInicial": "Toca notas para añadir...",
    "placeholderVacio": "Toca notas con el teclado para añadir...",
    "reproducirCompBtn": "▶️ Reproducir",
    "borrarCompBtn": "🗑️ Borrar",
    "guardarCompBtn": "💾 Guardar",
    "tusCanciones": "💾 Tus canciones",
    "notasCount": "({n} notas)",
    "bonitaMelodia": "¡Bonita melodía! 🎵",
    "borrado": "Borrado.",
    "tocaNotasPrimero": "¡Toca algunas notas primero!",
    "promptNombreCancion": "¿Cómo quieres llamar a tu canción?",
    "promptNombreDefault": "Mi canción",
    "nombreCancionAria": "Nombre de la canción",
    "confirmarGuardarBtn": "✅ Guardar",
    "cancelarBtn": "❌ Cancelar",
    "cancionGuardada": "¡Canción guardada! 🎉",
    "cancionBorrada": "Canción borrada.",
    "bienvenidoConNombre": "¡Hola, {nombre}! ¡Bienvenido al piano!",
    "escribeNombreTTS": "Escribe tu nombre para empezar.",
    "melodiaAscendente": "Escala ascendente",
    "melodiaDescendente": "Escala descendente",
    "melodiaDoReMi": "Do Re Mi",
    "melodiaArcoiris": "Arco iris",
    "melodiaOndina": "Ondina",
    "nota": {"C":"Do","C#":"Do sostenido","D":"Re","D#":"Re sostenido","E":"Mi","F":"Fa","F#":"Fa sostenido","G":"Sol","G#":"Sol sostenido","A":"La","A#":"La sostenido","B":"Si"}
  ,
  "transferencia": "Esto te ayuda a disfrutar de la música y a tocar con más confianza."
}, 'es');
})();
