/* ============================================================
   Routime — Textos de piano-teclas (EN)
   Archivo específico del idioma. Generado/actualizado por scripts/refactor-i18n.js.
   Se carga condicionalmente desde index.html según App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "title": "🎹 Piano",
    "saludoInicial": "Hi, future musician! 🎵 What's your name?",
    "escucharAria": "Listen",
    "tuNombreAria": "Your name",
    "vamos": "✅ Let's go!",
    "menu": "← Menu",
    "miNombre": "✏️ My name",
    "saludoMusico": "Hi, musician! 🎵",
    "saludoConNombre": "Hi, {nombre}! 🎵",
    "elegirModo": "Choose how you want to play 🎶",
    "elegirModoTTS": ". Choose how you want to play.",
    "modoLibreNombre": "Free play",
    "modoLibreDetalle": "Explore the notes and make tunes.",
    "modoSeguirNombre": "Follow the tune",
    "modoSeguirDetalle": "Repeat the song you hear.",
    "modoSimonNombre": "Simon Says",
    "modoSimonDetalle": "Remember and repeat the pattern.",
    "modoCancionesNombre": "Songs",
    "modoCancionesDetalle": "Learn well-known songs.",
    "modoCompositorNombre": "Composer",
    "modoCompositorDetalle": "Create your own song.",
    "explicacionAria": "Explanation",
    "instruccionLibre": "Press the keys on your keyboard like a piano! 🎹",
    "explicarLibreTTS": "Press the keys on your keyboard. Use A S D F G H J for the white notes, and W E T Y U for the black notes. Make your own music!",
    "octavaMenosBtn": "◀️ Octave",
    "octavaMasBtn": "Octave ▶️",
    "octavaMasTTS": "Higher octave",
    "octavaMenosTTS": "Lower octave",
    "grabando": "🔴 Recording",
    "parar": "⏹️ Stop",
    "grabandoAviso": "Recording! Play your notes.",
    "grabadoAviso": "Recorded! {n} notes.",
    "noTocado": "You haven't played anything.",
    "reproducirGrabacionBtn": "▶️ Listen to recording",
    "octavaMaxima": "You are already in the highest octave.",
    "octavaMinima": "You are already in the lowest octave.",
    "seguirHeaderTitulo": "Follow the tune",
    "instruccionSeguirDefault": "Listen to the tune and repeat it.",
    "instruccionSeguirConNombre": "Listen to \"{nombre}\" and repeat it.",
    "reproducirMelodiaBtn": "▶️ Play the tune",
    "ahoraRepitela": "Now repeat it!",
    "perfecto": "Perfect! 🎉",
    "casiIntentalo": "Almost! Try again.",
    "simonHeaderTitulo": "🔮 Simon Says",
    "instruccionSimon": "Watch the pattern and repeat it.",
    "notaDo": "Note C",
    "notaMi": "Note E",
    "notaSol": "Note G",
    "notaSi": "Note B",
    "nivelLabel": "Level: {n}",
    "puntosLabel": "Points: {n}",
    "observaSecuencia": "Watch the pattern...",
    "tuTurno": "Your turn! Repeat the pattern.",
    "correcto": "Correct! 🎉",
    "observaSiguiente": "Watch the next one...",
    "finJuego": "Oops! Game over. Points: {n}",
    "cancionesHeaderTitulo": "Songs",
    "elegirCancion": "Choose a song to learn 🎤",
    "dificultadFacil": "Easy",
    "dificultadMedia": "Medium",
    "cancionInstruccion": "Song: {nombre}. Listen first, then repeat.",
    "escuchando": "Listening...",
    "ahoraTuRepite": "Now you! Repeat the song.",
    "cancionCumpleanos": "🎂 Happy Birthday",
    "cancionEstrellita": "⭐ Twinkle Twinkle",
    "cancionHimnoalegria": "✨ Ode to Joy",
    "cancionVerde": "🌿 Green",
    "compositorHeaderTitulo": "✍️ Composer",
    "crearMelodia": "Create your own tune. Be creative!",
    "placeholderInicial": "Play notes to add them...",
    "placeholderVacio": "Play notes on the keyboard to add them...",
    "reproducirCompBtn": "▶️ Play",
    "borrarCompBtn": "🗑️ Delete",
    "guardarCompBtn": "💾 Save",
    "tusCanciones": "💾 Your songs",
    "notasCount": "({n} notes)",
    "bonitaMelodia": "Lovely tune! 🎵",
    "borrado": "Deleted.",
    "tocaNotasPrimero": "Play some notes first!",
    "promptNombreCancion": "What do you want to call your song?",
    "promptNombreDefault": "My song",
    "nombreCancionAria": "Song name",
    "confirmarGuardarBtn": "✅ Save",
    "cancelarBtn": "❌ Cancel",
    "cancionGuardada": "Song saved! 🎉",
    "cancionBorrada": "Song deleted.",
    "bienvenidoConNombre": "Hi, {nombre}! Welcome to the piano!",
    "escribeNombreTTS": "Type your name to start.",
    "melodiaAscendente": "Going up",
    "melodiaDescendente": "Going down",
    "melodiaDoReMi": "Do Re Mi",
    "melodiaArcoiris": "Rainbow",
    "melodiaOndina": "Water song",
    "nota": {"C":"C","C#":"C sharp","D":"D","D#":"D sharp","E":"E","F":"F","F#":"F sharp","G":"G","G#":"G sharp","A":"A","A#":"A sharp","B":"B"}
  ,
  "transferencia": "This helps you enjoy music and play with more confidence."
}, 'en');
})();
